### ISSUE TITLE
[Request] Window dimensions

### ISSUE THREAD

**Issue by luizaugustomm** [lainsce/quilter#1]
Hey Lains,

Congratulations for releasing another great app. Quilter is the one I was looking for <3.
As a user feedback, I suggest you to save the current height and width of the window so that when the user closes an re-opens Quilter, the window keeps its last dimension.

[]s
Luiz

**Comment by lainsce** [comment]
Will do! Expect this on 1.0.2! :+1:

**Comment by lainsce** [comment]
Fixed in a new commit on master ;)
