### ISSUE TITLE
Won't show local images (missing HTML content support?)

### ISSUE THREAD

**Issue by js-d-coder** [lainsce/quilter#101]
* Won't show local images (missing HTML content support?)
* I am using this app to view local copy of [You-Dont-Know-JS](https://github.com/getify/You-Dont-Know-JS) from Github. In preview of Readme.md file, local images attached with HTML `img` tag won't show up.

![screenshot from 2017-11-12 14-09-13](https://user-images.githubusercontent.com/23054879/32697340-63c274dc-c7b4-11e7-807a-d50a4393f1b0.png)  

* You can confirm what it should look like by visiting the page of You-Dont-Know-JS

* Using Quilter version 1.4.2  

Thanks for this app, enjoyed it!

**Comment by lainsce** [comment]
Yeah, inline HTML isn’t supported due to the nature of translating Markdown into HTML currently done... I’ll see what I can do! 👍

**Comment by js-d-coder** [comment]
Another markdown application seems to do it very well :-)

**Comment by lainsce** [comment]
That’s because that app has GitHub Markdown support, which I don’t have here. I might go and try adding it here

**Comment by js-d-coder** [comment]
that would be great!

**Comment by lainsce** [comment]
Actually, after researching about this, it isn't a GitHub markdown thing, just some badly typed Markdown that GitHub tries to recover and display in their Markdown processor. The true way to do such images is to type them as: ```![Alternative Text](path/to/local_image_file.jpg "Title of Image")```, and without the `%26` code stuff, that's actually `&amp;` as in `&`.
