### ISSUE TITLE
Custom font is ignored is Focus Mode

### ISSUE THREAD

**Issue by apcamargo** [lainsce/quilter#102]
I'm using Fira Mono as a custom font in Quilter. In focus mode, my custom font choice is ignored.
![screenshot from 2017-11-14 11 22 20](https://user-images.githubusercontent.com/22940964/32782051-3ed86a52-c92e-11e7-89b2-0e42ad583a34.png)
![screenshot from 2017-11-14 11 22 32](https://user-images.githubusercontent.com/22940964/32782050-3e344b98-c92e-11e7-95c2-8c22f7865dd3.png)

**Comment by lainsce** [comment]
This is by design, in Focus Mode any customization and colors are removed for the ultimate focused environment, so, this isn't a bug, it's a feature. :+1:
