### ISSUE TITLE
bug with colour of text

### ISSUE THREAD

**Issue by js-d-coder** [lainsce/quilter#104]
## Hello! If you found an error in this app, follow this template:

* The text in list item after code gets bolder
* I am writing JavaScript notes, I make note of important things along with code. After JavaScript code the text that follows it gets bolder (as show in image below)
* version - 1.4.3

![screenshot from 2017-11-19 22-22-18](https://user-images.githubusercontent.com/23054879/32993041-95bce5d4-cd78-11e7-8912-60dc8793da21.png)

I think there is a bug? If not please point out what I am doing wrong...
Thanks!

**Comment by lainsce** [comment]
Nah, it's not a bug, when you type code in, use either \``` \``` (for code blocks) or \` \` for single line code. Quilter will then know that you're marking those lines as code.

**Comment by js-d-coder** [comment]
I did surround my code with ``` before and after. I don't get what you mean?

**Comment by lainsce** [comment]
Hm, never mind. Can you show me with a video, what is on the previous lines and next lines from the screenshot? Because to get bold text, you'd need \** \** surrounding the text. Like \*\*this\*\*.
