### ISSUE TITLE
Filter "Markdown files" doesn't show Quilter documents

### ISSUE THREAD

**Issue by o-alquimista** [lainsce/quilter#107]
When browsing files to open, the default and only additional filter "Markdown files" doesn't even show files created with Quilter. Switching to "All files" is the only way to see anything.

I named the file with .markdown extension (test.markdown) and without an extension (test), and in both cases it does not show through the Markdown filter.

First, with Markdown filter...
![captura de tela de 2017-12-03 14-56-52](https://user-images.githubusercontent.com/25424263/33527576-50b6e5da-d83a-11e7-8773-716abb68a869.png)

Then without filters, "All files"
![captura de tela de 2017-12-03 14-57-07](https://user-images.githubusercontent.com/25424263/33527577-514dc96e-d83a-11e7-95f4-83143b0e8bb0.png)

**Comment by lainsce** [comment]
Ah yes, because the markdown filter uses the standard `.md` extension instead of the old `.markdown` extension.

**Comment by JonnyCodewalker** [comment]
Markdown uses the extension .md. Or am i misunderstanding something here?
