### ISSUE TITLE
headerbar breaks on maximize

### ISSUE THREAD

**Issue by Philip-Scott** [lainsce/quilter#11]
![screenshot from 2017-06-06 15 17 34](https://user-images.githubusercontent.com/10786508/26850666-f241ecce-4acd-11e7-8dc1-53c42b4e3749.png)

**Comment by Philip-Scott** [comment]
![screenshot from 2017-06-06 15 17 11](https://user-images.githubusercontent.com/10786508/26850674-f8a5d2ec-4acd-11e7-82b5-0b3d1b015849.png)

**Comment by lainsce** [comment]
This is fixed on 1.0.2, wait for the release to land. :+1:
