### ISSUE TITLE
How to creatre a new line

### ISSUE THREAD

**Issue by J0Ar** [lainsce/quilter#111]
Maybe i'am doing something wrong, but how i can jump to a new line if i want to?

Thanks Joerg :)

**Comment by lainsce** [comment]
You mean creating a new paragraph? It's easy: double press the Enter key then start it.

**Comment by J0Ar** [comment]
I meant to create just a line break, no paragraph. But i think i just misunderstood the characteristic of such an editor...it must have automatic line break so the behavior must be like this. No problem and sorry.
