### ISSUE TITLE
comment in appdata.xml file breaks validation with libappstream-glib

### ISSUE THREAD

**Issue by decathorpe** [lainsce/quilter#114]
I am looking to compile (and maybe package) your application on fedora, it looks great! However, the appdata file you ship currently fails the mandatory validation with libappstream-glib (that's what gnome-software uses - in contrast to appstream(cli), which is used by elementary).

It seems GNOME's library is using an XML parser that's a bit brittle, as it sometimes crashes with parsing errors (as is the case here). So, would it be possible for you to remove the XML comment at the bottom of the appdata file?

**Comment by lainsce** [comment]
I can, and I will right now 🚗

**Comment by lainsce** [comment]
And it's done!

**Comment by decathorpe** [comment]
Thanks! :+1:
