### ISSUE TITLE
opening new file deletes unsaved open doc

### ISSUE THREAD

**Issue by asdasdasdadasdasd** [lainsce/quilter#118]
If I've started writing on an unsaved doc, and then open another doc, the original unsaved one disappears, replaced by the opened one. As far as I understand (which isn't much) the unsaved doc is now deleted.

It may be useful to prevent data loss, to trigger a save dialogue before replacing the unsaved doc with the opened doc.

Version 1.4.6

**Comment by lainsce** [comment]
The thing is, the saved doc should always save after a period of time, or when you change the opened file.  
What are the steps you made to trigger a deletion of data?

**Comment by lainsce** [comment]
Any updates on this bug, if not, I'll close it due to inactivity

**Comment by lainsce** [comment]
Closed due to inactivity.
