### ISSUE TITLE
Fullscreen mode does not work

### ISSUE THREAD

**Issue by TheSirC** [lainsce/quilter#119]
Hello !
Thank you for your wonderful amazing curated app ! I found a little bug on it : 
* Description : Whether it is with the button or smart corners, the application does not go into full screen mode ; the corners disappears but the application does not "scale" (n.b : it is possible to drag the sides to fit the screen)
* Version : 1.4.6
* [Video](https://send.firefox.com/download/7f820cd917/#SckhtXoJHdtOKnwKRfGwlA)

Thanks for your time & investment!

**Comment by lainsce** [comment]
This bug is not on Quilter side, and I don't know what the bug is targeted to, and also, is something that only few people actually have as a bug.  
For whatever reason, that I don't know nor my friend which is an elementary OS dev, yeah, the fullscreen doesn't work properly for only some people...  

Can you help me by saying what's your GPU & CPU? (as shown in the about section in System Settings.)

**Comment by TheSirC** [comment]
Sure !
Here is the dump of the `lshw` command : 
```
  produit: Intel(R) Pentium(R) CPU B950 @ 2.10GHz
          fabriquant: Intel Corp.
          identifiant matériel: 1
          information bus: cpu@0
          taille: 876MHz
          capacité: 2100MHz
          bits: 64 bits
```
```
*-display
             description: VGA compatible controller
             produit: 2nd Generation Core Processor Family Integrated Graphics Controller
             fabriquant: Intel Corporation
             identifiant matériel: 2
             information bus: pci@0000:00:02.0
             version: 09
             bits: 64 bits
             horloge: 33MHz
```

**Comment by TheSirC** [comment]
Let me know if you want to know something else !

**Comment by lainsce** [comment]
I think I know what's going wrong here. Your CPU &GPU might be blocking desktop effects from happening, and Gala (the window manager) doesn't know how to properly show fullscreen if the hardware doesn't let desktop effects show. This might be a Gala bug then.
