### ISSUE TITLE
Dark window title needed

### ISSUE THREAD

**Issue by meeb** [lainsce/quilter#12]
There's a minor graphical issue when maximising the window on a desktop with a dark app bar / panel. Quilter should detect the colour of the window title and changing the fonts / icons to be white when the window title is dark or not change its window to be dark at all (most other eOS applications seem to just ignore the app bar colour). See the attached image for details.

This may be fixed in more recent versions as I can see your commits from two days ago reference a new dark mode, but this is currently broken in the version released on the eOS AppCenter.

![quilter-black-header](https://user-images.githubusercontent.com/2459512/26857929-9f26cf6a-4b71-11e7-9815-22edbc9384ab.png)

Thanks for the decent writing app!

**Comment by lainsce** [comment]
This is fixed in 1.0.3 which just now released on AppCenter, enjoy!

**Comment by meeb** [comment]
Thanks for the quick update push. Can confirm it's resolved.
