### ISSUE TITLE
"Unsaved changes" dialog doesn't work as expected

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [lainsce/quilter#125]
When creating a new file while there are unsaved changes, a dialog appears with "Close without saving", "Cancel" and "Save" options. Expected behavior for "Cancel" is dismissal of the dialog, without any action being applied, but it seems to work identically to "Close without saving", i.e. it completely dismisses the changes made to the file.

Using version 1.5.2.

**Comment by phocean** [comment]
I lost data because of this bug.

**Comment by lainsce** [comment]
Fixed in master, about to release for review tomorrow.
