### ISSUE TITLE
js code can be executable in editor

### ISSUE THREAD

**Issue by flaminestone** [lainsce/quilter#126]
## Hello! If you found an error in this app, follow this template:
After write text:
`<script>alert()</script>`
window with empty string will open
* quilter version 1.5.2
![image](https://user-images.githubusercontent.com/6047261/36473138-bc8ac6d8-1704-11e8-8afe-39a635e5c1ff.png)

**Comment by lainsce** [comment]
It can be because all text in preview mode is treated as HTML. I will try to disable JS code from running.

**Comment by lainsce** [comment]
Fixed in master, about to release for review tomorrow.
