### ISSUE TITLE
Preview mode resets view to top of page every ~20 seconds

### ISSUE THREAD

**Issue by ajashton** [lainsce/quilter#127]
I'm running 1.5.2. If I go to preview mode and scroll down a bit, the page will jump back up to the top after 20 seconds or so. Also: at this point any `<details>` elements that I had expanded while reading are collapsed again.

**Comment by lainsce** [comment]
It's because Preview Mode is refreshing itself for any changes made in Edit Mode. I will try to fix this though.

**Comment by lainsce** [comment]
Fixed in master, about to release for review tomorrow.
