### ISSUE TITLE
[Enhancement] Implement code blocks  highlighting

### ISSUE THREAD

**Issue by phocean** [lainsce/quilter#130]
Currently, code is not highlighted.

Please implement it so that it can be used for editing technical documents.

**Comment by lainsce** [comment]
It is. You need to write the code block like this for example for Python:
```
```python
enter code here
```EOF
```

Without the EOF.

**Comment by phocean** [comment]
I know markdown syntax.

Yet, there is no highlighting neither in editing nor preview mode, so I don't understand why you are closing it.

**Comment by phocean** [comment]
To clarify:

In sublimetext:

![capture d ecran du 2018-03-06 16 52 49](https://user-images.githubusercontent.com/4280885/37042527-e7f375b8-215e-11e8-8a28-5c3c03c0eb6d.png)

in quilter:

![capture d ecran du 2018-03-06 16 53 13](https://user-images.githubusercontent.com/4280885/37042574-fcc68b4c-215e-11e8-87e5-be18a251103f.png)

**Comment by lainsce** [comment]
Are you in the last version? It shojld have syntax highlightning in Preview Mode

**Comment by phocean** [comment]
I am using the version from the ElementaryOS application center. Isn't the latest version supposed to be there?

**Comment by lainsce** [comment]
Yeah. So here's the thing: Syntax Highlighting for code blocks is only in the Preview Mode.

**Comment by phocean** [comment]
Ok, then... as you wish if you prefer to close it.

I still think it would be a nice enhancement (for readability when writing).

**Comment by lainsce** [comment]
I designed Edit Mode to be very spartan looking to not make it distracting. Preview Mode in turn, has all the confetti.
Anyhoo, if you're ok with me closing the issue, then, it's closed 😄
