### ISSUE TITLE
[Request] Auto-save feature

### ISSUE THREAD

**Issue by dmitryam** [lainsce/quilter#131]
Hi, I've written some text in quilter but didn't close the app or saved the file. Later I did a reboot and it appeared that all my writing got lost. That was not a terrible loss, but an unfortunate one. 

I believe the text is autosaved each time the application is closed the regular way, but it does not get saved automatically, which would be a good feature to save from power loss or anything similar.

**Comment by lainsce** [comment]
It does get saved. It takes every 20 seconds to autosave, as a measure to not speed up the damage on SSDs and Hard Disks.
