### ISSUE TITLE
Wrong terminology: “header” used in place of “heading”

### ISSUE THREAD

**Issue by fitojb** [lainsce/quilter#133]
The nested titles you can add to a document in Markdown are headings, not headers. A header is a piece of text that is placed at the top of the page; the counterpart of a footer.

![image](https://user-images.githubusercontent.com/554953/37560261-b31b3e1c-29fa-11e8-898c-2b9052ba7bc7.png)

This can be fixed by doing something like `git grep -l "# Header " | xargs sed -i "s/# Header /# Heading /g"`

**Comment by lainsce** [comment]
I've only seen H1~H6 being referred as Headers 1 thru 6 online...

**Comment by lainsce** [comment]
Fixed in master, about to release for review tomorrow.
