### ISSUE TITLE
Show the Markdown symbol structure somehow

### ISSUE THREAD

**Issue by visvital** [lainsce/quilter#138]
As a user, I want to be able to start my writing with the structure, so that I could plan and manage my text in a better way (see Ulysessesapp for example).

I want to be able to create a rearrange the chapters without the need to go inside the whole text and find the chapters. At the same time, I want to be able to see the whole text which I wrote in the document.

Thank you!

**Comment by lainsce** [comment]
I see, so you're requesting a sidebar with parts of the document laid out? I'll see what I can do. :smile:

**Comment by visvital** [comment]
Basically, yes. Also, this might be helpful to be able to see the list of documents I'm working on as well.
So that the structure looks like follows:
```
-Document name 1
------| Chapter 1
------| Chapter 2
------| Chapter 3
-Document name 2
------| Chapter 1
------| Chapter 2
------| Chapter 3
-etc.
```

Sometimes this becomes really helpful, especially, when you are a technical writer and need to be able to manage the structure of the document easily (or even move some parts of your writings to different documents as well). I believe the same applies to novel writers, because they need to control the ordering of episodes really often, as well as define the structure of the whole novel.

Thank you!

**Comment by lainsce** [comment]
I can do this with only the current document, but I'm working around this by having two tabs in the sidebar: Recents and Code. Recents would store the last 5 opened documents in Quilter

**Comment by lainsce** [comment]
Continues under issue #143
