### ISSUE TITLE
Allow tabs to be able to work with multiple documents

### ISSUE THREAD

**Issue by gnacho** [lainsce/quilter#139]
So far the best GTK editor I ever found. Thank you very much!!!

In case someday you decide to make a "not so simple" version, consider some mockups I did a few months ago to take some ideas: https://github.com/gnacho/Gnome-MD

I can help with Spanish translation too, let me know.

Thank you again!!

**Comment by lainsce** [comment]
Hey, thanks! :smile: 
Quilter actually isn't "so simple", it is just minimal and not in your way when writing texts. :smirk:

I'll see your mockups and get new ideas for the app though if they have nice simple things hidden there.  
And if your variant of Spanish isn't here yet, by all means translate the app away!  
Just follow the instructions by clicking in this repo's po folder.

**Comment by gnacho** [comment]
Sorry, by "simple" I meant minimal, referring to the UI.

One suggestion, launching more instances or allowing "tabs" (both options should be great) in order to be able to work in different documents at the same time.

**Comment by lainsce** [comment]
Would you be happy if instead of working with multiple docs, the sidebar stores the last 5 opened documents, like if it was a Recents view?

**Comment by lainsce** [comment]
Continues under the issue #143
