### ISSUE TITLE
[Request] Its possible to add tabs?

### ISSUE THREAD

**Issue by beeblebrox3** [lainsce/quilter#14]
Also, would be nice if it saves automatically the files on temp files when the app closes or new documents are open, like Scratch does.

Thanks!

**Comment by lainsce** [comment]
Quilter is for big files containing a story, not for multiple files competing for space and your focus. :thinking: 
One thing I'm working on is a sidebar where you can jump between chapters and sub-chapters of the story.

If you want a tabbed interface, stick with Scratch. :smiley:

**Comment by beeblebrox3** [comment]
Thanks!
