### ISSUE TITLE
Change Some Style and make quilter more uniform

### ISSUE THREAD

**Issue by surajmandalcell** [lainsce/quilter#146]
## Change Some Style

Can you guys add this for light mode (default)
```
.quilter-toolbar.titlebar{
  background-color: #FCFCFC;
}
```

And this for dark mode in your css?
```
.quilter-toolbar.titlebar{
  background-color: #232629;
}
```

**Before :** 
![quilter_before_white](https://user-images.githubusercontent.com/11650177/40694552-c43d6444-63da-11e8-8fd0-3a2c64bac11e.png)
**After :** 
![quilter_uniform](https://user-images.githubusercontent.com/11650177/40694567-d542fb32-63da-11e8-91f1-afda771a0869.png)

Before : 
![quilter_unified_before](https://user-images.githubusercontent.com/11650177/40694590-e5261afc-63da-11e8-9db3-db70074ba431.png)
After : 
![quilder_uniform_dark](https://user-images.githubusercontent.com/11650177/40694598-ec1bda0e-63da-11e8-888d-47de843e1b69.png)

**Comment by lainsce** [comment]
I don't feel making the headerbar's background the same as the content's background visually will change anything. Give me a solid argument and I might change my stance on this.

**Comment by surajmandalcell** [comment]
Saw this somewhere, looked cool, thought there was a chance it was possible in linux.
![nightg](https://user-images.githubusercontent.com/11650177/41016272-eed53b32-696b-11e8-951c-5f1e68736574.gif)

**Comment by lainsce** [comment]
@surajmandalcell It is possible, but Quilter just isn't a gimmicky widget, if you know what I mean. :stuck_out_tongue_winking_eye:

**Comment by surajmandalcell** [comment]
Aah, ill make my own then xD
Any helpful resources to learn vala from other than valadoc and countless hours of trial and error?

**Comment by surajmandalcell** [comment]
@lainsce btw my theme already does(change header-bar color) this, try it if you want to see it in practice. https://github.com/surajmandalcell/elementary-x

**Comment by lainsce** [comment]
@surajmandalcell I learnt Vala by reading up on other's code and also Valadoc

Since this is resolved, I'mma close this.
