### ISSUE TITLE
Question: Is it possible to compile this app for Windows?

### ISSUE THREAD

**Issue by vsalbuq** [lainsce/quilter#147]
I really like your app. It has every single feature I wanted for a note taking software.
I already use it at home, but I would like to use it at my job. Unfortunately, we use only Windows there.

Do any of you know if this would be possible? If you could just point me the direction, I'll try it by myself.

**Comment by lainsce** [comment]
I don't think there's a way to compile it in Windows, because this is an app coded in Vala, which isn't present in Windows, not even in WSL. Why not give elementary OS a spin in a VM for Quilter? :wink:
