### ISSUE TITLE
Word count on selection

### ISSUE THREAD

**Issue by eliocamp** [lainsce/quilter#149]
It would be great if the status bar showed the number of words in the current selection!

PS: I've been loving quilter, thanks!

**Comment by eliocamp** [comment]
I think counting words in selection is a pretty standard feature of a lot of composers so I don't think it would be weird. Of course, it should be clear what the count is for. Either by adding something like "Words (in selection): 348", or "Words: 123/348", or "348 words selected" (similar to Libre Office). only when there's a selection or maybe by displaying it as a whole different field.

**Comment by lainsce** [comment]
I don't see Quilter as a Word Processor, though, also, no other Markdown Text editor of the category Quilter is, does this.

**Comment by lainsce** [comment]
Going to close this because I feel that the Word Count as-is is enough information.
