### ISSUE TITLE
Ctrl+A is read as Ctrl+Q in other layouts

### ISSUE THREAD

**Issue by kameha** [lainsce/quilter#155]
Hello! 

When I use the application (in French) and I want to select all with ctrl+a shortcut, it closes the application. On French keyboards, the A is where the Q is on English keyboards, it may be the problem.
I use version 1.5.6 on Elementary OS.

Thanks!

**Comment by lainsce** [comment]
It shouldn't do that unless you're using the English keyboard layout... Weird.
Try setting the keyboard layout again(I know, it's a bummer to do it again), and try Ctrl+A again.

**Comment by lainsce** [comment]
Tested this with the French keyboard layout in the AZERTY layout, and indeed this doesn't happen with me.

**Comment by kameha** [comment]
It happens with me in ElementaryOS as in Ubuntu. Still don't know why if
it's not because of the keyboard layout.

**Comment by lainsce** [comment]
I'll investigate further, as this might be a thing that spans all my apps if so.

**Comment by lainsce** [comment]
Yeah, no, this doesn't happen in any of my apps. Did you by accident enable some weird keyboard feature?

**Comment by kameha** [comment]
I use "French alternative" layout.

**Comment by lainsce** [comment]
But what I use is the internal Gtk name for the Ctrl+Q combo.

**Comment by kameha** [comment]
Well, the ElementaryOS is a fresh install and I did nothing about gtk or
any keyboard stuff. Maybe should I mention I use it on a laptop (acer v
nitro if it matters).
I'm really sorry I can't help you for this problem. I'll try to set other
keyboard layouts to see if the problem is still here, and I'll tell you if
this affect the problem in any way.

**Comment by lainsce** [comment]
Don't feel sorry if things are just wacky. It could be written differently too.

**Comment by lainsce** [comment]
After extensive testing, with the French (Alternative) layout, I saw that it also blocks Ctrl-Z (Undo) because it thinks it's Ctrl-W instead. I'd advise not using this layout since it'll break many apps.
