### ISSUE TITLE
Search Option

### ISSUE THREAD

**Issue by btd1337** [lainsce/quilter#158]
Please, add a search option to find words in document.

Note: If possible using shortcut ctrl + f

**Comment by lainsce** [comment]
I'll see what I can do.

**Comment by lainsce** [comment]
It's done in master.

**Comment by btd1337** [comment]
@lainsce Good.

I would like to make only one suggestion:

**Pikaur** doesn't meet the basic requirements of an AUR Helper, look at this list:

https://wiki.archlinux.org/index.php/AUR_helpers

**aurman** and trizen are the two most widely used and complete AUR Helpers of the Arch ecosystem.

Consider making a change.

**Comment by lainsce** [comment]
Eh, Arch users will use whichever AUR helper they know best. I'm not going to force one on them.
