### ISSUE TITLE
Please allow fullscreen options.

### ISSUE THREAD

**Issue by CallieG** [lainsce/quilter#17]
So, I am loving this so far, but if it is supposed to be useful for distraction free writing, having the ability to go fullscreen would be ideal.

So far, on Loki 0.4.1, I am unable to do so.

Is this a bug, or just a missing feature?

**Comment by lainsce** [comment]
It's actually there, just press F11 and you'll enable/disable it! :smiley:

**Comment by CallieG** [comment]
Just tried that, and all it does for me is to hide all of the interface, without taking up all of the screen.

I ran it with --debug to see if I could be helpful in this.



Application.vala:153: Quilter version: 1.0.4
[INFO 14:14:06.734963] Application.vala:155: Kernel version: 4.4.0-79-generic
[WARNING 14:14:06.789327] [Gtk] Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name
[WARNING 14:14:06.789434] [Gtk] Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name
[WARNING 14:14:06.789549] [Gtk] Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
[DEBUG 14:14:06.832965] [Gtk] Connecting to session manager
[DEBUG 14:14:06.842073] Settings.vala:163: Loading settings from schema 'com.github.lainsce.quilter'
[DEBUG 14:14:55.410270] Toolbar.vala:85: Prefs button pressed.
[INFO 14:14:55.452020] [Gtk] GtkDialog mapped without a transient parent. This is discouraged.


Also attached is a screen shot.

Thanks for responding so quickly.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by lainsce** [comment]
I dunno how this bug is affecting many users as I don't know the source of it, as it doesn't affect my app, just the window manager is confused about it.
Thanks for the --debug though, good to always share it with devs.

I'd file a bug at elementary/gala though, maybe it'll help with this bug.

**Comment by CallieG** [comment]
OKay.  Thank you.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
