### ISSUE TITLE
Headings shouldn't center

### ISSUE THREAD

**Issue by micahilbery** [lainsce/quilter#173]
Headings probably shouldn't center or if they have to center they should do so with the page and not the paragraphs.

![centering](https://user-images.githubusercontent.com/4886639/45710210-5c9d5400-bb5c-11e8-9f82-d3c8bb058d40.png)

version: 1.6.3

**Comment by lainsce** [comment]
I'll find a way to make paragraphs span the total width and not look this weird, that way this bug will be fixed.

**Comment by lainsce** [comment]
Fixed in 1.6.6
