### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by micahilbery** [lainsce/quilter#174]
It would be nice to be able to choose a custom fonts especially for the editor mode. This would be useful for people who have disabilities like dyslexia so they could choose a font that would be easier for them to read or just for those who like a particular font.

**Comment by lainsce** [comment]
I actively "fought" against this choice since I think setting custom fonts adds leeway for a ton of "I've setup a font to be 2px and now I can't read" issues. I think Quilt Mono is the best default I can do, since it has small letter quirks that avoid dyslexia problems..

**Comment by Addvilz** [comment]
I'd also love to see a way to select from at least system fonts. I use IBM Plex for writing, and hypothetical issues do not seem like a justification enough to not have this feature. I'd love to replace Atom I use now with Quilter but this is not something I can do without being able to do very basic customization such as changing editor and display fonts.

**Comment by lainsce** [comment]
Since then I've added Quilt Vier and now on next version, Quilt Zwei, both based upon Plex (because it's open-source) but customized for Quilter.

Both seem like good fonts to use.
