### ISSUE TITLE
[Feature Request] Change font size for editor

### ISSUE THREAD

**Issue by BNolet** [lainsce/quilter#177]
I'd like to be able to make the font size for the editor bigger. It would help with visibility for me

**Comment by lainsce** [comment]
It has a "Large" font setting. Is it not enough for you?

**Comment by BNolet** [comment]
There's no font size setting, only margins and spacing :S

![image](https://user-images.githubusercontent.com/10198484/46387543-1f28e280-c695-11e8-8323-ef48764ff6b0.png)

**Comment by lainsce** [comment]
Oh, then you're using the Loki release. I can't do much for it, you'll have to wait for Juno, since the app updated a lot.

**Comment by BNolet** [comment]
Oh, alright, my apologies!
