### ISSUE TITLE
Tried to open .odt file and got it corrupted.

### ISSUE THREAD

**Issue by RLFontan** [lainsce/quilter#178]
Hello!

- I just tried to open a .odt file i have wrote on Focus Writter and it got corrupted! The worst part of it is that i got desperate and tried to open it with "Code" and the "Ebook viewer" and i completly lost my file, its a blank document now.
- Version 1.6.6
- It's a complicated thing, because Quilter can attract users from Focus Reader like me, and Focus Reader can deal with these stuff.

Thanks!

**Comment by lainsce** [comment]
Quilter can only open Markdown files... I'm so sorry!
