### ISSUE TITLE
Code block and Italic style when shouldn't

### ISSUE THREAD

**Issue by megatux** [lainsce/quilter#185]
I'm using "```" for _code block_ but still interpreted the _text_ as **italic** : 

![captura realizada el 2018-10-24 10 36 39](https://user-images.githubusercontent.com/850020/47434380-d2f32e80-d778-11e8-9fd3-1fbc0b112a5b.png)

**Comment by lainsce** [comment]
It's just visual, it won't affect the preview nor your file. :)
