### ISSUE TITLE
Nested lists renders as single level list

### ISSUE THREAD

**Issue by zeebok** [lainsce/quilter#187]
After updating to Juno, Quilter does not render nested lists. It places all bullets on the same level.
What is expected:
- Bullet
- Another
    - Nested Detail

What I see:
- Bullet
- Another
- Nested Detail

**Comment by lainsce** [comment]
Haven't changed the backend for rendering the preview, so something's definitely up. I'll check it and fix.

**Comment by btd1337** [comment]
This problem persists.

It didn't work with tab or spaces.

The live code works corretly on [dilinger](https://dillinger.io/) but in Quilter don't.

**Comment by lainsce** [comment]
Yeah, something definitely is acting up.

I'll take a look at it when Ican, still fixing more important bugs for Quilter that are more complex. Sorry~

**Comment by lainsce** [comment]
Fixed this!
