### ISSUE TITLE
$$...$$ doesn't make latex math equations

### ISSUE THREAD

**Issue by emiellr** [lainsce/quilter#189]
&&...&& or &...& doesn't create a LaTex markdown.
No matter what I try it doesn't create LaTex markup.
[Issue in action](https://i.imgur.com/Sx7klGg.png)

**Comment by lainsce** [comment]
Fixed!

**Comment by lainsce** [comment]
It's now `\( ... \)` for single line LaTeX and `\[ ... \]` for multiple line LaTeX. I'll update the cheatsheet soon.
