### ISSUE TITLE
Recover a file

### ISSUE THREAD

**Issue by K-Eo** [lainsce/quilter#19]
Is there any way to recover a file?

I don't know if is a bug or something else but I was writing a file, I switched to another file in the same instance and then I went back to the initial file and surprise, all my text did gone.

**Comment by lainsce** [comment]
I'm going to add a dialog to the user to save the document before opening a new file! :+1: 
(Thanks for filing the bug as I didn't even catch that I forgot to add a save before opening dialog!)

**Comment by K-Eo** [comment]
It works fine now. Saddly I lost my file :cry: but thanks anyway for the quick answer.

**Comment by lainsce** [comment]
Aw, maybe it was a blessing in disguise to perfect it? :smiley:

Closing the issue.
