### ISSUE TITLE
File Management Issues (Save/Open/etc.)

### ISSUE THREAD

**Issue by knorquist** [lainsce/quilter#190]
I wrote up a document last night and powered down. This morning I pulled it up and the entire document was there, but when I opened a new document and then switched back to the old one I lost about half the document. Pretty weird, but luckily it was just some non-critical notes. For now I have git running on everything, just in case.

**Comment by lainsce** [comment]
There's going to be a massive backend rewrite happening this month or the next, fixing these issues. Look forward to it! :smile:

**Comment by knorquist** [comment]
Sounds good, thank you!

**Comment by aljelly** [comment]
Saving related things from the other issues:

---

### After saving a file with "Save as...", open it as the current file, show it in the sidebar and select it

At the moment when you save a file with "Save as..." it's not clear what file is open in the editor or what file you'll save to next. Is it the file selected in the sidebar or the one that you just saved to (which doesn't show up in the sidebar after)? Opening the file, adding the file to the sidebar and selecting it would make it more clear it's the one that you just saved to.

---

### Save/backup unsaved documents

Save or backup unsaved documents in somewhere like `~/.local/share/com.github.lainsce.quilter/unsaved/` if the user makes a new file but then closes Quilter. Then reopen the file on next startup. This is what Code does. Currently Quilter writes to the previously opened file but this is a known bug at #190.

(Though Code seems to fail to open the unsaved file(s) when launching the next time. Additionally don't do as Code currently sometimes does and delete the file after directly opening the unsaved file and then closing it.)

**Comment by SubhadeepJasu** [comment]
Basically Quilter should close the file and create a new one automatically when new button is clicked.

**Comment by janxkoci** [comment]
Yeah today I noticed that when I made new files in Quilter (with the plus icon), they  were actually overwriting the first file I opened - luckily I had it in Dropbox, so I could restore the original version (one month old). But I was lucky, this shouldn't happen at all :)

**Comment by thorbian** [comment]
I just lost 1000 words of writing from this bug. This app should not be up in the appstore as long as this bug exists, or at least come with a huge warning

**Comment by thorbian** [comment]
> I just lost 1000 words of writing from this bug. This app should not be up in the appstore as long as this bug exists, or at least come with a huge warning

And then I learned the use of versioning and restoring in Dropbox. But seriously you should make a warning or something

**Comment by nevillepark** [comment]
This also happened to me—lost some writing after opening a new document, and text I pasted into a new document overwrote the last saved one. 

I don't think this app is stable enough to be in the elementary App Centre at the moment.

**Comment by janxkoci** [comment]
As a workaround, instead of starting a new document, I now create new empty file with .md extension and then open it in Quilter (I noticed Quilter is not actually in the list of apps to open this file, so I open it in text editor, type something, save it and then Quilter becomes default app. Somehow Quilter cannot be associated with empty .md, maybe I should also report that?).

**Comment by icyJoseph** [comment]
Is it possible to recover a lost file somehow?

**Comment by janxkoci** [comment]
If you don't use something like Dropbox or git, it's gonna be hard - I succesfully* used opensource program [PhotoRec](https://www.cgsecurity.org/wiki/PhotoRec) in the past to recover data from crashed SSD.

* in my case my filesystem "melted" so I could recover files but with random generic names (but correct extensions). In your case you would probably get the file back just fine.

**Comment by lainsce** [comment]
**Quilter is in Maintenance Mode since October 2018**

I am in the process of rewriting the whole app to fix all File management issues and more.
As such, this app is frozen in time until I rewrite it completely.

**Comment by lainsce** [comment]
Please check out PR #214 to see what still needs to be done by me then this bug is blasted finally.

**Comment by lainsce** [comment]
FINALLY IT IS FIXED!

**Comment by SubhadeepJasu** [comment]
ok
