### ISSUE TITLE
Export to pdf: generated document follows on-screen theme

### ISSUE THREAD

**Issue by elvisd** [lainsce/quilter#191]
I.ex.: I use the dark variant, write the document and export to PDF.
The resulting pdf uses the on-screen theme variant.

See attached screenshot.

IMHO the exported pdf should always use a fixed style (for me the black on white)

Using version 1.6.8
![screenshot from 2018-11-08 17 17 23](https://user-images.githubusercontent.com/307127/48211644-33d65580-e37a-11e8-8738-6691334b23d6.png)

**Comment by lainsce** [comment]
Will fix it when I have free time, which might be in December..

**Comment by lainsce** [comment]
Working on this now.

**Comment by lainsce** [comment]
Fixed in master.
