### ISSUE TITLE
Create new document and auto-save problem (document lost)

### ISSUE THREAD

**Issue by elvisd** [lainsce/quilter#192]
Enable auto save document
Start to write a document.
Save as... and save it to disk.
Click on new document
The new empty document overwrites the previous saved document!
![screencast from 2018-11-08 17 34 10](https://user-images.githubusercontent.com/307127/48212910-e4455900-e37c-11e8-9b01-8f12022ed077.gif)

**Comment by knorquist** [comment]
I ran into this enough times that I am VERY careful about saving stuff now. I have git enabled as a way to manage lost or overwritten stuff. Not really a fix I know but a bandaid until this gets worked out.

**Comment by lainsce** [comment]
Duplicate of #190, track this bug over there... :+1:
