### ISSUE TITLE
Allow a custom hotkey switch (Add a more notebook-friendly hotkey switch)

### ISSUE THREAD

**Issue by eljefuri** [lainsce/quilter#194]
Issue #78 helpfully added a hotkey switch, but unfortunately the key chosen is one that requires holding the Fn (Function) key. Many laptops have media keys on by default so this is a bit awkward, not to mention the required stretch of the hand to pull it off. I would greatly appreciate a Preferences option to be able to change this switch hotkey to any key combination that I want.

**Comment by lainsce** [comment]
Which combination of key do you think makes sense as an alternative?

**Comment by lainsce** [comment]
Awaiting answer before I can do anything...

**Comment by lainsce** [comment]
Would Ctrl + 1 work? Esc is commonly used by the system.

**Comment by lainsce** [comment]
Fixed in master, await release.

**Comment by janxkoci** [comment]
F1 in most programs is used for getting help. Some better default options could be:

Ctrl+Tab is commonly used by browsers and other apps to swich between tabs / documents.

Some markdown apps, in particular Jupyter Notebook, use Enter to switch to edit mode (if you are in edit mode, it will insert a newline as expected) and Esc to exit edit mode, switching to preview mode.
