### ISSUE TITLE
After saving a file with "Save as...", open it as the current file, show it in the sidebar and select it

### ISSUE THREAD

**Issue by aljelly** [lainsce/quilter#196]
At the moment when you save a file with "Save as..." it's not clear what file is open in the editor or what file you'll save to next. Is it the file selected in the sidebar or the one that you just saved to (which doesn't show up in the sidebar after)? Opening the file, adding the file to the sidebar and selecting it would make it more clear it's the one that you just saved to.

Quilter 1.6.8 from AppCenter.

**Comment by lainsce** [comment]
Please add this as a comment on #190, since all saving/opening/etc related issues are there.
