### ISSUE TITLE
Reduce vertical margin on "small" margin size

### ISSUE THREAD

**Issue by aljelly** [lainsce/quilter#197]
Screenshot:
![screenshot from 2018-11-21 10-47-50](https://user-images.githubusercontent.com/10395308/48836562-024a8a80-ed7b-11e8-9fb1-09d7f8ccfcdd.png)

On the small margin setting the vertical margin doesn't change and so it's a bit too much. Could it be reduced on the smaller setting so it's even with the horizontal margin?

In other words (if the GTK inspector is telling me the right thing) make `top-margin` and `bottom-margin` `16` like the left/right margin on the small margin setting (instead it stays on `40`).

Version 1.6.8.

**Comment by lainsce** [comment]
Vertical margin doesn't change, and shouldn't change. Only the horizontal margins change, due to the design mirroring Preview mode in geometry.

**Comment by aljelly** [comment]
I just think it looks strange and sticking out when the horizontal margin size is set to small and the vertical margin ceases to be "square" or "even" with the horizontal margin, for lack of a better way to describe it.
