### ISSUE TITLE
A dark mode but in a similar vein to Sepia

### ISSUE THREAD

**Issue by aljelly** [lainsce/quilter#198]
I like the Sepia theme because it's easier on the eyes, a bit like how Solarized Light/Dark is supposed to be. It might be nice to have (or someone else might want) a dark version in a similar vein to that. Maybe call it "Moon(light) Mode" or something.

Maybe base it on something like elementary's Slate 700 colour (and text colour something like Slate 300/100 or Silver 500/700)? They may not look right though, those are just guesses.

**Comment by lainsce** [comment]
I'll work on this soon

**Comment by lainsce** [comment]
Done, enjoy the Moon colorscheme on master. When all bugs are squashed it'll be on AppCenter.
