### ISSUE TITLE
Save/backup unsaved documents

### ISSUE THREAD

**Issue by aljelly** [lainsce/quilter#199]
(hopefully I'm not overwhelming you with issues)

Save or backup unsaved documents in somewhere like `~/.local/share/com.github.lainsce.quilter/unsaved/` if the user makes a new file but then closes Quilter. Then reopen the file on next startup. This is what Code does. Currently Quilter writes to the previously opened file but this is a known bug at #190.

(Though Code seems to fail to open the unsaved file(s) when launching the next time. Additionally don't do as Code currently does and delete the file after directly opening the unsaved file and then closing it.)

1.6.8

**Comment by lainsce** [comment]
Please add this as a comment on #190, since all saving/opening/etc related issues are there.
