### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by JamesTiberiusKirk** [lainsce/quilter#20]
I know this is by design, however, we need to have the ability to resize the text. For example, I am on a 720p display and text just is way too big. 
Please add the ability to do that back in! I really like quilter and other than that negative, it is perfect for me! I would definitely like to keep using it.

**Comment by lainsce** [comment]
Think about it like this: the text being bigger as it is right now, makes focusing better.
There's a psychological effect in play here, that humans pay more attention to bigger text than normal text.

**Comment by JamesTiberiusKirk** [comment]
True, however, I still need to option to make the text be smaller. I am almost feeling claustrophobic when using this application side by side with something like a pdf doc. I simply need to be able to make it smaller.

Why did you remove that option anyway, why not just set the default to a bigger text?

**Comment by lainsce** [comment]
If you don't need the Focus Mode which is where the text is big, then disable it? 🤔

**Comment by JamesTiberiusKirk** [comment]
I did, the text is still too big.
So why did you remove it in the first place?

**Comment by JamesTiberiusKirk** [comment]
Right, so why did you remove that?
Sorry, I'm not trying to be annoying, just genuinely curious.

**Comment by lainsce** [comment]
Because it clashed with the idea of the app.
If I let it be, I'd have bugs saying "Wah! Font XYZ is too hard to read! Why is *THAT* an option!?"

**Comment by JamesTiberiusKirk** [comment]
Well, why is "sudo rf -rf /" and option? (I know that might be blocked on modern day Linux, just trying to prove a point)
Because the whole point of Linux is that is free (as in freedom).
I am not saying that you should just start adding all of the features, but at least have the basic ones please. 
The removal of this feature alone might possibly make me switch to something else.
And to those people just say "stick to the defaults".

Remember, you are dealing with a Linux community, not Windows or Mac.

**Comment by lainsce** [comment]
I'll see what I can do, and you can expect magic coming your way in the next release!

**Comment by JamesTiberiusKirk** [comment]
Thanks a lot! :D
Will be impatiently waiting :) !
