### ISSUE TITLE
Tracking always resets to "Characters"

### ISSUE THREAD

**Issue by welaq** [lainsce/quilter#202]
Quilter 1.6.8:
 Tracking at the status bar always resets to Characters. See gif.
![quilter1](https://user-images.githubusercontent.com/28876465/48946917-f8ba5180-ef37-11e8-813e-d9c8d6ebe4ee.gif)

**Comment by lainsce** [comment]
Oh, it's 1.68, the version on AppCenter. I've long fixed this in master. Await the release when its done for the fix. Sorry for the delay. :disappointed:
