### ISSUE TITLE
In some cases you have to click twice to turn "Focus Mode" off

### ISSUE THREAD

**Issue by welaq** [lainsce/quilter#203]
Quilter 1.6.8:
In some cases (if you enabled Focus mode in Preferences) you have to click twice on "Focus Mode" to turn it off. See gif.
![quilter2](https://user-images.githubusercontent.com/28876465/48947003-4f279000-ef38-11e8-99e8-b2006cd9f140.gif)

**Comment by lainsce** [comment]
After thinking more about this, I think this is the intended behavior when you realize the toggle in the preferences is like a permanent setting, and the one in the menu is a temporary one. It's not a bug.
