### ISSUE TITLE
Latex

### ISSUE THREAD

**Issue by zcanter** [lainsce/quilter#206]
Hello, I am unable to render latex. I cannot tell if this is a bug or a problem on my end. 

![screenshot from 2018-12-13 23 53 53](https://user-images.githubusercontent.com/5613001/49990408-64d61700-ff32-11e8-869f-c276ce490d70.png)

**Comment by lainsce** [comment]
Are you on the AppCenter version, or the one in this repository? AppCenter version has a bug which it doesn't display LaTeX.

**Comment by lainsce** [comment]
As such, this bug doesn't exist anymore, but I'm waiting on other bugs being solved to release a new version

**Comment by zcanter** [comment]
Hey, thanks for getting back to me so quickly. Yes it is from the appcenter. I will download Quilter direct from the repo. Great app and vision though! Thanks again.
