### ISSUE TITLE
Custom preview styling

### ISSUE THREAD

**Issue by harisvsulaiman** [lainsce/quilter#207]
I think that the preview should be themable with custom fonts Colors etc.
Since this preview is rendered in a webview AFAIK, it should be easy to load custom CSS file to it.

This repository could host css stylesheets and the app could downloaded them on demand.

This would be an interesting feature,which could encourage more diverse ecosystem of themes.

I would like to know your thoughts on this, @lainsce

**Comment by lainsce** [comment]
The use of custom themes would be extra work to make work, since the whole app would need to adapt to the new theme as well in the edit view and app ui. The current 4 themes were carefully made to be the best in aiding focus for writers.
