### ISSUE TITLE
Add an option to save indent

### ISSUE THREAD

**Issue by JustMeErazem** [lainsce/quilter#208]
When indenting twice on larger bullet lists eg.

* Option one:
  * Suboption one
  * Suboption two

you have to press tab every time to get the indent you want.
Please add an option to automatically indent, elementaryOS's Code might give you an idea on how to do that.

Thanks :)

**Comment by lainsce** [comment]
I'll see how to do it. I'm however focusing all on #190 at the moment, so it might take a while.

**Comment by lainsce** [comment]
**Quilter is in Maintenance Mode since October 2018**

I am in the process of rewriting the whole app to fix all File management issues and more.
As such, this app is frozen in time until I rewrite it completely.

**Comment by lainsce** [comment]
Fixed.
