### ISSUE TITLE
Lovely app, here are a few UI issues

### ISSUE THREAD

**Issue by scottjenson** [lainsce/quilter#212]
Sorry if this isn't a classic bug report but I thought it would be helpful to give you UX feedback. I can make these separate issues if you like but I'm not sure you're interested in this type of feedback

The New button acts like an erase button
It's confusing that when I hit new, everything I type disappears. I assume I need to save the typed text? If so, could there be a prompt to save the file before throwing it away?

I can save a file that can't be opened
I did eventually find the save button and just typed 'notes' but then I wasn't able to find the file from the OPEN command (as it appears to be looking for '.md' files) This is a known pattern with a simple fix. If there is not suffix to the file, just append .md

The side bar is confusing
Not really sure how the side bar works but I expected "new" would crate a new entry, but it doesn't. As I learned to save .md files and open them, I ended up with 3 of the same file. I really don't know what is happening.

I can't change the edit font
I just want a simple note editor, MD is nice but not my main focus. I just want a focused writing experience. It would be nice to be able to choose a font and size for the writing.

**Comment by lainsce** [comment]
**Quilter is in Maintenance Mode since October 2018**

I am in the process of rewriting the whole app to fix all File management issues and more.  
As such, this app is frozen in time until I rewrite it completely.

**Comment by lainsce** [comment]
> The New button acts like an erase button

Going to be fixed in the Rewrite®

> I can save a file that can't be opened

Going to be fixed in the Rewrite®

> The side bar is confusing

Going to be fixed in the Rewrite®

> I can't change the edit font

Quilter is designed to be used with the provided font and sizes, I will not change this.

**Comment by lainsce** [comment]
Closing this since most of the issue reflects #190.
