### ISSUE TITLE
Inline HTML not parsed in Preview mode

### ISSUE THREAD

**Issue by rgb-one** [lainsce/quilter#213]
When previewing a markdown file with inline HTML, the inline HTML gets treated like paragraph text. Instead it should be recognized and rendered as HTML.

![screenshot from 2019-02-19 00-48-36](https://user-images.githubusercontent.com/5672238/52993451-3d904000-33e2-11e9-81f6-837714e9689b.png)

Quilter version 1.6.8

Heres a link to the markdown file in the image:
https://raw.githubusercontent.com/laravel/framework/5.7/README.md

**Comment by lainsce** [comment]
**Quilter is in Maintenance Mode since October 2018**

I am in the process of rewriting the whole app to fix all File management issues and more.
As such, this app is frozen in time until I rewrite it completely.

**Comment by lainsce** [comment]
Fixed.

**Comment by rgb-one** [comment]
Cool :+1:
