### ISSUE TITLE
Button "Clear files from sidebar" clearing all inputed data

### ISSUE THREAD

**Issue by flaminestone** [lainsce/quilter#216]
Hello. I found this problem:

* Open Quilter, and add text to text area
* Open sidebar
* Click to "Clear files from sidebar" button

After that, all inputed data will be deleted, but this button must to close only opened files (with saveing all changes), and ask about saving current data to file (like after creating new file)

![gifout](https://user-images.githubusercontent.com/6047261/53166245-d6db7400-35e5-11e9-8c50-fcac31d6d377.gif)

May be, show ...ginhub.lainsce.quilter/temp.md by default in sidebar is a good idea? And show it in header 
![image](https://user-images.githubusercontent.com/6047261/53166132-8b28ca80-35e5-11e9-9908-a34ea8f9bf56.png)

Version 1.7.0

Thanks!

**Comment by lainsce** [comment]
That button is for when you want a real clean app without files nor content.
I should add in a dialog to confirm if you want to clear everything.

**Comment by lainsce** [comment]
Fixed in master, release next week.
