### ISSUE TITLE
Writing to phantom document after closing all documents

### ISSUE THREAD

**Issue by flaminestone** [lainsce/quilter#222]
## Hello! I found strange behaviors, and I think it's wrong:

* Open Quilter
* Close "New Document"
* Write to text area.

There are no opened documents, but writing is enabled. 
Left sidebar is empty. 

![gifout](https://user-images.githubusercontent.com/6047261/53341425-939e3f80-391c-11e9-842b-7dd483987d6e.gif)

### Correct behaviors:
Left sidebar can't be empty if writing is enabled.  
If I close all files, and try to write to text area, temp.md file will be added to sidebar.
Path to temp.md file will show under header after file is added to sidebar (now, path to edited file can be updated only after show/hide sidebar)

Version: 1.7.3
Thanks!

**Comment by lainsce** [comment]
Fixed in master, please await new release
