### ISSUE TITLE
Close without saving not closing current file

### ISSUE THREAD

**Issue by flaminestone** [lainsce/quilter#223]
* Open Quilter
* Click "New file"
* Click "Close without saving"

After that, new file will added to sidebar, but old file will not close

![gifout](https://user-images.githubusercontent.com/6047261/53341807-951c3780-391d-11e9-81da-ec8e58432de9.gif)

May be, don't need to close current file after click "New file". Can you only add new file to ".local/share/com.github.lainsce.quilter" after click "New file"?

Version 1.7.3
Thanks!

**Comment by lainsce** [comment]
Fixed in master, please await a release.
