### ISSUE TITLE
Enhancement: New file naming scheme

### ISSUE THREAD

**Issue by flaminestone** [lainsce/quilter#224]
At now, all new files is named "temp.md"...
 
I see 2 variants for optimizations:

# First way:

-  Open Quilter and write some text. It will be saved to `~/.local/share/com.github.lainsce.quilter/temp.md` automatically.
- Click to "New file" and write to it other data. It will be saved to `~/.local/share/com.github.lainsce.quilter/temp1.md` automatically.

# Second way: 
But the best way for save, I think, is a take first 40 characters from the first `#` header
![image](https://user-images.githubusercontent.com/6047261/53343450-75870e00-3921-11e9-8e43-934d83a4c041.png)
- I create new file, and write to it something like it: `# Come ideas for good Quilter looking`
- Will be nice to see the file with name `Come_ideas_for_good_Quilter_looking.md` when saved.

@ Version 1.7.3
Thanks!

**Comment by lainsce** [comment]
I'll see what I can do.

**Comment by janxkoci** [comment]
Just a note - the second version is used in another elementary app (PS Notes I think) but it's not very well done. Whenever I made a new note it took first line as both header and filename, however when I type it, it creates bunch of files with partial name as I type and then throws them in the trash as I type more. Not very elegant, so try to avoid that maybe.

**Comment by lainsce** [comment]
I'll take into consideration that it won't save with the header as name unless the user says so, so it'll be "New File" until the user hits Ctrl+S or somesuch.

**Comment by lainsce** [comment]
After much testing, I couldn't do this justice. Sorry, but it'll have to be named `temp.md`.
