### ISSUE TITLE
No file appear in sidebar

### ISSUE THREAD

**Issue by tnntwister** [lainsce/quilter#227]
v1.7.4 

I closed the current files already open at the first launch, and now, when i open a file, nothing comes in the side bar, it's empty.

----------------------
enhancement talk : 

I tried to open a directory, without success. This feature is what i could adopt and give money for, Code didn't have a markdown preview, but manages directory browsing in the sidebar, and Notes Up don't allow to play with real files. 
Ulysses for Mac manages the two worlds (database like Notes Up and file management like Code) smoothly. Quilter could be an Ulysses alternative with tree of files management in the sidebar (like Code). Thanks for the work anyway !!

**Comment by lainsce** [comment]
I'll have a look.

**Comment by lainsce** [comment]
Fixed.
