### ISSUE TITLE
Doesn't stay synced with file

### ISSUE THREAD

**Issue by cassidyjames** [lainsce/quilter#23]
If I open a file, it looks like it is just one-time loading the contents into the window, saving that state internally, then never re-loading or re-saving the file on disk. This is problematic.

1. I start writing in Quilter, save the file, continue writing, then try to share that file with someone. It's a very old version (hasn't been updated from Quilter's internal state).
2. I open an _existing_ Markdown file in Quilter, make several changes, then close it. Those changes are not saved to the file, but there's no way to tell that from in Quilter.
3. I open a file in Quilter, make some changes from another program (or something like a Dropbox Sync), and those changes are never reflected in Quilter (even when those changes occur when Quilter is closed).

**Comment by cassidyjames** [comment]
Instead, I think looking into the way [Scratch](https://github.com/elementary/scratch) handles file management might be helpful.

**Comment by lainsce** [comment]
I've been reading up on the Scratch file handling, and found out that it's heavily dependent on Granite.Notebook tabs to specify which file(s) to sync internally.
I'd need to find a way to decouple the logic from that.

**Comment by lainsce** [comment]
After explanations on Slack I know what to do for this bug.
