### ISSUE TITLE
Quilter (still) overwrites my files

### ISSUE THREAD

**Issue by janxkoci** [lainsce/quilter#230]
Hi,

I updated Quilter yesterday, today I opened one file (using Files), then closed Quilter. Later I opened second file (using Files again), but the content of the first file appeared instead (as it was the last file opened in Quilter). I had to go to dropbox versioning again to restore the file.

I really consider switching to some other editor (like UberWriter from flathub), as this is really not the kind of thing I want to worry about constantly.

Please consider NOT asking $10 for your app if it still has problems like this.

Wish you best of luck.

**Comment by lainsce** [comment]
It shouldn't do that. I'll investigate this problem further.

**Comment by lainsce** [comment]
I've investigated and tested Quilter against all use cases (2 files, open one then another, open 10 files, open 5 files then another, etc. You get the idea.) and I've not even found a single opening bug like you describe on version 1.7.5; so if your version is out of date, please update and report if the bug persists.

**Comment by lainsce** [comment]
I've found the bug. Fixed and soon released as version 1.7.6
