### ISSUE TITLE
Simplify file management [wishlist]

### ISSUE THREAD

**Issue by janxkoci** [lainsce/quilter#231]
Hi @lainsce,

I really enjoy your app, but there are still some issues, that I would like to see solved, before I can comfortably enjoy your app again.

This is a design suggestion, that could help with your file management problems.

First of all, in the AppCentre description, you claim

> Work on a story, one file at a time.

So maybe it would work better if you really _enforce_ your "one file at a time" (that's what we expect from the description anyway):

- Have just **one temp file** (so don't worry about naming it, you will always have at most one, just go with temp.md in your prefered location), until it is explicitly saved.
- Saved files would always load from their location.
- Opening second file would first close the previously opened file. 
  - In case autosave is enabled just save it, otherwise ask if it was modified.
  - Make sure you don't save the first file into location of second or vice versa. I mean, *really make sure*. Probably best would be to *always* close file first _before_ you open next file. Even temporary file (by clicking New button).

This could make your sidebar unnecessary, but if you implement it *properly*, you could keep the sidebar. The sidebar should behave the same way as described above, especially the part about always closing a file before opening other file.

Your app is great and I really enjoy using it, most of the time. It's just these file-management bugs ruin the experience.

Hope we can resolve this soon and focus on writing again ;)

**Comment by lainsce** [comment]
All of your suggestions are what happen naturally in the app, the sidebar is just a "shelf" in which to choose the file to open. :heart:

**Comment by janxkoci** [comment]
Well there _is_ a problem somewhere, see #230. The new version of the bug actually overwrites files even if I follow the workaround I posted here before (i.e. creating and opening documents from Files). So right now I don't have _any_ safe way to work with my files (other than backups and restores, which is frustrating).

**Comment by lainsce** [comment]
Which version are you running? The latest?

**Comment by lainsce** [comment]
I've solved the linked bug, so, closing issue.
