### ISSUE TITLE
Quilter doesn't check spelling

### ISSUE THREAD

**Issue by lloerau** [lainsce/quilter#235]
Hello! Just installed Quilter on Elementary OS Juno, and found out that the app doesn't check my spelling. The spellchecker is switched on in the app, of course. Quilter version is 1.7.5

**Comment by lainsce** [comment]
I'll see what I can do

**Comment by lainsce** [comment]
Fixed in 1.8.1, soon released.

**Comment by lloerau** [comment]
Thank you!
