### ISSUE TITLE
Outline navigation issue

### ISSUE THREAD

**Issue by sempasha** [lainsce/quilter#237]
I expect outline items are clickable and clicking on it will scroll document to corresponding heading. But nothing happens.

**Comment by lainsce** [comment]
That's a feature I was working on for 1.8.1

**Comment by lainsce** [comment]
Thinking about it further, I think that searching for the header shown in the outline with the included searchbar is a better approach for this, and saves time not scrolling.

**Comment by sempasha** [comment]
Yes, of course. But what about situation you not know all the headers in the file. And it wloud be nice for people, who like clicking, to make a click.

**Comment by lainsce** [comment]
There's no way you won't know all headers if you open up the Outline pane. Also, people who like clicking can still click, except not lose focus and click click click.

**Comment by sempasha** [comment]
Lol
You are funny enough to donate for you.
