### ISSUE TITLE
Quilter crashes when creating a new document

### ISSUE THREAD

**Issue by fegue** [lainsce/quilter#238]
Quilter crashes when I try to create a new file by either clicking on the 'new file' icon in the headerbar or by clicking on 'New Document' in the sidebar.

To create a new file, I first have to save an empty markdown file and then open it in Quilter.

Quilter was installed from elementary AppCenter in version 1.8.0

**Comment by lainsce** [comment]
I'll see what I can do

**Comment by lainsce** [comment]
Fixed in 1.8.1, soon released.
