### ISSUE TITLE
Saving the file on every change

### ISSUE THREAD

**Issue by donadigo** [lainsce/quilter#24]
Saving files on every change you do in the document has a few issues that can make the experience unpleasant:

1. Even if your system can save files at a good rate / speed, some systems with slower hard drives or large documents could cause freezes in the app since you're doing that synchronously and on every change. 

2. That could also have an impact on SSD's which don't like a lot of write operations.

In this case you should have a timeout that e.g: 2 seconds, and if in those 2 seconds the user didn't change anything in the document, save the file, otherwise, reset the timeout.

**Comment by lainsce** [comment]
Thanks for pointing out!
Expect a fix in the next release.
- [ ] Fixed this bug.
