### ISSUE TITLE
Incorrect header parsing in sidebar

### ISSUE THREAD

**Issue by flaminestone** [lainsce/quilter#240]
All symbols after "#" is parsed like header, but it is incorrect. It will work only if "#" is placed at the beginning of the line (or if only spaces is placed before "#")

Example:
_____________________________________________
# Main header

```python
@post("/callback") # Section for /callback
def callback():
    if request.json['status'] == 2: # status 2 - is a status for build file. You can see all statuses in our api documentation https://api.onlyoffice.com/editors/
        file = requests.get(request.json['url']).content
        with open('files/' + request.query['filename'], 'wb') as f:
            f.write(file)
    return "{\"error\":0}"
```
_________________________

This part contain only one header (# Main header)

![image](https://user-images.githubusercontent.com/6047261/54738359-fa81e200-4bc4-11e9-947b-60c30c356606.png)

Version: 1.8.0
Thanks!

**Comment by lainsce** [comment]
I'm going to fix this

**Comment by lainsce** [comment]
fixed
