### ISSUE TITLE
Error opening the software from linux element

### ISSUE THREAD

**Issue by botijo** [lainsce/quilter#241]
## Hello! If you found an error in this app:

Error opening the software since the last update.

Kernel: 4.15.0-46-generic 
kernel-release: 49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 
hardware-platform: x86_64 
operating-system:  GNU/Linux

**Comment by lainsce** [comment]
I'm going to need more information than this.

**Comment by botijo** [comment]
A new update has arrived and the error has been fixed.  
Thank you for your work
