### ISSUE TITLE
Does not open

### ISSUE THREAD

**Issue by agnco** [lainsce/quilter#243]
I am running a fresh install of Elementary OS Juno, installed Quilter fine. Opened the first time clicked on something in the side bar and it seemed to crash. I have uninstalled and installed the app a number of times from the AppCenter but the app doesn't open.  It does show up in the dock but the app does not open.

**Comment by lainsce** [comment]
What does it say when you open up Terminal and run `com.github.lainsce.quilter`?

**Comment by lainsce** [comment]
Fixed, I found out what happened
