### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sempasha** [lainsce/quilter#245]
I'd facing the issue - couldn't get strikethrough text. There are many markdown specifications and implementations, usually I use double tilde `~~text~~`. But quilter doesn't support it. So I had to search another way to do it. And I'd found - HTML tag `<strike>`.

It would be nice qulter supports double tilde as well, ideally to support several common markdown syntaxes - github, commonmark and so on.

And better quilter should also provide some help with currently supported markdown syntax description.

**Comment by lainsce** [comment]
_NOTICE: I'm now in the middle of Uni midterms and as such, I cannot help you with fixing bugs until April 7th._

**Comment by lainsce** [comment]
Quilter does support `~~text~~` style strikethrough. Not a bug.

**Comment by sempasha** [comment]
I'm not sure you understand me.

First. I'd like quilter support `~~text~~` for strikethrough style. Like many other markdown editors. So it is mostly feature request.
Second. Usually the only way to ensure application supports or not some feature - is help reference, which missing for quilter. So the second feature request is help reference.

Thank you very much. Quilter is awesome despite some inconveniences.

**Comment by lainsce** [comment]
But it does support "`~~text~~` for strikethrough style" as well as "help reference" via the menu option Markdown Cheatsheet.

Но он поддерживает «`~~text~~` для зачеркнутого стиля», а также «справочную справку» через пункт меню Markdown Cheatsheet.

(translated with Google Translate)

**Comment by sempasha** [comment]
Oh, sorry, now I see it works well.
Going to buy new glasses and maybe new brain.
