### ISSUE TITLE
Trying to understand application's behavior.

### ISSUE THREAD

**Issue by ryanbabcock** [lainsce/quilter#249]
I am running version 1.8.2 from the AppCenter. I am not sure I understand the purpose of the application. I expected that the text field would display the body text of the currently highlighted item in the sidebar,  typing in that field will be automatically saved, saving a file would update the filename in the sidebar, and creating a new document would start with an empty text field. This does not appear to be the case.

The referenced behavior can be observed [here](https://www.youtube.com/watch?v=vhgqJ6lKx0A&feature=youtu.be).

This app is beautifully designed, but I find it to be completely unpredictable. If the intention is for the user to work on one file at a time, why does it give them the option to open other files?

**Comment by lainsce** [comment]
I'll explain it simply: Quilter was up to a version in the past a one-file-app. With the start of the Sidebar, I've been working on making it a multiple-files-per-session app. As such, bugs may occur and those are what I'm smashing every week. It takes time.

**Comment by janxkoci** [comment]
Okay but the result is that we can now reliably work with zero files :/

**Comment by lainsce** [comment]
That's not how any of this works, you yourself is having this problem, and I don't see anyone say the same.
You have a problem with the app, and I'm here to help. Don't forfeit this friendly conversation.

**Comment by janxkoci** [comment]
There is a video linked in the OP's post. I can reproduce it with my install of 1.8.2.

**Comment by lainsce** [comment]
Yes, but that behaviour seen in the video is what I'm currently fixing. I don't possess the power to fix things that are complex to fix in one day.

**Comment by lainsce** [comment]
Fixed in master.
