### ISSUE TITLE
Markdown rendering issues

### ISSUE THREAD

**Issue by janxkoci** [lainsce/quilter#253]
Hi there,

I have some issues when I try to preview my document in Quilter. Some parts of text are missing and instead I see something that resembles incomplete html tags:

![Snímek z 2019-05-30 10-09-03](https://user-images.githubusercontent.com/19331850/58618833-d973f680-82c3-11e9-899d-c46be952fc91.png)

When I open the same file in UberWriter (from flathub), it renders fine:

![Snímek z 2019-05-30 10-09-36](https://user-images.githubusercontent.com/19331850/58618880-ec86c680-82c3-11e9-8c12-adbc5d41eb2d.png)

It also renders properly on [my Github pages](https://janxkoci.github.io/linux_for_biologists.html), the problem is with [this file](https://github.com/janxkoci/janxkoci.github.io/blob/master/linux_for_biologists.md).

Unrelated issue is the duplicated entry in the sidebar.

**Comment by lainsce** [comment]
It seems that the inline local image syntax was picked up here, when it saw two `:` in sequence.
A small fix is on the way!

**Comment by janxkoci** [comment]
Fixed, thanks!
