### ISSUE TITLE
fountain markdown?

### ISSUE THREAD

**Issue by jolupa** [lainsce/quilter#255]
Sorry this is not a bug or a problem, so first sorry.
I want to ask if the software can write in fountain markdown[1] I just found the program searching for fountain markdown writter programs.
Thanks!
[1][Fountain Markdown](https://fountain.io)

**Comment by lainsce** [comment]
Dunno who tagged Quilter as such, but at the present time, it only does pure Markdown plus some extensions of its own. Sorry!
