### ISSUE TITLE
Exporting turns on dark mode

### ISSUE THREAD

**Issue by eliocamp** [lainsce/quilter#256]
Exporting to pdf while on light modes turns on dark mode. 

![Peek 2019-06-03 12-50](https://user-images.githubusercontent.com/8617595/58815566-393d0b00-85fe-11e9-81b5-a5853806b19f.gif)

**Comment by lainsce** [comment]
I'm going to fix this asap :+1:

**Comment by lainsce** [comment]
Fixed in master, soon released.
