### ISSUE TITLE
Losing Data... somehow...

### ISSUE THREAD

**Issue by poetgrant** [lainsce/quilter#259]
I recently switched from Slackware to elementaryOS on my laptop. I installed Quilter and loaded up a file that I have been working on in joe editor. I was at about 12,000 words. Well, I loaded it into Quilter and edited it a little, then hit save.  When I went back to add something to the document, there was nothing there. I thought maybe Quilter wasn't loading the file, so I opened it in joe editor and it was completely blank. 

So, luckily I had a backup saved on a thumb drive (though without the edits). So not all was lost, but it is giving me serious doubts about using Quilter now. Is there something I am doing wrong perhaps?

**Comment by lainsce** [comment]
Which version are you using? If it's below 1.9.0, then it might have file related issues like you describe.

**Comment by poetgrant** [comment]
It is version 1.9. I'm running it on elementary OS. Something else. I 
just saved a file manual, overwriting the original. When I went back to 
it, it was just blank. I'm not exactly sure what is going on. I would 
have thought that saving and overwriting the original would definitely 
save the file.

**Comment by poetgrant** [comment]
Is there a program I could use that monitors what the app is doing when I hit save? Like a terminal output or something? I am kind of new to a lot of the GUI programs.

**Comment by lainsce** [comment]
You could try to record a video of the issue and the steps taken. That'd be awesome for me to understand in which action it does the issue. There are screen recording apps on AppCenter, but off the top of my head I forgot the name of.

**Comment by poetgrant** [comment]
Oh! Good idea. I will look for it. Thank you for being so quick to respond! :D

**Comment by poetgrant** [comment]
https://photos.app.goo.gl/s1uB4XHDhkZzTSGH6

**Comment by lainsce** [comment]
Oh, that video is enlightening!

I'll look into the issues shown in the video as soon as possible!

**Comment by poetgrant** [comment]
Thank you!

I hope you didn't mind my suggestions during the video. The only text editor experience I really have is nano-editor and joe-editor. I wish I knew Vala, I might be able to help out more.

**Comment by lainsce** [comment]
UPDATE: This became more difficult than I could do alone, so I'm putting a Help Wanted.

**Comment by poetgrant** [comment]
I would be happy to pay a bounty if that is possible.

Also, I wonder if looking at the 'Code' codebase could help?

On June 10, 2019 12:03:50 PM EDT, Lains <notifications@github.com> wrote:
>UPDATE: This became more difficult than I could do alone, so I'm
>putting a Help Wanted.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lainsce/quilter/issues/259#issuecomment-500474229

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by lainsce** [comment]
The Code codebase uses tabs instead of what Quilter does which is a sidebar, the code for making stuff work is completely different. I'm sure there is a "gotcha" I'm not seeing.

**Comment by poetgrant** [comment]
I talked to the tootle dev, bleakgrey about it. He said it when it autosaves, it save everything in temp.md and that might be a place to start looking.

Joe Editor saves temporary files with a '~' in front of the file name. I wonder if there is a way to do that with Quilter.

**Comment by poetgrant** [comment]
There is also a thing Joe does when it abruptly gets shutdown called 'DEADJOE' where it saves your whole session, but I suppose that would be a separate issue and/or feature request. Hehehe

**Comment by lainsce** [comment]
> Joe Editor saves temporary files with a '~' in front of the file name. I wonder if there is a way to do that with Quilter. That way all the temp files stay separate.

That's.. it. I'm gonna try doing this.

**Comment by lainsce** [comment]
I've worked around this with a smarter way to handle files in the sidebar.
