### ISSUE TITLE
Hiding the side panel

### ISSUE THREAD

**Issue by elig0n** [lainsce/quilter#262]
Is there a way to hide the left side panel ? I couldn't find any.

P.S. will outline be navigational ?

Thanks!

**Comment by lainsce** [comment]
The side panel can be hidden with this button:
![Screenshot from 2019-06-23 00 32 04](https://user-images.githubusercontent.com/4886639/59971231-70903f00-954e-11e9-9891-b8b5e7769684.png)

As for your second question, in a future version, I'll try to make it navigational. :+1:
