### ISSUE TITLE
libmarkdown2 doesn't exist

### ISSUE THREAD

**Issue by yurivict** [lainsce/quilter#263]
Could you please provide the URL of the source of ```libmarkdown2```?
* Repology doesn't find it: https://repology.org/projects/?search=libmarkdown
* Arch linux doesn't find it: https://aur.archlinux.org/packages/?O=0&K=libmarkdown

Interestingly, the Arch port https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=quilter doesn't mention it. I wonder how does it build without ```libmarkdown2```.

**Comment by lainsce** [comment]
libmarkdown2 is a library found in the Ubuntu repos under:
- libmarkdown2
- libmarkdown2-dev

**Comment by yurivict** [comment]
libmarkdown2 redirects to the package called "discount" for some reason: https://packages.ubuntu.com/bionic/libmarkdown2

**Comment by lainsce** [comment]
Maybe it's a library add-on to `discount`. :man_shrugging:
