### ISSUE TITLE
Window size keeps growing if you dont delete files on the sidebar

### ISSUE THREAD

**Issue by Hedronmx** [lainsce/quilter#268]
* Window size keeps growing if you dont delete files on the sidebar
* If you don't dismiss files on the sidebar, the window keeps growing and growing vertically
* 1.9.2
* Screenshot
   ![Problem](https://i.imgur.com/2xacZC1.png)

**Comment by lainsce** [comment]
I'll devise a plan to curb this size bug.

**Comment by Hedronmx** [comment]
Anyway to remove all of the files?

**Comment by lainsce** [comment]
Clicking on the Remove All Files button will clean the sidebar of all files, without touching any of them.

**Comment by Hedronmx** [comment]
I cant, window is to tall for my monitor

**Comment by lainsce** [comment]
Oh, then we will have to be technical about this:
- Install Dconf Editor on Appcenter
- Without touching anything, go to com > github > lainsce
- Right click on quilter and select reset recursively
- Click on the statusbar white checkmark
- Re-open Quilter, which should now be reset completely.

**Comment by Hedronmx** [comment]
Got it, thanks! Could you add a way to remove files individually? Or I am missing something

**Comment by lainsce** [comment]
The thing is, it had that function, but was too messy and deleted users files under their noses. I preferred to go with a single button. I'll make it so the sidebar doesn't grow, in August.

**Comment by Hedronmx** [comment]
ALright thank you for your time,

**Comment by lainsce** [comment]
Fixed, soon in AppCenter
