### ISSUE TITLE
Spell checking not working

### ISSUE THREAD

**Issue by GeorgeZack** [lainsce/quilter#269]
I have been using Quilter on ElementaryOS, installed from the app store. I cannot figure out how to get spell checking to work. I have updated, reinstalled, and restarted. Nothing will work. Using version 1.9.2

Thanks!

**Comment by lainsce** [comment]
What language is your system running on? If English, make sure that in Settings > Extensions you have Spellchecking enabled.

**Comment by GeorgeZack** [comment]
It looks like my system language needs some updating. I don't have access to the internet at the moment so I will update you with that.

**Comment by GeorgeZack** [comment]
I updated my system language, reset the computer, reset the preference, the application. But still no luck. Do you think this is a system issue rather than Quilter? I'd hate to bother you about a linux issue rather than an application issue.

**Comment by lainsce** [comment]
This might be a system issue if your system language has a strange code to represent it. Ex. English is "en", but also "en_us" if it's English (US).

**Comment by GeorgeZack** [comment]
It seems like LibreOffice Writer is able to spell check English words.

**Comment by lainsce** [comment]
I'll look into it then. Seems like Quilter is the culprit.

**Comment by lainsce** [comment]
Fixed, soon in AppCenter
