### ISSUE TITLE
Feature Request: When in Half-Width mode, sync scrolling

### ISSUE THREAD

**Issue by fastrizwaan** [lainsce/quilter#275]
If we visit https://stackedit.io/app# and scroll down and type, we can see the right side view also scrolls down to the editing line.

in Quilter, the if we scroll down, the preview does not scroll to the current line which is being edited/typed.

It is extra effort to first type text then scroll down in the preview area on the right

I'm using quilter-2.0.0-1.fc31 on fedora 31. thanks

**Comment by lainsce** [comment]
I'll see what I can do!

**Comment by lainsce** [comment]
Due to some exhaustive searching about this and how to do it, it seems this is not so easily possible under current GTK. As soon as GTK delivers something to link both widgets together more easier, I'll do this.

**Comment by fastrizwaan** [comment]
> Due to some exhaustive searching about this and how to do it, it seems this is not so easily possible under current GTK. As soon as GTK delivers something to link both widgets together more easier, I'll do this.

Please do ask the GTK developers for such feature. GTK4 is in development. Thank you

**Comment by lainsce** [comment]
I have started work on this, master will have a bug until I finish this.

**Comment by lainsce** [comment]
Fixed in master.

**Comment by fastrizwaan** [comment]
Just updated to git version. It partially works. Typing at the end of document won't update text in the right side. The right side does not scroll down completely.
![Screenshot from 2019-12-18 22-12-47](https://user-images.githubusercontent.com/1161682/71105488-aa7f8c80-21e3-11ea-8c64-3d72c89700c7.png)

**Comment by lainsce** [comment]
That's the problem. This is what I could do given the restraints of what I've researched on GTK functions about syncing the scrolling...
