### ISSUE TITLE
The manual saving of a file should automatically update the file name in the headerbar as well as in the sidebar

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#276]
* Describe the issue
However, if I save the first opened "New File" as test.md for example, it will not be displayed to me. Quilter still shows "New File" in both the header and the sidebar. My expectation would be that Quilter would simply rename the existing "New File", and these changes would be visually regenerated automatically in the header and sidebar. Like elementary Code does it for example. Right now it seems to me that Quilter keeps the existing "New File" unchanged, while in my File browser (elementary OS Files btw.) the new file is written with the name I want to save it under.

* State what version you're using
2.0.1

**Comment by lainsce** [comment]
Fixed in 2.0.2
