### ISSUE TITLE
Feature Request: When system History setting is off, don't remember saved state

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#277]
* Describe the issue
Comparable to https://github.com/elementary/files/issues/822
At the moment the last used file is restored automatically.
* State what version you're using
2.0.1
* Possible solution
One solution would probably be, if no history should be created, that a session closes automatically with all its open files, if I close quilter over the x button.
Further suggestions can be found here https://github.com/elementary/files/pull/823

**Comment by 4jNsY6fCVqZv** [comment]
Out of curiosity: What blocks this issue?

**Comment by 4jNsY6fCVqZv** [comment]
Hello, what I don't understand: Why should it depend on my hard drive and its age/speed which icon Quilter chooses for a new file? I would expect Quilter to always recognize Markdown as such and not make it a plaintext file!

**Comment by lainsce** [comment]
A better title :P

**Comment by 4jNsY6fCVqZv** [comment]
Yes, much more readable:)

**Comment by 4jNsY6fCVqZv** [comment]
Does this also include window and position settings for you? I'm not sure if it's all about content. How does the elementary do it?

**Comment by lainsce** [comment]
Basically, they don't remember saved state of files, but all other functions are saved.
It _should theoretically be easy_ but I'll need to study this further.

**Comment by lainsce** [comment]
Fixed in master.
