### ISSUE TITLE
The entries of the "Outline" tab should also be cleaned immediately when I press the "Remove All Files" button

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#278]
* Describe the issue

Steps to reproduce the bug:
1. Open any .md file with Quilter which has already content. For example, a few headings.
2. Hit "Remove All Files"
3. Switch to "Outline" tab
4. The outline of the last opened file is still displayed, while the text editor in the right column gets clarified as intended.
My expectation would be that if I clear all files of the current session, Quilter will not be able to display it's contents anymore. Quasi in the sense of data protection.
* State what version you're using
2.0.1.

**Comment by lainsce** [comment]
Fixed in 2.0.2
