### ISSUE TITLE
When the sidebar is open, quarter tiling should still be possible

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#279]
* Describe the issue
Currently only maximizing the window works as soon as the sidebar is open. As soon as the sidebar is closed, quarter tiling works again.
My expectation would be that I can use quarter tiling with the sidebar open.
* State what version you're using
2.0.1

**Comment by lainsce** [comment]
Since elementary OS does not use quartertiling by default nor it'll have it in the foreseeable future, I'm closing this as invalid for now.

**Comment by 4jNsY6fCVqZv** [comment]
You argue with the default of the elementary theme. Unfortunately, I can't quite understand why you're closing the issue because of this. The reason for my issue was that the behavior within Quilter is not consistent.It is not holistically related to the operating system and its properties.
I'm asking you to reopen the issue if you still think it's an improvement for Quilter.
Whether you find time or would like support from other developers to realize it, it's something else, isn't it?

**Comment by 4jNsY6fCVqZv** [comment]
Cannot reproduce the issue with the last release 2.0.3.  Looks like quarter tiling is working as expected!

**Comment by lainsce** [comment]
Oh, nice!
