### ISSUE TITLE
File names of deleted files should not be reused. Instead Quilter should name a new file "New File".

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#280]
* Describe the issue
I created an .md file with Quilter. I deleted it in elementary Files with Shift+Del.
Also in Quilter I pressed the button "Remove All Files", so the file should not be there anymore. So my expectation.
When I open the app the headerbar says "No Documents Open". If I have parallel Files open, I see how Quilter creates a probably temporary file. And with the name of the file, which I had already completely deleted. How is that possible? I don't want deleted file names to be used again by default. A test with two files showed that Quiler selects the last file name used for saving. From a privacy perspective, I want Quilter to forget the file names when I remove all information about this file from the system.

* State what version you're using
2.0.1

**Comment by 4jNsY6fCVqZv** [comment]
EDIT: It looks as if the bug can also be reproduced with the reading time. Sometimes Quilter writes the read time of previously deleted files for new files. But the new file is empty, unsaved and contains no characters. The new files come from the cache first, don't they?

**Comment by lainsce** [comment]
Fixed in 2.0.2
