### ISSUE TITLE
Quilter should use the default Media type text/markdown icon when I create a file with it

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#281]
* Describe the issue
The default elementary OS Media type would be: Media type text/markdown I guess.
At the moment Quilter creates just a "Media type text/plain" instead in Files, compared to the correct "Media type text/markdown" icon that is shown in Quilters sidebar. Applies to all files I have tested with.
* State what version you're using
2.0.1

**Comment by 4jNsY6fCVqZv** [comment]
EDIT: I'd like to reproduce the issue reliably. Unfortunately, I can't do that right now. Rarely, but sometimes a media type text/markdown appears after saving. But mostly not.

**Comment by lainsce** [comment]
I don't seem to reliably find this bug as well. In my cse, it's always 99.99% correctly identifying itself.

**Comment by 4jNsY6fCVqZv** [comment]
What can I do as a user to give you more information?

**Comment by 4jNsY6fCVqZv** [comment]
How can we get closer to a solution?

**Comment by lainsce** [comment]
The thing varies and isn't 100% because of disk speeds or read/write limits. So if you have an older hard drive, then it'll show it wrong but is benign.

**Comment by lainsce** [comment]
Closing....

**Comment by 4jNsY6fCVqZv** [comment]
Hello, what I don't understand: Why should it depend on my hard drive and its age/speed which icon Quilter chooses for a new file?
I would expect that Quilter always display Markdown when it creates Markdown. And don't just make it a .md file that looks like a plaintext file in the File Browser!

**Comment by 4jNsY6fCVqZv** [comment]
Do you have any idea why Quilter chooses the wrong icon?

**Comment by lainsce** [comment]
Because I chose for it to show the md icon in the UI. Since you can't open other files than .md files, it should show a Markdown file. In Files though, I don't know.

**Comment by 4jNsY6fCVqZv** [comment]
In the sidebar of Quilter the icon is correct. As far as I know it always shows the Markdown icon, even if Files shows a plaintext icon afterwards. By the way, it is also exciting that elementary Code sometimes also picks a plaintext icon when saving, although I format the new file specifically as Markdown and save the file as .md as well. I'll open an issue there and see if there are any other ideas for a solution that Quilter can use.
