### ISSUE TITLE
The calculated read time should be deleted when I press the "Remove All Files" button

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#283]
* Describe the issue
Steps to reproduce the issue:
1. create a new file with Quilter.
2. insert enough character material so that quilter can even make a minute specification greater than 0.
3. press the "Remove All Files" button.

I would expect the read time to be set to "0m". Quilter still shows me the previously calculated time. The issue occurs with all tracking types.

Allow me a technical question: How is the reading time calculated by Quilter? I suspect that there are many more issues involved than what I have just tried to formulate here.

* State what version you're using
2.0.1

**Comment by lainsce** [comment]
Fixed in 2.0.2
