### ISSUE TITLE
Quilter creates a new file named "New File" in /home with "Media type: text/plain" without asking

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#285]
* Describe the issue

Exciting is, at first I thought it was just a temporary file, because I didn't save a new file with the name and put it there.
Steps to reproduce the issue:
1. Open the app
2. Click "New file" in the menu bar
3. Close Quilter via the "x" button without saving the file.
4. Open Quilter again and the file will be created at the same moment.
However, if I press the "Remove All Files" button before step 3, the file will not be created after the restart.
If it's a temporary file I would expect that it will not be made visible to users in the File Browser at all. For a temporary (opened) file LibreOffice chooses hidden solutions like ".~lock.test.odt#" for example.
I also don't want to have to delete it manually every time. For me there is no use of this empty plaintext file. Where does it come from? What is its use in Quilter?
* State what version you're using
2.0.1

**Comment by lainsce** [comment]
This is such a weird one... Highly unreproducible.

**Comment by 4jNsY6fCVqZv** [comment]
What makes the issue unreliable for you to report?
With the method described above, it is at least 100% reproducible for me. What I can add: Even if I add another "New File" in Quilter, it stays in the /home directory with only one new plaintext file that is created automatically.

**Comment by lainsce** [comment]
Oh, I read your instructions wrong. Sorry! I have that file now in Home. Oof.

**Comment by 4jNsY6fCVqZv** [comment]
Do you have any idea why this file is created at all? Is it a temporary file that Quilter doesn't handle as such?
At least that's obvious for me, because the file is only created when I do the above steps. So create a "New File" via the button and don't save it and restart Quilter.

**Comment by lainsce** [comment]
The help wanted label is for other developers to help with fixing the bug, as this specific bug is out of my league due to how complex it is in-code to find.

**Comment by lainsce** [comment]
Fixed! :tada:

**Comment by 4jNsY6fCVqZv** [comment]
Whoa, thanks! How did you find out? I'm still waiting for AppCenter to install the updates. Thank you very much for fixing all the bugs and I'm curious to see how Quilter has evolved!

**Comment by 4jNsY6fCVqZv** [comment]
Whoa, thanks! How did you find out? I'm still waiting for AppCenter to install all the latest updates. Thank you very much for fixing all the bugs and I'm curious to see how Quilter has improved!

**Comment by 4jNsY6fCVqZv** [comment]
Whoa, thanks! How did you find out? I'm still waiting for AppCenter to roll out all the latest updates. Thank you very much for fixing all the bugs and I'm curious to see how Quilter has improved!

**Comment by lainsce** [comment]
Basically there were methods that were creating files based on the subtitle instead of path
