### ISSUE TITLE
Broken code blocks highlighting

### ISSUE THREAD

**Issue by ashucg** [lainsce/quilter#286]
**Problem**: Correct preview is not generated when using following markdown
#### Markdown:
```
### Example 1
`curl -o /dev/null -w 'Connect: %{time_connect} Total time: %{time_total}' https://example.com`

---

### Example 2

`find . -regextype posix-extended -regex ".*-[[:digit:]]{2,4}x[[:digit:]]{2,4}(@2x)?.(jpg|jpeg|png|eps|gif)" -type f -ls`
```
#### Screenshot:
![image](https://user-images.githubusercontent.com/11291284/67289318-efca5b00-f4cd-11e9-9908-91ae451f7c0e.png)

#### Same Markdown In [GhostWriter](https://github.com/wereturtle/ghostwriter):
![image](https://user-images.githubusercontent.com/11291284/67289437-230cea00-f4ce-11e9-9be0-af4dc959dc1b.png)

**Version:** 2.0.0-1.fc30 (from Fedora repository)

**Comment by lainsce** [comment]
What happens here is that the code used inside these blocks has special characters that Quilter looks for for external files. Quilter isn't really for technical documents using `%` or `|`.

**Comment by ashucg** [comment]
okay, I understand, thank you for your reply.
