### ISSUE TITLE
The animation of switching between full width / half width should match the animation of switching between Edit/Preview.

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#288]
* Describe the issue
Currently it looks like if there is a strong flashing of the editor when switching between Full-Width/Half-Width.
If you switch between the Edit/Preview view, the animation is much smoother (like fading in/out) and more pleasant. Would it be possible and useful to match both animations?
Opening and closing the sidebar, for example, is just as smooth.

* State what version you're using
2.0.3

**Comment by lainsce** [comment]
It would look very strange to see it swipe between Width modes. They aren't pages of a book, they're supposed to change between them in a fade animation. Maybe the animation is too fast? But then I can't control the speed.

**Comment by 4jNsY6fCVqZv** [comment]
Yes, definitely too fast for my perception!
What do you mean when you say you can't control the speed?  Is there no passage in the code?

**Comment by lainsce** [comment]
It's a fixed speed animation that I can't change.

**Comment by 4jNsY6fCVqZv** [comment]
where is the position in the code? How is the animation created?

**Comment by lainsce** [comment]
The animation comes with GTK. I don't have any code in my app dealing with it.

**Comment by 4jNsY6fCVqZv** [comment]
I don't understand yet. Somehow you have to include GTK code to get the animation, don't you?

**Comment by lainsce** [comment]
Yes. And since I include GTK, I can't simply change GTK animation speed on Quilter. It's a fixed value I can't change.

**Comment by 4jNsY6fCVqZv** [comment]
Which GTK code do you use for this animation?

**Comment by 4jNsY6fCVqZv** [comment]
When I look at https://elementary.io/docs/human-interface-guidelines#comboboxes, I wonder why you chose a combobox here? Wouldn't it be possible to solve that via https://elementary.io/docs/human-interface-guidelines#linked-buttons? The animation also depends on the choice, doesn't it?

**Comment by lainsce** [comment]
No, the animation doesn't depend on the choice of widget. Also, I chose a combobox because of familiarity with other apps of the same category.

**Comment by lainsce** [comment]
Going to lock conversation because it seems this will never end.
