### ISSUE TITLE
If I permanently delete a file created with Quilter from the File Browser, Quilter should not restore it automatically after every restart

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#289]
* Describe the issue
Steps to Reproduce:
1. click on "Remove all files".
2. close Quilter
Open the quilter again.
4. create a "new file".
5. save it as "test".
Note: Quilter now changes the filename and path directly and displays it :)
6. close Quilter.
7. Within Files use Ctrl.+Del to remove test.md
Note: The file is again only displayed with the plain text symbol.
8. open Quilter again.
9. test.md with the previous directory is displayed again in the File Browser as well as in Quilter. So it seems impossible to delete the file. Each time Quilter is deleted and restarted, the file is back.

EDIT:
The procedure is repeated until after restarting Quilter I create a new temporary? file with the "New file" button. Then a permanently deleted Quilter file will be permanently deleted.

* State what version you're using
2.0.3

**Comment by lainsce** [comment]
It seems that you forgot to clean the Quilter workspace with the Remove All Files button before going to Files and deleting the file. That's how it should be done. The other way around would be a bug with Files.

**Comment by 4jNsY6fCVqZv** [comment]
You mean step 5 should be the Remove All Files button again?
And then close Quilter and look at the File Browser?

**Comment by lainsce** [comment]
Yes, everytime you're done with your writing session you should clean it. This includes wanting to delete the file in Files later.

**Comment by 4jNsY6fCVqZv** [comment]
You also write that your path represents the desired user behavior. 
To me this way does not seem intuitive. There is no hint by the app itself that the procedure should be like this and not different. I have looked at Code and LibreOffice for comparison. It is always possible to permanently delete a previously saved file via Files. Even if it is still open. It does not come back. This logic would be what I expect, because I am so used to it from other common apps in this field. Why did you choose a different logic?

**Comment by lainsce** [comment]
Because Quilter isn't meant to be a code editor nor a word processor. It's meant to be a story drafter or similar long length text writing with the use of Markdown. As such, I'm using the logic of similar apps.

**Comment by 4jNsY6fCVqZv** [comment]
Do you have a similar app that I can install via AppCenter and that has a similar
Especially in the context of https://github.com/lainsce/quilter/issues/277 I feel it important that closing Quilter also means that old information does not reappear if I do not want that.

**Comment by 4jNsY6fCVqZv** [comment]
By the way, your suggestion from https://github.com/lainsce/quilter/issues/289#issuecomment-550011510 doesn't work. It leads to a new file being created, which solves https://github.com/lainsce/quilter/issues/280, but a similar error as in https://github.com/lainsce/quilter/issues/285 still exists. There is then this additional file, which strangely enough constantly flickers in the file browser and in addition constantly changes its name. Even a permanent deletion of the new file does not lead to any changes, as soon as I restart Quilter, both are there again. The only way to solve this problem is to open Quilter and click on "New file". Then the flickering stops immediately and I can permanently delete the test file in Files as usual.

**Comment by lainsce** [comment]
That's very weird. The `test.md.xxxxx` shouldn't exist outside of the cache folder.
Open up a new issue with this.

**Comment by 4jNsY6fCVqZv** [comment]
Why a new issue, the problem that is looking for a solution, is already in the title of this issue, isn't it?
I also think it's faster if you open one yourself than if you first write me that I should open one, don't you? :)

**Comment by 4jNsY6fCVqZv** [comment]
Why a new issue, the problem that is looking for a solution, is already in the title of this issue, isn't it? You can also reopen this issue.
