### ISSUE TITLE
Saved file constantly being refreshed

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [lainsce/quilter#29]
When I open a text file with Quilter, and look at the text file in the file manager, I notice that it is flickering, and I can't even select it properly, because it deselects itself every time it flickers. Is the file getting constantly refreshed (saved?)? Isn't this a bad practice because it constantly engages the hard drive? I think the auto-save should have a saner period, like 10 seconds maximum. Even if the computer burns, a person doesn't lose more than 10 seconds of work. Maybe even better solution would be to save on losing focus, like many text editors (AFAIK, Scratch included) do.

**Comment by lainsce** [comment]
Will do a fix, expect it on the next release! 📦
