### ISSUE TITLE
Even if no file is open, I can write in the editor

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#290]
* Describe the issue
Since this content is lost even when clicking on the "New file" button, I would expect that I cannot use the editor without opening a file first.
The "Save as..." button is logically also blocked. Maybe it would be nice if it could become insensitive, if there is no option to save?
It would be wonderful if Quilter would also give me a visual hint what to do to be able to use the editor.
* State what version you're using
2.0.3

**Comment by lainsce** [comment]
Nope, the save as button should work even in this state, correctly saving what you typed in a file and opening that file as you finish saving as a file.

**Comment by 4jNsY6fCVqZv** [comment]
There's no open file.

Steps to reproduce:
1. Open Quilter
2. write something into the code editor
3. try to save it -> nothing happens when i press the "Save as" button
4. create a "New file" -> the previously typed content is lost

**Comment by lainsce** [comment]
I have no idea how you got into the state you're describing, because I never got into that state where the Save As button doesn't work. It should _always_ work.

**Comment by 4jNsY6fCVqZv** [comment]
Unfortunately I can reproduce the error at will. There is not a single case where saving would be possible.  I am using a standard elementary OS without any modifications.

**Comment by lainsce** [comment]
I'll see what I can do, but I'm assuring you that your remaining issue is a very specific case that doesn't seem to happen too often.

**Comment by 4jNsY6fCVqZv** [comment]
How do you come to the conclusion that the case is very specific and does not occur so often? I can reproduce it at any time, without exception. For me, this is the opposite of rare.
Can you share what it looks like for you if you follow my steps?

**Comment by janxkoci** [comment]
I can confirm the issue with the latest version. I closed all documents, typed into the empty canvas and Save as.. does nothing.

**Comment by lainsce** [comment]
I'm locking this as #296 is the issue to go to for Save As button bugs.
