### ISSUE TITLE
Bug: Preview View contents not cleared when should be

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#291]
* Describe the issue
Even if I press the "Remove All Files" button, the preview view is not cleared.
For both tabs (Files" and "Outline") in the sidebar, the old content is displayed in the preview view. I would expect that if nothing is open, Quilter will not be able to show old data. But I also wonder where the app can get this data from at all ...
**EDIT:** Even if I close Quilter several times and open it again, the error remains.
* State what version you're using
2.0.3

**Comment by lainsce** [comment]
This is indeed a weird thing. I'll look into it.

**Comment by 4jNsY6fCVqZv** [comment]
merci!

**Comment by lainsce** [comment]
Fixed in master
