### ISSUE TITLE
Change tooltip from "Start search" to "Find..."

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#293]
* Describe the issue
See https://elementary.io/docs/human-interface-guidelines#distinguish-search-find
->  "Find is for highlighting matching instances of a string." I think that describes the current behavior of Quilter.
* State what version you're using
2.0.3

**Comment by lainsce** [comment]
Will change it soon™

**Comment by lainsce** [comment]
Fixed.
