### ISSUE TITLE
Find & replace -> "Replace" button does not work

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#294]
Steps to Reproduce:
1. Create a test document with the sentence: "This is a test!
2. Search for " a " in the " Find text... " field. 
3. Enter " no " in the "Replace with..." field.

Expected result:
Quilter makes the change when I press the "Replace" button.
Current: Quilter does nothing.
It only works when I press the "Replace all" button. But if there is only one possible string, it's not a logical behavior, that only this button has an effect.

* State what version you're using
2.0.3

**Comment by lainsce** [comment]
I can reproduce this, will fix once I'm back.

**Comment by lainsce** [comment]
Fixed. Added a tooltip to guide on how it works.
