### ISSUE TITLE
"Save as..." Button does not work

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#296]
* Describe the issue
Steps to reproduce the error are described here: https://github.com/lainsce/quilter/issues/290#issuecomment-550346638
Unfortunately I can reproduce the error at will. There's no exception.
* State what version you're using
2.0.3

**Comment by lainsce** [comment]
Not sure why or how you get this bug, see this recording from Quilter downloaded straight from AppCenter and also cleaned of previous use:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/4886639/69466734-0e896f00-0d64-11ea-9290-357eb2ae2be1.gif)

**Comment by 4jNsY6fCVqZv** [comment]
Can you please share a short screencast? I test with a complete reinstallation. Like I said, I can reproduce the issue without exception and at will. As a question for me: You have already tried to safe it if Quilter is open, but no new file is created before? My expectation would then be that Quilter would create a new file directly and display it in the sidebar.

**Comment by lainsce** [comment]
Sorry, but I can't reproduce this.
