### ISSUE TITLE
Quilter saves files when it should not

### ISSUE THREAD

**Issue by janxkoci** [lainsce/quilter#297]
As it says on the tin, Quilter saves files when it shouldn't, namely:

* I have the option **Save files when changed** turned **off**
* I didn't do any change to the file

But the file I open from file manager is saved to the disk within seconds after opening, even though I have disabled the option and didn't change the file.

This is with the latest version: 2.0.3. I didn't notice this behavior in previous version.

I'm now worried again to use Quilter, as this was one of the symptoms back when Quilter was overwriting my files - it just messed up where to save the current file and then saved it where I didn't want, namely over another file. This is *why I turned off* the autosave to begin with. And now this *safety feature* (as I call it in my head) doesn't work anymore. Now I don't want to use the app with several files as I worry it will start to overwrite wrong files *again*. Please fix it.

**Comment by lainsce** [comment]
I will fix it, don't worry. Must have been something I missed.

**Comment by lainsce** [comment]
Fixed in master

**Comment by janxkoci** [comment]
I can confirm it no longer happens.

**Comment by nevillepark** [comment]
It still happens :(

**Comment by lainsce** [comment]
Update your Quilter version to the last version.
