### ISSUE TITLE
Strange and flickering file [format: example.md.xxxxx with plain text icon] is displayed

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#298]
* Describe the issue
The issue is well described here https://github.com/lainsce/quilter/issues/289#issuecomment-551870393
* State what version you're using
2.0.3

**Comment by lainsce** [comment]
You can be assured that this file is not harmful and it's not a bug.

**Comment by 4jNsY6fCVqZv** [comment]
You wrote:
> That's very weird. The test.md.xxxxx shouldn't exist outside of the cache folder.
Open up a new issue with this.

That's why I've created this issue. If you send me your developer contact address, I will show you with a short video, that Quilters behaviour is not harmful, but a bug.

**Comment by lainsce** [comment]
I've tested Quilter straight from AppCenter and clean of any previous configuration, and the file never appears outside the cache folder. I'm sorry but it's really tiring to chase bugs if I see nobody but you face this issue. Can you provide a video doing exactly everything that triggers the bug?

**Comment by 4jNsY6fCVqZv** [comment]
Well, on the one hand, I understand you can't reproduce the issue. On the other hand, it's not said that other users don't have the problem. I see that I can make a screencast. Is there a way to find the bug through logs? Or by running it in the terminal?

**Comment by 4jNsY6fCVqZv** [comment]
Well, on the one hand, I understand you can't reproduce the issue. On the other hand, it's not said that other users don't have the problem. I will see that I can do a screencast. Is there a way to find the bug through logs? Or by running it in the terminal?

**Comment by lainsce** [comment]
All I'm going to say is that this isn't an issue that I should devote time and resources to "fixing" because it does not make Quilter have adverse affects nor does it make sense to fix. I could be fixing other things which have a more pressing problem than this.
