### ISSUE TITLE
Unknown crash 3rd line core dump.

### ISSUE THREAD

**Issue by CodeManS99** [lainsce/quilter#30]
Every time I write in the application I get to about the second line and the app crashes losing everything I just typed. Here is the process info.`$ com.github.lainsce.quilter %U
[INFO 12:44:21.354092] Application.vala:153: Quilter version: 1.1.7
[INFO 12:44:21.354183] Application.vala:155: Kernel version: 4.8.0-58-generic
[WARNING 12:44:21.418808] [Gtk] Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name
[WARNING 12:44:21.418931] [Gtk] Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name
[WARNING 12:44:21.419066] [Gtk] Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
[ERROR 12:45:25.230568] FileUtils.vala:110: Error removing file: Permission denied
Trace/breakpoint trap (core dumped)
`

**Comment by lainsce** [comment]
I'm looking into it and will soon issue a release with the fix.
Thanks for doing this bug report!

- [ ] Fix released

**Comment by Faelian** [comment]
On my machine, the bug seems to happen when using a custom font size (defined from Quilter preference's menu).

**Comment by CodeManS99** [comment]
Huh, I disabled custom font on mine but it still crashes.

**Comment by lainsce** [comment]
I might have fixed this in master, clone the repository and compile it locally as per the README, and say if it's resolved.
