### ISSUE TITLE
Replacing a file with a newer version adds a new entry to the sidebar

### ISSUE THREAD

**Issue by 4jNsY6fCVqZv** [lainsce/quilter#300]
* Describe the issue
My expectation: If I save an opened file again with "Save as..." under the same file name using the replace dialog, no new entry should be created in the sidebar.
* State what version you're using
2.0.3

**Comment by lainsce** [comment]
This is a bug I can reliably reproduce! :tada:

**Comment by lainsce** [comment]
Fixed in master
