### ISSUE TITLE
Cant't export to PDF

### ISSUE THREAD

**Issue by lfmg96** [lainsce/quilter#303]
Hello!
 
When I export a PDF document, it export a empty document that can't be readed.

I don't know if it's a Quilter problem or a system problem.

Can you help me?

I'm at 2.0.3 version.

![PDF Bug](https://user-images.githubusercontent.com/58710073/70478165-2af20f00-1ab9-11ea-921f-1883fe74b35a.png)

![image](https://user-images.githubusercontent.com/58710073/70478235-58d75380-1ab9-11ea-904b-d95409006a77.png)

**Comment by lainsce** [comment]
It looks like your system language preferences is not ideal, mixing English and Portuguese…
Try fixing that first then try exporting again. Quilter needs the language set correctly for PDF exports because it uses a system thing which can change names with languages.
