### ISSUE TITLE
Incorrect Markdown rendering

### ISSUE THREAD

**Issue by shawn1thompson** [lainsce/quilter#309]
I'm not sure if this was addressed in the most recent version. I don't see any updates to Markdown, but am also not sure the problem is there. I'm still on 2.0.4 as the elementary OS App Center has not updated to the most recent version. Here's the problem:
**This:**
# The 10 Commandments of Success
*taken from The Business of Life (1916) by Frank Crane*
1. Control Your Thoughts
2. Be Courageous
3. Make a Program And Follow It
4. Find Out What You Want
5. Settle the Sex Problem Intelligently
6. Pay Attention to Your Money
7. Adjust Yourself
>The secret of efficiency is adjustment. Those who do things are they that know how to adjust.
8. Be a Good Sport
>To be a good sport means to be a good loser.
9. Go On
10. Obey Your Conscience
**Renders:**
![Screenshot from 2019-12-26 11 26 06](https://user-images.githubusercontent.com/32218754/71484552-92ef6780-27d2-11ea-806f-1ba706d9f07c.png)

I've tried changing various things in the syntax, but it never renders properly. Also, just looked at the preview of my post and Github renders it correctly.

With all that, thanks for the app. It's usually enjoyable.

**Comment by lainsce** [comment]
The thing is, GitHub uses another set of Markdown rules that they themselves created. Quilter doesn't use that set, it uses the actual Mardown from the official specifications. In the official specifications, any block quote that doesn't have a double empty line will continue adding to it as seen in Quilter.

This is not a bug :wink:
