### ISSUE TITLE
Weird Font Issue

### ISSUE THREAD

**Issue by Hedronmx** [lainsce/quilter#31]
I have a strange font issue, on the menu and on the title. Everything besides those two areas look good.
See the image for a reference. I couldn't screenshot the menu...

http://imgur.com/a/Wvjwg

**Comment by lainsce** [comment]
Are you using the default GTK theme and default fonts? 🤔

**Comment by Hedronmx** [comment]
I'm using arc theme and Roboto font.. Let me try to revert back to defaults.

**Comment by Hedronmx** [comment]
It looks great on default settings... hmmm so... Now what lol

**Comment by lainsce** [comment]
Now stop using non-defaults then? 😂 

Seriously. Non-default theming breaks everything and "voids" the warranty of bug-free software on elementary OS.

**Comment by Hedronmx** [comment]
Alright, Ill stop using your app.

Thanks dude :D

**Comment by lainsce** [comment]
I'm sorry to see you go, but really reconsider if you really want to stop using my app for your needs.

**Comment by Hedronmx** [comment]
Oh man sorry I forgot the :p emoji. I won't stop using your app for a simple font bug! I love it!

**Comment by lainsce** [comment]
Ah, ok! 😂
Thanks!
