### ISSUE TITLE
Use $ $ for inline math in KaTeX

### ISSUE THREAD

**Issue by RyanGreenup** [lainsce/quilter#311]
I quite like this app because it's so quick and snappy on *Elementary*, all my markdown notes use  single `$` to delimit inline `$\LaTeX$` and I really think that should be implemented as well as `\( \LaTeX \)`.

Also is it possible to use a custom CSS?

## Documenting LaTeX support

Also it might be worth mentioning in the readme that the version in the AppCentre is out of date, so to get TeX support it is necessary to install from the AppCentre, then build from source and then ` sudo mv com.github.lainsce.quilter /usr/bin/`

Thanks!

**Comment by lainsce** [comment]
You can enable LaTeX support by toggling the switch on in Preferences under Extensions. `$...$` is the only syntax possible for LateX though. The AppCenter version is 2.1.0, shouldn't be lower unless you're not updated.
