### ISSUE TITLE
Issues with Quilter's previewer on scroll

### ISSUE THREAD

**Issue by CharlieBoyer** [lainsce/quilter#313]
Hello !
I encounter a issue with Quilter's documents preview. I'm on the v2.1.0 running on ElementaryOS 5.1 (Based on Ubuntu 18.04.3 LTS ; Linux 4.15.0-76-generic ; GTK 3.22.30)

This issue is pretty weird, for some reason, when Quilter have a "well-sized" window, in preview mode, "exceed" the top of document by scrolling-up, move instantaneously at bottom of the previewer, far from the document. After some tests to reproduce that behaviour, it seems the bug is not triggered if Quilter start with a smaller window.
Besides, it happen several times that the preview was kept with this position (at the bottom) even when switching between modes.
After testing multiples times, the bug triggers seems to change, I have sometimes no problems or no position-lock when switching between modes.

I add a zipped screen-cast to illustrate the issue. I hope I've been enough precise.
Thanks in advance !
[quilter_preview_issues.webm.zip](https://github.com/lainsce/quilter/files/4156782/quilter_preview_issues.webm.zip)

**Comment by lainsce** [comment]
This is a bug with every app that has the preview scroll position sync with the editor position, and can't be fixed by me currently.
