### ISSUE TITLE
Opening files changes modification time, even without edits

### ISSUE THREAD

**Issue by the-kazooboy** [lainsce/quilter#315]
Opening a file changes its modification time, even if Quilter makes no modifications to the file.

Using version 2.1.0-1.fc31 downloaded from the Fedora repository on Fedora 31.

# Steps to Reproduce
1. Create a file with an arbitary timestamp, e.g. `touch -t 01010100 time.md`
2. Verify the file's modification time using `ls -l` (Jan 1 01:00 in previous example)
3. Open the file with Quilter, and then quit Quilter without making edits
## Expected Behaviour
`ls -l` should still show the file's timestamp as unchanged from previously, because no changes were made to the file.
## Actual Behaviour
`ls -l` reveals that file's timestamp has been changed to the time when Quilter is closed.

Having issues producing screencast, but I'm happy to provide any clarification or test in a different way.

**Comment by lainsce** [comment]
Quilter autosaves things when closing, this to prevent accidental non-saving of modifications, and that's why the modified time changed. I agree that it's aggressive, but it's for a good cause, because if it weren't made this way, people would close the program and lose progress.

**Comment by lainsce** [comment]
Fixed, albeit using my suggestion above.
