### ISSUE TITLE
Stalled machine due to excessive resource usage

### ISSUE THREAD

**Issue by samtuke** [lainsce/quilter#316]
Quilter 2.1.1 installed from Fedora 31 repositories, maxed out CPU usage and consumed around  800mb of memory, causing the machine to stall. This lasted for over 30 minutes until I managed to kill the process. Around 4 markdown documents were open in Quilter at the time, each of less than 80 lines in length.

Unfortunately I have no other logs or diagnostics from that occurrence.

**Comment by lainsce** [comment]
Must be some weird one-time bug, I can't test because I target elementary OS.
