### ISSUE TITLE
Unable to save new documents when escaped the first save 

### ISSUE THREAD

**Issue by fineous** [lainsce/quilter#317]
If I abort the first time I save a new file and then try to save it again later, the save dialog does not appear.

Also, how do I get the version? It's not in any menu I have been able to find and running com.github.lainsce.quilter --version does not print anything.

**Comment by lainsce** [comment]
I'll look into it; in the meantime, Ctrl+S to save.

**Comment by lainsce** [comment]
> If I abort the first time I save a new file and then try to save it again later, the save dialog does not appear.

If you are on the latest version on AppCenter, this shouldn't occur, I have already fixed this on an earlier version.

> Also, how do I get the version? It's not in any menu I have been able to find and running com.github.lainsce.quilter --version does not print anything.

Always check it on AppCenter, that is where you'll get the reliable information for this, or here on github on this repository, under the releases tab.
