### ISSUE TITLE
double setting for corrector

### ISSUE THREAD

**Issue by megatux** [lainsce/quilter#318]
"Activar el corrector ortográfico" is twice in the Extensions settings tab page:

![Captura de pantalla de 2020-03-01 00-10-31](https://user-images.githubusercontent.com/850020/75618849-77963500-5b52-11ea-8d3b-9e125dbf786f.png)

**Comment by lainsce** [comment]
Someone has translated things twice, one of those is "Enable code highlighting"

**Comment by lainsce** [comment]
Since I don't know the proper term for code highlighting in Spanish, I'll leave this to a spanish native to correct;
follow the instruction in the `po` folder here in this repo, and make a PR correcting this.
