### ISSUE TITLE
Consider pandoc superset of markdown

### ISSUE THREAD

**Issue by lf-araujo** [lainsce/quilter#32]
If possible, instead of using basic markdown, try supporting pandoc's superset with all the table and references syntax.

Thanks for the app.

**Comment by lainsce** [comment]
Will do!

Expect pandoc markdown in the next release! 👍

**Comment by lainsce** [comment]
By the way, what does Pandoc's Markdown superset support in terms of syntax?
Could you give me examples? 👍

**Comment by lainsce** [comment]
Any who, I added the supported markdown rules
of pandoc markdown in master.

**Comment by lf-araujo** [comment]
It supports cross references like

[Figure](/path/){#fig:number1} and then later on the text you could call
@fig:number1 and a internal reference is created.

2017-07-07 2:45 GMT+10:00 Lains <notifications@github.com>:

**Comment by moqmar** [comment]
First of all, this is a really nice project and I love the fact that it isn't written in Electron like every alternative ever! Unfortunately, Quilter is still not really suitable for writing longer documents with citations, footnotes, and so on - would it be possible to use pandoc for the preview (maybe with configurable extensions and command line parameters) and maybe adding Frontmatter and LaTeX formular support to the syntax highlighting? Take a look at this example file:

```markdown
---
title: Hello World
references:
- id: WatsonCrick1953
  author: [{family: Watson, given: J. D.}]
  title: 'Molecular structure of nucleic acids: a structure for deoxyribose nucleic acid'
---

# A new file
Hello World! This is a new file, built mainly for **testing** stuff. Does *highlighting* also work for $f_or_mu_la_s$?! Obviously not[^1], but at least for footnotes?!

Maybe we can use citations [@WatsonCrick1953]

[^1]: Hello World

Oh no, everything's broken in the preview!
```

When running it through `pandoc --from markdown --to html5 -o test.html --filter pandoc-citeproc test.md`, I get the following output:

![grafik](https://user-images.githubusercontent.com/5559994/56099171-bf47aa00-5f09-11e9-9ad6-ce04e900fda4.png)

The syntax highlighting in Quilter doesn't support formulas and YAML/Frontmatter (latter being a smaller problem), and the preview is just broken completely:

![grafik](https://user-images.githubusercontent.com/5559994/56099200-151c5200-5f0a-11e9-9285-2c5ef84d25ce.png)

![grafik](https://user-images.githubusercontent.com/5559994/56099202-1d748d00-5f0a-11e9-93d5-e2ba31995fa4.png)
