### ISSUE TITLE
RFE: port to gtksourceview-4

### ISSUE THREAD

**Issue by kloczek** [lainsce/quilter#322]
Yep it would be good to have it as gtksourceview-3.0 is already outdated.

**Comment by lainsce** [comment]
There, just updated to Gtksourceview 4

**Comment by kloczek** [comment]
Still no intention to port to Gtksourceview 4

I see that Debian provides Gtksourceview 4.

**Comment by lainsce** [comment]
It's on the PR, locking the issue.
