### ISSUE TITLE
Quilt Mono isn't mono when bold

### ISSUE THREAD

**Issue by Bronislas** [lainsce/quilter#323]
Hi,

I'm trying Quilter right now and I'm quite happy with it but, when I put a word between asterisks to make it looks bold, the word itself is bold in Quilter, and the Quilt Mono font does not appear to remain monospace when bold.

A screenshot might be clearer : 
![Capture d'écran du 2020-03-23 15 33 25](https://user-images.githubusercontent.com/34268533/77327560-b2d3f000-6d1b-11ea-8495-1db663f35571.jpeg)

**Comment by lainsce** [comment]
It is bold, it's just that Quilt Mono is fairly tiny bit thinner than most monospace fonts for readability.

Compare in your screenshot the thickness of the words China with Etats-Unis. Eytats-Unis is Quilt Mono when bold.

Hope I helped clarify. :)

**Comment by Bronislas** [comment]
Yeah, I understand what you mean, but the problem is the fact that when bold, Quilt Mono is larger than when it is regular, as you can see in the table's columns. Is there a way to :
1. Keep the same width whether bold or regular ?
2. Prevent Quilter to make the text bold when between asterisks ?

**Comment by lainsce** [comment]
1. I can't, because a font being bold gains a bit more width, whether I like it or not.
2. That would defeat the purpose of a markdown editor now, wouldn't it? :)
