### ISSUE TITLE
Change requested for AppCenter: Better detail release details

### ISSUE THREAD

**Issue by cassidyjames** [lainsce/quilter#324]
Thanks for submitting your 2.2.1 update to AppCenter! However, while reviewing we noticed that your latest release changes are not descriptive, and don't tell users what actually changed. We want to avoid the trap of all apps ending up saying, "Bug fixes and performance updates," so we [ask developers](https://github.com/elementary/houston/wiki/Publishing-Updates#release-descriptions) to be more specific.

Please address these changes and publish a new release (i.e. 2.2.2). The new release's AppData description can include the cumulative change description since 2.2.1 will never have been released to users.

**Comment by lainsce** [comment]
But it's real minor changes, can't really detail without sounding like "uh duh?".
