### ISSUE TITLE
Export to pdf does not work in Spanish

### ISSUE THREAD

**Issue by McJaben** [lainsce/quilter#325]
## Hello, I have an error with the "export to pdf" function.

I didn't had any problem until now. When I try to export some text to PDF it only shows a blank file (0 bytes). I do not know how to make it work.
I am on 2.2.2 version of Quilter.  

   `Some screenshots of the problem https://ibb.co/C7XSPBR https://ibb.co/WxVC2fb`

Thanks! It is a great app, I like it very much. Just wanted to report this issue because I care about this project.

**Comment by lainsce** [comment]
Due to these PDF strings linked below not being translated, PDF export will not work due to being synced to the system's language; if the strings aren't translated, it confuses the exporter.

https://github.com/lainsce/quilter/blob/master/po/es.po#L461

**Comment by lainsce** [comment]
Can't help with this bug myself since it needs translations.

**Comment by shtonchjo** [comment]
I logged into another account where the interface is in English and Export To PDF works.

**Comment by lainsce** [comment]
If someone is available for translating the strings linked above, more people can enjoy using the Export function :)

**Comment by lainsce** [comment]
This might be fixed in the next version. Open a bug again if not.
