### ISSUE TITLE
Crash when clicking preview and not properly opening document

### ISSUE THREAD

**Issue by Fatih20** [lainsce/quilter#326]
I opened quilter . By default, the app will open will launch with the last opened document. For this instance, I wanted to make a new document tho, so I acted accordingly. Made a new document and saved it. I then typed some things in it and wanted to look at it's preview. Whoops! The app just crashed. I opened the app again, but it opened the previous files instead the new one I just made before the crash.

I'm using 2.2.2 downloaded from the appcenter.

Here's the video of the crash
https://open.lbry.com/@Fatih109:4/Screen-record-from-2020-04-06-09.56.36:d?r=7YWrkr8hJMjm8335kNGjStx3D2ZoNEHm
https://open.lbry.com/Screen-record-from-2020-04-06-09.51.17:9?r=7YWrkr8hJMjm8335kNGjStx3D2ZoNEHm

Thanks! I really liked this apps for working on my assignment and would love to have this sorted out.

**Comment by lainsce** [comment]
Let's work through this together;

Have you cleaned up the sidebar before opening that document with the `A.`?
(That's to make things less random for me.)

**Comment by Fatih20** [comment]
No. As you can see from the video, after opening the app, I instantly made a new document and saved it.

**Comment by lainsce** [comment]
Please have a clean Quilter session:

- Open up Dconf Editor,
- Go to com > github > lainsce
- Right click on quilter and set Reset Recursively
- Click on the checkmark on the statusbar that appears
- Then, try to do that again, if it crashes again, then I'll think of what it could be.

**Comment by Fatih20** [comment]
No, it doesn't happen now.

**Comment by lainsce** [comment]
Then the bug is fixed. Closing...

(If these seemingly random things happen again, reset your session as above and you're golden.)

**Comment by Fatih20** [comment]
Ok, thanks.

**Comment by Fatih20** [comment]
It happened again, is there no permanent solution other than continuously babysitting this app?

**Comment by lainsce** [comment]
I'll look into it.

**Comment by Fatih20** [comment]
I also found that when Quilter behave like this it's also painfully slow when copying and pasting large (>1000) block of text when otherwise there are no delays. I tried to do that and it took 5 minutes to paste that large block of text before doing the steps you've mentioned.

**Comment by lainsce** [comment]
Well, the processing to make preview updates with every change so if you give it a lot of text at once (but not opening a large document, there's a difference) it's bound to lag; I can't change that.

**Comment by Fatih20** [comment]
> Well, the processing to make preview updates with every change so if you give it a lot of text at once (but not opening a large document, there's a difference) it's bound to lag; I can't change that.

The problem here is that it doesn't. It only does before I did the steps you've mentioned.

**Comment by lainsce** [comment]
That's not happening here on my copy of it from the repository. It updates gracefully with every change. But if I give it a big paste, it'll lag and that's where I can't change it.

**Comment by Fatih20** [comment]
I'm using the appcenter version.

**Comment by lainsce** [comment]
AppCenter version should be the same unless something happened and you're using an older version.

**Comment by Fatih20** [comment]
The crashing is gone after I did this.

> Please have a clean Quilter session:
> 
>     * Open up Dconf Editor, (`sudo apt install dconf-editor` if you don't have it)
> 
>     * Go to com > github > lainsce
> 
>     * Right click on quilter and set Reset Recursively
> 
>     * Click on the checkmark on the statusbar that appears
> 
>     * Then, try to do that again, if it crashes again, then I'll think of what it could be.

But I had happened again and I need to redo the steps.

**Comment by lainsce** [comment]
If you can't help me I can't help you.

Closing bug due to insufficient bug tracing due to lack of a minimal document that showcases the bug as issued.
