### ISSUE TITLE
Check Contrast on things in Dark Mode

### ISSUE THREAD

**Issue by jfgordon2** [lainsce/quilter#327]
1. Dark mode is too dark, hiding the buttons that would otherwise be present in the other themes
2. Child windows spawned from this application don't respect system-wide light/dark theme preferences, instead spawning a dark filechooser when the dark theme is selected, and a light-themed filechooser when the other themes are selected 
(this can be visually obstructive when a GTK theme is tailored specifically for light or dark for some users)

### Issue 1
My suggestion for `1` is to just adopt a lighter background color for the dark theme, like in 
Elementary OS's upcoming dark theme

*Changing `background-color: #111111;` to `background-color: #393939;`*
![image](https://user-images.githubusercontent.com/55799997/78597809-c9963e80-7813-11ea-85ba-81e6658107fb.png)

### Issue 2
My guess for `2` is that gtk's prefer dark theme is explicitly defined per theme:
`Gtk.Settings.get_default ().gtk_application_prefer_dark_theme = false;`
In the source view file:
https://github.com/lainsce/quilter/blob/master/src/Widgets/SourceView.vala#L299-L330

My suggestion might be to just remove those lines and let it adopt the application user's preferences.

**Comment by lainsce** [comment]
1. What buttons? Also the dark theme is made for times where you want to type in low-light conditions, so going bright isn't ideal.
2. Any of my apps are not tailored to other themes. Quilter does what it should do, not have a blaring white filechooser on dark theme, and vice-versa, it would just feel wrong. Also, there's going to be an elementary OS `prefer-dark` key for the whole os and I'm going to rework around that.

It's a non-issue.

**Comment by jfgordon2** [comment]
@lainsce I respect that might be why you use the dark theme, but I think some other people have preference or accessibility reasons for why they use dark themes.

As far as the buttons:

The dark theme as it's currently written makes these blend with the rest of the UI:
![image](https://user-images.githubusercontent.com/55799997/78617957-b2b91180-783e-11ea-8cb8-c5b0c27ab9ff.png)
![image](https://user-images.githubusercontent.com/55799997/78617981-c3698780-783e-11ea-8417-fe10524b589b.png)

vs either of the other two themes:
![image](https://user-images.githubusercontent.com/55799997/78618018-dbd9a200-783e-11ea-9792-fd57b1b0b9ec.png)
![image](https://user-images.githubusercontent.com/55799997/78618041-e7c56400-783e-11ea-8aa0-4695b00f2b36.png)

**Comment by lainsce** [comment]
I can fix those by making the pressed state lighter.

**Comment by jfgordon2** [comment]
@lainsce that sounds great - I can't see the unpressed state either, but that might be my monitor?  Either way, thanks for thinking through this to make this even more usable.

**Comment by lainsce** [comment]
At first I thought this was yet another "I'm using a custom theme why everything sucks dev?" but it actually contains some good insight :P

**Comment by lainsce** [comment]
Fixed in next version
