### ISSUE TITLE
Some characters mess up editor view

### ISSUE THREAD

**Issue by janxkoci** [lainsce/quilter#329]
I found that some characters can mess up with formatting in the editor view. In particular the `<` symbol is causing some trouble, see screenshot:

![Snímek z 2020-04-10 13-23-12](https://user-images.githubusercontent.com/19331850/78987605-ce6a3380-7b2e-11ea-85e8-a37d5163eca3.png)

**Comment by lainsce** [comment]
Yeah, I'm going to make my own Markdown edit view styling sometime in the future to combat this. It's not easy. It'll take some time.
