### ISSUE TITLE
Could not execute Vala compiler "valac"

### ISSUE THREAD

**Issue by nick87720z** [lainsce/quilter#33]
Simple "meson build" ends with this error.
As result, build dir is not recognized as build dir.
Problem is that valac executables are versioned on my system (i use gentoo).
In most packages, using cmake or autotools, valac may be specified (e.g. -DVALA_EXECUTABLE in cmake, or --vala-compiler / --valac in waf or autotools).

Can't there be same option too?
Creating shell alias valac=/usr/bin/valac-0.34 doesn't work there.

**Comment by lainsce** [comment]
Sorry!
But Quilter is made to build only on elementary OS.
If you want a port of it to run in Gentoo, you're more than welcome to fork it and do the necessary changes.
Just mention I'm the original author. 👍
