### ISSUE TITLE
Infinite preview scrolling

### ISSUE THREAD

**Issue by janxkoci** [lainsce/quilter#330]
I have a weird issue with preview - sometimes when I turn preview on, I see no text. After some time I found that there is a *lot* of scrolling area and my preview is scrolled all the way down (see the scroll indicator on the right in the screencast below). Now I can scroll up, but if I reach the top of the document, it resets the scrolling position back to bottom.

These two issues are not always connected - for example here I have a gif of only the scrolling issue, but I can see my text just fine when I switch to preview (i.e. it didn't open scrolled to bottom):

![quilter-infinite_preview](https://user-images.githubusercontent.com/19331850/78988169-746a6d80-7b30-11ea-93af-2c30129590b6.gif)

However if the scrolling issue gets fixed, the other issue (when opening preview is scrolled all the way down) will disappear too.

**Comment by lainsce** [comment]
Sometimes, preview gets desynced with the edit view, and it's a limitation of the GTK/Sourceview used in the underlying repos, this was fixed in newer GTK/Sourceviews; and I'm waiting on elementary OS 6 to fix this.
