### ISSUE TITLE
Linux: middle-click not pasting

### ISSUE THREAD

**Issue by shtonchjo** [lainsce/quilter#331]
Hi! On Linux the middle-click normally allows to paste unformatted text from a special clipboard. This only works within Quilter when the selection remains, not when the text is unselected. 

![animated](https://user-images.githubusercontent.com/4954965/78990104-daa5bf00-7b35-11ea-96c3-50d0691520d4.gif)

Thanks!

**Comment by lainsce** [comment]
I believe this was a change in elementary OS system-wide; I can't also do the middle-click paste in other text apps.
