### ISSUE TITLE
Cannot commit (?) translation

### ISSUE THREAD

**Issue by shtonchjo** [lainsce/quilter#332]
Hi,
I must be missing some knowledge of Github... I followed the readme for submitting transations : I pulled the files from Github, created the po files (in root and in extra) editing with poedit, git config'd my email and password, at the time of committing the changes I had some issues.

$ `git checkout -b "Translation eo` brings the git terminal
$ `git checkout -b "Translation eo"` tells `fatal: 'Translation eo' is not a valid branch name.`
$ `git checkout -b "eo"` works, lists my files - OK
$ `git add *` - OK
$ `git commit -m "Translated your app for Esperanto" && git push` brings `fatal: The current branch eo has no upstream branch.` - it tells me to execute: 
$ `To push the current branch and set the remote as upstream, use
    git push --set-upstream origin eo` which however brings :
`remote: Permission to lainsce/quilter.git denied to shtonchjo.
fatal: unable to access 'https://github.com/lainsce/quilter/': The requested URL returned error: 403`

--> how to submit my translation?

Thanks

**Comment by lainsce** [comment]
You're supposed to use the fork button here on GitHub, make your additions there, and then make a Pull Request with the additions so that it comes to me to review it.
(I should amend the guides... someday)

**Comment by shtonchjo** [comment]
OK, I just did the Pull Request (hope it works)
If you want, I can try to help (in the limits of what I can learn)
I don't know Vala, could learn, but I could work on maintenance, CSS, javascript

**Comment by lainsce** [comment]
If you feel you can help on anything in my apps, then you're free to do so! Dankon pro la traduko, btw :D
