### ISSUE TITLE
Quilter Unable to Render Large Documents?

### ISSUE THREAD

**Issue by Fatih20** [lainsce/quilter#334]
## Hello! If you found an error in this app, follow this template:
I use the version currently available on elementary appcenter.

https://open.lbry.com/Screen-record-from-2020-04-20-21.14.20:b?r=Cg1pp5MCWV1a5Nj5jDumPs9b13dNZqWG
Quilter has an elegant scrolling behaviour in Focus mode. But, it's (kinda) frustrating to use when you're trying to select a segment of text. The scrolling behaviour itself is great and unique, but made it hard to select a segment of text. I know that you can just use shift to select from point A to point B, but still.

Thankss!

**Comment by lainsce** [comment]
It's working as intended, you don't do big selections while on Focus Mode; it's meant for you to just click to the top or bottom to get where you want and then select text there in that part; not the whole document manually.
