### ISSUE TITLE
Sidebar close button always closes current open file

### ISSUE THREAD

**Issue by mcclurgm** [lainsce/quilter#336]
The sidebar in Quilter consistently closes the wrong file when I click on the close (X) button. I believe this is because it always closes the current active file, even if I click on the close box on another file.

To reproduce: 
1. Open Quilter (preferably with no documents)
2. Create a new file and write something in it. Save it (to make this obvious, call it `doc1.md`).
3. Create another new file and save it with a different name (like `doc2.md`).
4. Select `doc2.md` in the sidebar like you're about to write something in it. Make it the active file.
5. Click the close button on `doc1.md`.
6. `doc2.md` will close, leaving `doc1.md` open.

The expected behavior is that when I click the close button on `doc1.md`, it will be closed, not `doc2`.

I compiled from source on May 5. The current release is 2.2.4, so I assume this is on its way to 2.2.5.

**Comment by lainsce** [comment]
Yeah, this is something I did to prevent document loss, only the selected (and thus saved) document is closeable; I intend to hide the close button on the non-selected documents to help not confuse.

**Comment by lainsce** [comment]
Fixed in #338
