### ISSUE TITLE
1.1.8 Core Dump on startup

### ISSUE THREAD

**Issue by CodeManS99** [lainsce/quilter#34]
This time it crashed before the window even appeared.

 `com.github.lainsce.quilter
[INFO 21:12:14.922016] Application.vala:153: Quilter version: 1.1.8
[INFO 21:12:14.922159] Application.vala:155: Kernel version: 4.8.0-58-generic
[WARNING 21:12:14.997697] [Gtk] Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name
[WARNING 21:12:14.997985] [Gtk] Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name
[WARNING 21:12:14.998309] [Gtk] Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
[ERROR 21:12:15.071378] [GLib-GIO] Settings schema 'com.github.lainsce.quilter' does not contain a key named 'window-maximized'
Trace/breakpoint trap (core dumped)`

**Comment by lainsce** [comment]
My suggestion is `sudo ninja uninstall`, then cleaning your build directory, then redoing the build process.
