### ISSUE TITLE
PDF export produces an empty file

### ISSUE THREAD

**Issue by stsdc** [lainsce/quilter#340]
When exporting to a .pdf, an empty file is created.
HTML export works fine.
Version 2.2.4

**Comment by lainsce** [comment]
PDF Export depends on if your System Language is set to one of the languages Quilter supports due to a string used which changes per language. In Quilter Next I'll look into not having this limitation.

**Comment by stsdc** [comment]
Thanks :+1: I was writing in polish and everything was red :grimacing:

**Comment by lainsce** [comment]
That also was fixed in Quilter Next, with an improved spellchecker :P
