### ISSUE TITLE
Interface not readable when using OS with dark theme

### ISSUE THREAD

**Issue by GiulioCentorame** [lainsce/quilter#341]
OS: Linux Manjaro xfce (Adapta Maia theme)
Quilter 2.2.4-1 (from [AUR](https://aur.archlinux.org/packages/quilter) )

Hello hello, thank you for this fantastic program! 
I found that when using the light and sepia themes on my os, the upper portion of the UI is almost unreadable, whereas it's fine with the dark theme.

Here are some screenshots:
![Dark theme](https://imgur.com/7OjzUeK.png)
![Light theme](https://imgur.com/ZvsUeUU.png)
![Sepia theme](https://imgur.com/OIi4MBi.png)

**Comment by lainsce** [comment]
If you're using a custom theme, that's what happens. I can't fix this, you're on your own.

**Comment by GiulioCentorame** [comment]
Right, but it's the same with the default theme:
![https://imgur.com/iYmFtS0.png](https://imgur.com/iYmFtS0.png)

**Comment by lainsce** [comment]
That's still not the default theme Quilter was built upon, which is elementary's.
