### ISSUE TITLE
It does not start the app

### ISSUE THREAD

**Issue by tomaswarynyca** [lainsce/quilter#344]
Hello, good, I installed the app from the store used it a couple of times and now does not start more, any idea that may be? The process runs on the system monitor. Thanks

**Comment by lainsce** [comment]
Can you detail what you were doing to make this happen? Steps to have it happen would be helpful for me.
Also, there's the version 2.5.0 coming soon that might help in solving this.

**Comment by tomaswarynyca** [comment]
Thanks for responding, I was in the configuration menu to disable the spell checker, I closed the application and did not start it anymore. Compile the version from the github and I don't start either.
If I saw that you were developing a new version, I wanted to compile it but I am missing some dependencies that I am trying to install in ElementaryOS.

**Comment by lainsce** [comment]
Can you try this (found in another issue):

"So I tried installing Dconf editor to see if there is some messed up setting - and there was! The language set for Quilter spell check was set to 'All_Upper Case' - changing it to 'en_GB' fixed the issue and spell check now works on both laptops."

**Comment by tomaswarynyca** [comment]
I just installed Dconf editor, opened the quilter configuration and now it opened without problems. Thanks bro!

**Comment by lainsce** [comment]
Closing the issue then!
