### ISSUE TITLE
Switches to Edit view when changing Preview font

### ISSUE THREAD

**Issue by cassidyjames** [lainsce/quilter#345]
Pretty minor, but annoying.

![Peek 2020-08-28 09-51](https://user-images.githubusercontent.com/611168/91587476-0faf8400-e914-11ea-92fe-7d3fd9239897.gif)

**Comment by lainsce** [comment]
Yeah, this is why I removed this in the headerbar in 3.0 to be on settings dialog instead...
Having 3.0 stalled from being to the public due to LibHandy is quite hard to maintain to backport things...
