### ISSUE TITLE
Error converting equation in latex to markdown

### ISSUE THREAD

**Issue by anhkhoado93** [lainsce/quilter#346]
Latex inline equation and equation block get mixed up with markdown syntax. 
Example: The following line: \\(\sum_{n=1}^{\infty} 2^n\\) . This prints:
 `![math equation](https://drive.google.com/file/d/1Ad4L7aBulg8PA8I28jiFnAAxDL3TZmSw/view?usp=sharing)`
The ^{\infty} 2^ was superscripted rather than printing the math equation (in latex). I'm using version 2.5.1. Sorry if I am mistaken, I am new to markdown.

**Comment by lainsce** [comment]
Always encase your LaTeX code in `$$...$$` for an equation block, and `\(...\)` for inline. Check also that the LaTeX extension is on in the settings.

**Comment by anhkhoado93** [comment]
Sorry, I dont think I described it clearly. The latex code was encased in \\(...\\), and LaTeX extension is on in Setting. The problem is that Quilter would take this line of code:  \( \sum_{n=1}^{\infty} 2^n \) , where the "\sum_{subscript}^{superscript}" syntax would print the  [summation notation](http://www.columbia.edu/itc/sipa/math/summation.html) and 2^n would superscript the letter 'n' (in LaTeX). 
However, Quilter mistook this notation and superscripted the text between two caret symbol '^'.

**Comment by lainsce** [comment]
Oh, I see. Well, collisions like this are common when mixing Markdown and LaTeX, and I think the solution is to use a function in LaTeX that _looks_ like a superscript for now.

**Comment by johnblommers** [comment]
This issue should remain open because the problem is not resolved. Other LaTeX expressions fail to render properly, for example with Quilter 3.3.0:

![Screenshot from 2021-02-12 19-01-17](https://user-images.githubusercontent.com/8484427/107840157-49ab0000-6d65-11eb-9824-39999a5d6bd9.png)
