### ISSUE TITLE
Quilter wiping progress, not deleting entries in tabs

### ISSUE THREAD

**Issue by mxkew** [lainsce/quilter#348]
Hi, I'm on v 2.5.2. I just recently discovered that, although I ctrl + s my files religiously, quilter has discarded all but the beginning 2 lines of my past 4 log entries, each comprised of about 500 words or so. All the progress was lost, despite appearing as if it was saved on exit. In addition to this, clicking the 'x' on the tabs of open projects does nothing but make the program hang for a few seconds.

I love this project and I hope this issue gets remedied quickly so I can continue using it without fear of losing all my markdown files.

**Comment by lainsce** [comment]
Can you show the output on Terminal while this happens?

Other than that, it may be a disconnect between the internal settings carried over from older versions. Try wiping the settings by downloading Dconf Editor, navigationg to com/github/lainsce and right-clicking on  quilter and selecting Reset recursively and then the little checkmark button. After all that, check if it does this bug again.

**Comment by lainsce** [comment]
@mxkew If you can't help me with those things above, I won't be able to fix. :(

**Comment by mxkew** [comment]
How do I view the terminal output while using quilter?

**Comment by lainsce** [comment]
1. Open quilter in Terminal by typing in `com.github.lainsce.quilter`
2. Do your things as usual
3. If the app crashes or does the bug you said it does, ctrl+c in the terminal to stop Quilter from running
4. Copy all the output since starting quilter here.

**Comment by mxkew** [comment]
** (com.github.lainsce.quilter:5092): WARNING **: 23:32:02.297: SideBar.vala:132: Unexpected error during selection: Failed to open file “/home/dana/.local/share/com.github.lainsce.quilter/~2020-08-27T21:45:33-0400.md”: No such file or directory

This is what I get when hitting the 'x' on a file in the tabs to try and close it.

Upon further inspection, the bug seems a bit more complex than I first believed. There are a little over a dozen tabs open; I'll have two open for one file. For brevity's sake, I'll have saved it 09.02.2020.md. One tab will just say "New Document" and will contain all the data I'd previously believed Quilter wiped. The other will be listed as 09.02.2020.md, but it will only contain the first couple lines, like I mentioned in the initial report.

Could the terminal output have to do with the fact that I save my documents in a 'Documents' rather than .local/share/com.github.lainsce.quilter ?

Sorry if I came off a little brash in my first report

**Comment by lainsce** [comment]
Nah, you're fine.

This seems like it's using the older system of saving files, and it's corrupting on the new version because Quilter doesn't know anymore about that type of saving, opting for a better one.

I think if you follow my second advice in my reply above, it should not happen anymore:
`Other than that, it may be a disconnect between the internal settings carried over from older versions. Try wiping the settings by downloading Dconf Editor, navigating to com/github/lainsce and right-clicking on quilter and selecting Reset recursively and then the little checkmark button. After all that, check if it does this bug again.`

**Comment by mxkew** [comment]
Same issue! Installed dconf and went ahead through the steps you outlined. I wonder why this persists after recursive reset...

`** (com.github.lainsce.quilter:9903): WARNING **: 19:21:26.894: SideBar.vala:132: Unexpected error during selection: Failed to open file “/home/dana/.local/share/com.github.lainsce.quilter/~2020-09-13T19:21:26-0400.md”: No such file or directory
`

**Comment by lainsce** [comment]
Can you see if the directory `/home/dana/.local/share/com.github.lainsce.quilter` exists? If not, then it's actually a bug with the program not making that directory or something.

**Comment by mxkew** [comment]
Yup, the whole directory exists

**Comment by lainsce** [comment]
Hmm, then I don't know what's happening then. I've tested locally, switching between documents, inserting cyrillic text (my test to see if saving something other than latin works) and etc. and it all works flawlessly.

I'll need a video made with a screen recorder... That should help me pinpoint where it goes wrong.

**Comment by mxkew** [comment]
Is there an email or something you would like me to send that to? 

Sorry for the late response, I've been swamped lately

**Comment by lainsce** [comment]
You can drag the video here in GitHub to the comment box, and it'll inline upload it.

**Comment by lainsce** [comment]
@mxkew It's been 10 days... I'll assume you got it working.
