### ISSUE TITLE
Allow scrolling the document's page below the text.

### ISSUE THREAD

**Issue by razmarques** [lainsce/quilter#349]
I would like to suggest a feature for a future release, that is, to allow scrolling the blank space below the last line of text. The idea is to keep the text flow in the centre of the document and forcing the writing focus in the centre of the document rather than the bottom, as it feels more balanced and pleasing when writing.

Currently using version 2.5.1

Cheers!

**Comment by lainsce** [comment]
You can activate this with Typewriter Scrolling for the Focus Mode. :smile: 

/closing

**Comment by razmarques** [comment]
Thanks for the tip!
