### ISSUE TITLE
Custom fonts don't apply in Focus Mode

### ISSUE THREAD

**Issue by MrHuds0n** [lainsce/quilter#35]
When going to Focus Mode all text is shown in the default monospace font.

**Comment by lainsce** [comment]
That's by design, the focus mode is tailored to be well, focused. No custom fonts in that mode.

**Comment by MrHuds0n** [comment]
As far as I understand focus mode is supposed to be just for highlighting the current sentence/paragraph (at least that's what it is in other editors such as Typora). If so, then I have to question this decision considering the default font is monospace which is not entirely suited for writing... anything really, other than code.

**Comment by lainsce** [comment]
You'll understand why it is monospace once I finalize the Preview Mode.
In Preview Mode, it'll have serif fonts suited for reading your story, not this monospace in the Edit View.
