### ISSUE TITLE
[Quilter Next] Search should look more like Code's

### ISSUE THREAD

**Issue by hanaral** [lainsce/quilter#352]
The current search drop down looks a bit odd, and doesn't quite make sense for the amount of horizontal space it has
Current:
![Screenshot from 2020-11-17 11-06-39](https://user-images.githubusercontent.com/58219504/99383215-7619c200-28c5-11eb-9f0c-88efe9ed2a94.png)

What it could look similar to:
![Screenshot from 2020-11-17 11-07-08](https://user-images.githubusercontent.com/58219504/99383241-7f0a9380-28c5-11eb-9b18-14c63755abcb.png)

**Comment by lainsce** [comment]
This is by design, to fit things in small displays like mobile phones or small laptops. Not a bug. 😅
