### ISSUE TITLE
The "Remove File from Sidebar" action doesn't do anything

### ISSUE THREAD

**Issue by volfpeter** [lainsce/quilter#354]
Hi,

I'm trying out Quilter, it looks really nice, but I'm having the issue I described in the title (on an up-to-date elementary OS 5 with the latest version of Quilter installed from AppCenter).

Steps to reproduce the problem:
- Click the "New file" button a couple of times to create a couple of empty files.
- Click the "Remove File from Sidebar" icon in the renderer of one of the created files.

Result: the file remains in the sidebar.
Expected result: the file is removed from the sidebar. 

Thanks!

**Comment by lainsce** [comment]
If a file is not selected in the Sidebar, the button will not do anything, I wonder why the button is showing if the file isn't selected.

**Comment by volfpeter** [comment]
Well, just tried select then remove and as I can see the button doesn't work regardless of whether the file is selected or not.

**Comment by lainsce** [comment]
I'll look into this, and issue a minor fix update.

**Comment by lainsce** [comment]
Fixed, await the release soon.

**Comment by volfpeter** [comment]
If nobody else complains about it, feel free to the fix only in 3.0! I image that would spare a fair bit of time for you. It's not urgent for me.

**Comment by lainsce** [comment]
Nah, I issued a release 2.5.2 for this, since it could affect more than you. 😃

**Comment by volfpeter** [comment]
Thanks, it was super quick!
All the best!
