### ISSUE TITLE
Elementary OS App Center is still distributing v5.2.1

### ISSUE THREAD

**Issue by nukoka-amaru** [lainsce/quilter#359]
I was having an issue removing files from the sidebar just as in Issue #354 . I updated my repos and tried reinstalling to install the current version but the App Center instead installed v5.2.1 again. It seems to me that the current version needs to be pushed to the App Center for distribution.

#### System Information
* eOS v5.1.7 Hera

**Comment by lainsce** [comment]
Nothing I can do, I can't push releases somehow to AppCenter anymore.

**Comment by nukoka-amaru** [comment]
Thanks for the heads up @lainsce I wasn't sure how the App Store functioned.

**Comment by lainsce** [comment]
Anyways, newer Quilter versions are now going to be up on Flathub.

https://flathub.org/apps/details/io.github.lainsce.Quilter
