### ISSUE TITLE
The header bar flashes on resize when the filename is too large to be shown on the header bar

### ISSUE THREAD

**Issue by nahuelwexd** [lainsce/quilter#362]
I recently installed the app from Flathub, and when I click the "New document" button, I get the editor in the narrow mode, and if I try to resize it, the header bar start flashing and changing between two modes. I noticed it happens 'cause the default filename is too large. If I save the file with a shorter name and open it again, the issue is fixed.

Version: 3.0.0 (from Flathub)

I attach a screencast.

https://user-images.githubusercontent.com/18204745/105620167-a22b5500-5dd8-11eb-800c-a98451673b4c.mp4

**Comment by lainsce** [comment]
Fixed, next version (3.1.2) should have the fix.
