### ISSUE TITLE
Version number in about dialogue not correct

### ISSUE THREAD

**Issue by lightonflux** [lainsce/quilter#364]
Just loaded the newest version from Flatpak. And checked the about dialog.  The version reported by the app and flatpak are different. 

![Bildschirmfoto von 2021-01-24 15-38-19](https://user-images.githubusercontent.com/1377943/105633694-61742000-5e5a-11eb-8d88-ba62517d5093.png)

**Comment by lainsce** [comment]
Oops, guess I forgot to update this on the build file. My bad. Easily fixable.
