### ISSUE TITLE
UI is endlessly rearranging

### ISSUE THREAD

**Issue by lightonflux** [lainsce/quilter#365]
Using the newest version from flathub. 3.1.2 on Fedora 33.

Save this (exactly) as a file. Or add the lines to an existing file and make the window slowly smaller until you find the size that recreated this issue.

 I reduced a file with some references like this until i found this line is the issue:

```

1: https://www.youtube.com/watch?v=osdoLjUNFnA (5 Minuten)
```
Not sure if this is a libhandy issue. But it happens both with x and wayland. 

https://user-images.githubusercontent.com/1377943/105634367-f6c4e380-5e5d-11eb-8694-ade2a1572de6.mp4

**Comment by lainsce** [comment]
This is somewhat fixed to the extent that I can do in a newer version.
