### ISSUE TITLE
How to reset Quilter preferences

### ISSUE THREAD

**Issue by johnblommers** [lainsce/quilter#368]
With Quilter 3.0.0 it's gotten into full-screen mode and doesn't want to leave it. I cannot resize the window. It didn't do this when I first ran it.

So I would like to try resetting the preferences. I cannot find the preferences file. So where does Quilter keep its preferences file? Will deleting that file reset Quilter to defaults?

**Comment by lainsce** [comment]
You couldn't leave it after pressing F11 again while fullscreened?

**Comment by lainsce** [comment]
Also, check out your Quilter install because it will be at 3.1.5 soon, not 3.0.0.
