### ISSUE TITLE
Can't close files in sidebar

### ISSUE THREAD

**Issue by bertob** [lainsce/quilter#369]
Clicking close buttons here does nothing for me:

![image](https://user-images.githubusercontent.com/1908896/106762342-08647300-6636-11eb-8e1e-c794ea59de9c.png)

Fedora 33, latest version from Flathub

**Comment by lainsce** [comment]
Oh, yeah. Of course it wouldn't do anything, it's under a stray if. :joy: 

I'll fix this.
