### ISSUE TITLE
Crashes during inactivity

### ISSUE THREAD

**Issue by MrHuds0n** [lainsce/quilter#37]
```
[INFO 15:39:12.726500] Application.vala:153: Quilter version: 1.1.9
[INFO 15:39:12.726562] Application.vala:155: Kernel version: 4.4.0-83-generic
[FATAL 15:39:12.835451] [GLib-GObject] g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[FATAL 15:39:12.835475] [GLib-GObject] g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[FATAL 15:39:12.835488] [GLib-GObject] g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[FATAL 15:39:12.835514] [GLib-GObject] g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[FATAL 15:39:12.835525] [GLib-GObject] g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[ERROR 15:41:12.715102] FileUtils.vala:110: Error: Error removing file: Permission denied
[1]    9866 trace trap (core dumped)  com.github.lainsce.quilter
```

**Comment by CodeManS99** [comment]
I think this is the same error.

`com.github.lainsce.quilter %U
[INFO 14:04:28.511124] Application.vala:153: Quilter version: 1.1.9
[INFO 14:04:28.511212] Application.vala:155: Kernel version: 4.8.0-58-generic
[WARNING 14:04:28.589137] [Gtk] Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name
[WARNING 14:04:28.589326] [Gtk] Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name
[WARNING 14:04:28.589495] [Gtk] Theme parsi`

**Comment by CodeManS99** [comment]
I think this may be the same error.
`com.github.lainsce.quilter %U
[INFO 14:04:28.511124] Application.vala:153: Quilter version: 1.1.9
[INFO 14:04:28.511212] Application.vala:155: Kernel version: 4.8.0-58-generic
[WARNING 14:04:28.589137] [Gtk] Theme parsing error: gtk-widgets.css:2045:14: 'min-height' is not a valid property name
[WARNING 14:04:28.589326] [Gtk] Theme parsing error: gtk-widgets.css:2046:13: 'min-width' is not a valid property name
[WARNING 14:04:28.589495] [Gtk] Theme parsing error: gtk-widgets.css:2051:13: 'min-width' is not a valid property name
[FATAL 14:04:28.846456] [GLib-GObject] g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[FATAL 14:04:28.846540] [GLib-GIO] g_file_get_child: assertion 'G_IS_FILE (file)' failed
[FATAL 14:04:28.846629] granite_services_paths_ensure_directory_exists: assertion 'dir != NULL' failed
[FATAL 14:04:28.846711] granite_services_paths_ensure_directory_exists: assertion 'dir != NULL' failed
[FATAL 14:04:28.846770] [GLib-GIO] g_file_get_child: assertion 'G_IS_FILE (file)' failed
[FATAL 14:04:28.846830] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:28.846891] [GLib-GIO] g_file_create: assertion 'G_IS_FILE (file)' failed
[FATAL 14:04:28.846948] [GLib-GIO] g_file_get_path: assertion 'G_IS_FILE (file)' failed
[FATAL 14:04:28.847005] [GLib] g_file_get_contents: assertion 'filename != NULL' failed
[FATAL 14:04:28.847074] [Gtk] gtk_text_buffer_set_text: assertion 'text != NULL' failed
[FATAL 14:04:28.847141] [GLib-GObject] g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[FATAL 14:04:28.997460] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:28.997660] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:35.225890] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:35.226173] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:35.588575] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:35.588735] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:35.845698] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:35.845998] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:36.080850] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:36.081147] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:36.566839] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:36.567119] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:36.917381] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:36.917664] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:38.443955] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:38.444239] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:38.974757] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:38.975043] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:39.584889] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:39.585170] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:42.614105] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:42.614482] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:43.037210] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:43.037449] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:43.339519] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:43.339801] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:43.701263] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:43.701548] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:43.962881] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:43.963176] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:44.489816] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:44.490104] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:44.848806] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:44.849033] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:45.513641] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:45.513919] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:46.269208] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:46.269490] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:47.249898] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:47.250178] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:47.782477] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:47.782759] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:53.828575] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:53.828865] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:54.176878] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:54.177124] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:54.394081] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:54.394441] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:54.677102] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:54.677393] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:54.809989] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:54.810142] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:55.388320] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:55.388608] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:55.690998] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:55.691281] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:56.016251] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:56.016534] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:56.561752] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:56.562034] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:56.971519] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:56.971802] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:57.237734] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:57.238019] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:57.595416] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:57.595702] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:57.932449] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:57.932734] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:58.178019] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:58.178436] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:58.376469] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:58.376754] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:58.811606] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:58.811893] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:04:59.695539] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:04:59.695821] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:38.888397] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:38.888687] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:40.102965] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:40.103255] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:40.478374] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:40.478663] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:40.787686] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:40.787977] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:41.145586] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:41.145869] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:41.430956] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:41.431243] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:41.729279] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:41.729567] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:42.066147] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:42.066531] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:42.304199] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:42.304492] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:42.705200] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:42.705496] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:42.963970] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:42.964263] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:43.259132] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:43.259423] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:43.536611] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:43.536785] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:44.074166] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:44.074567] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:44.355876] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:44.356169] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:44.634015] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:44.634446] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:45.034177] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:45.034645] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:45.432841] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:45.433136] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:45.712222] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:45.712516] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:46.120336] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:46.120629] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:46.581052] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:46.581338] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:46.839331] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:46.839622] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:47.183836] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:47.184127] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:47.537626] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:47.537911] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:47.779603] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:47.779890] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:48.019881] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:48.020170] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:48.270739] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:48.271023] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:48.538676] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:48.538967] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:48.970068] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:48.970481] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:49.178134] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:49.178519] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:49.525762] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:49.526047] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:49.755540] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:49.755828] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:50.223088] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:50.223375] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:50.543472] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:50.543757] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:50.843124] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:50.843412] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:51.163288] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:51.163574] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:51.498345] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:51.498631] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:51.956133] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:51.956425] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:52.238016] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:52.238427] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:52.526297] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:52.526590] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:52.788518] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:52.788808] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:53.123848] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:53.124135] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:53.547501] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:53.547792] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:54.989013] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:54.989302] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:55.404197] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:55.404490] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:55.725386] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:55.725680] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:55.969470] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:55.969611] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:05:58.235059] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:05:58.235354] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:06:22.012191] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:06:22.012480] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:06:22.510885] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:06:22.511080] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:06:22.902742] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:06:22.903031] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:06:23.170086] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:06:23.170490] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:06:23.532434] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:06:23.532730] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:06:23.827336] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:06:23.827622] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:06:24.224721] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:06:24.225021] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:06:24.507319] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:06:24.507619] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:06:24.822463] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:06:24.822751] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:06:25.614189] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:06:25.614593] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:06:26.034649] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:06:26.034943] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:06:26.487660] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:06:26.487947] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:06:27.042876] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:06:27.043161] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:06:27.663366] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:06:27.663937] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[FATAL 14:06:29.420922] [GLib-GIO] g_file_query_exists: assertion 'G_IS_FILE(file)' failed
[FATAL 14:06:29.421213] quilter_utils_file_utils_save_file: assertion 'file != NULL' failed
[ERROR 14:06:29.615293] FileUtils.vala:110: Error: Error removing file: Directory not empty
Trace/breakpoint trap (core dumped)`

**Comment by lainsce** [comment]
That's odd. It should be saving the file in the background.
I'll fix it soon.

**Comment by lainsce** [comment]
Ok, I've tested the current app on all sides, and in all ways you'd interact with it, and I didn't find this problem. 😞

**Comment by alisonbnt** [comment]
+1 here

The app suddenly closes after a few minutes.

**Comment by lainsce** [comment]
OH

Found the source of the problem!

Will fix it as soon as possible. *facepalm*

**Comment by alisonbnt** [comment]
Awesome! Glad you've found it!

**Comment by lainsce** [comment]
:tada: :tada: :tada: :tada:
IT'S FIXED, HOORAY!
:tada: :tada: :tada: :tada:
