### ISSUE TITLE
No way to show the sidebar at startup

### ISSUE THREAD

**Issue by bertob** [lainsce/quilter#370]
By default I don't get a sidebar or bottom bar on startup, so the only way to show the sidebar is to click the "new document button", which gets me to this state (from where I don't see a way to hide it again):

![image](https://user-images.githubusercontent.com/1908896/106762454-23cf7e00-6636-11eb-99f1-abf9c2451f9c.png)

As discussed on Matrix, perhaps removing the bottom bar and moving those controls to the top bar would be good anyway, and it'd fix this problem as a side-effect :)

**Comment by lainsce** [comment]
Actually this was something I overlooked. It's supposed to default to show, but hide if the user wants to. Fixing.

**Comment by lainsce** [comment]
Fixed.
