### ISSUE TITLE
Outline does not update

### ISSUE THREAD

**Issue by bertob** [lainsce/quilter#372]
When I start a new doucment and add some headers, they don't show up in the "outline" section (Which I assume they should?):

![image](https://user-images.githubusercontent.com/1908896/106763188-e0c1da80-6636-11eb-9a24-88279bee8db2.png)

**Comment by lainsce** [comment]
Fixing this. :)

**Comment by lainsce** [comment]
Fixed.

**Comment by bertob** [comment]
Are you sure this is is fixed? I just built master and it's still happening:

![image](https://user-images.githubusercontent.com/1908896/106818248-500bee80-6678-11eb-9279-3bfd172a851a.png)

**Comment by lainsce** [comment]
It takes a moment after you save the file somewhere.

Freshly new files made by the New Document button aren't files yet until you save them somewhere. :thinking:

**Comment by bertob** [comment]
That's a bit counterintuitive I assumed that the outline updates live as I add/remove titles.

**Comment by lainsce** [comment]
It does, but only with files that exist in the file system... I couldn't find a way to make it work with cache files :(

**Comment by bertob** [comment]
Maybe temporarily save them in the flatpak directory? Or does that not work either?

**Comment by lainsce** [comment]
That was the first thing I tried before just settling on new files are ephemeral on creation but after closing/saving Quilter they become real files.

Maybe I should hide outline until the file is saved, then show it?

**Comment by lainsce** [comment]
Also, lemme reopen this lol

**Comment by bertob** [comment]
> Maybe I should hide outline until the file is saved, then show it?

That sounds like it'd be suprising, but maybe worth a try if there's no other option

**Comment by lainsce** [comment]
> That sounds like it'd be suprising, but maybe worth a try if there's no other option

I've seen this happen on more complex apps where certain parts only show if needed.
Maybe it's even better than having dead UI lying around until some mysterious condition (for the user, at least) is met for it to start being alive.

**Comment by lainsce** [comment]
I just thought of a better way to make this work:

If the file is selected in the sidebar, show Outline for that file, otherwise, hide.

This might work for the cache files as well.

**Comment by lainsce** [comment]
Nevermind, I found out why it wasn't working; I wasn't calling the methods for the outline in the proper places on cache files' case. This is now actually fixed.
