### ISSUE TITLE
*** QUILTER: Function EXPORT TO PDF ***

### ISSUE THREAD

**Issue by JoanGitHubUser** [lainsce/quilter#377]
## Hello! If you found an error in this app, follow this template:

*** QUILTER: Function EXPORT TO PDF ***

* Describe the issue
   Perhaps I have a fault on my configuration or so, but the PDF have 0 bytes

* State what version you're using
  2.5.1
   
* Take a screenshot of the problem, then use the Markdown property for it:  
![Captura de pantalla de 2021-02-12 22-05-00@2x](https://user-images.githubusercontent.com/78983614/107822475-791a3680-6d7e-11eb-8db2-c953d1b57b37.png)

   
* If the problem needs it, show me a video of the problem with Screenkey running in the background.

Thanks!

**Comment by lainsce** [comment]
You're using Quilter in a language which Quilter wasn't translated for, so PDF will not work due to a certain button in the PDF dialog needing the translation to work properly.

**Comment by JoanGitHubUser** [comment]
Hi,

  I have changed the language to English and efectively, all works perfect. If I can contribute to translate your app, I am offer to it.

**Comment by lainsce** [comment]
Go ahead! Follow the instructions:
https://github.com/lainsce/quilter/blob/master/po/README.md

**Comment by JoanGitHubUser** [comment]
Hi,

  I have followed the instructions to commit the proposal of
translation of your app to Catalan ca.po, that I have finished
yesterday night.  Badly, the transaction do not do anything in the
terminal, and it's supposed 
that at certain point, from the terminal, the process demands por user
and password of GitHub.

  Perhaps, the folders in that I worked or saved de po are not the
correct ones, or I need more install process of Gid ?

  Actions taked :
  
   1. Cloned : git clone https://github.com/lainsce/quilter :


    2. Translation saved on po folder  -> ca.po :



  3. From the terminal in the aaTraduccions folder (not from the sub-
folder  \quilter) :


  4. The LINGUAS file already has the ca line for the language
translated, so I do not have added it to the last line

  And it stays here doing nothing more ...  If I make this orders from
the \quilter sub-folder the results are the same.

What am  I doing bad ?  

 Best regards,

    Joan

  

El dv. 12 de 02 de 2021 a les 14:11 -0800, en/na Lains va escriure:

**Comment by lainsce** [comment]
Oh, I have to update the instructions, I forgot to add a very important step, sorry!

1. Fork the repository here on github with the Fork button at the top-right
2. Clone that repository
3. The rest is the same as before.

**Comment by JoanGitHubUser** [comment]
Ok, I will try and see.

**Comment by JoanGitHubUser** [comment]
Hi !

   Sorry but no way :-(

   This time I have cloned my fork of your project :


  All the commands need to be executed on the /aaTraduccions Folder, or
on /aaTraduccions/quilter ? 

pd: attached the two files ca.po and ca.mo, in the case you directly
could fork them

El ds. 13 de 02 de 2021 a les 05:22 -0800, en/na Lains va escriure:

**Comment by lainsce** [comment]
>on /aaTraduccions/quilter

Yeah, on the folder it created when you git cloned it. :)

**Comment by JoanGitHubUser** [comment]
Hi,    I am a bit lost but I think the changes are commited and pushed.
 They are here :

 and here :


   Best regards,
       Joan  El ds. 13 de 02 de 2021 a les 10:58 -0800, en/na Lains va
escriure:

**Comment by lainsce** [comment]
I can't see those files... Could you open a Pull Request? That way your translation should be reviewed by me and merged so that it shows up on the release.
