### ISSUE TITLE
Quilter freezes up with large documents

### ISSUE THREAD

**Issue by johnblommers** [lainsce/quilter#378]
When opening a Markdown file with 60,000 words it  takes Quilter around a minute to load it all in. 

When you next enable the Highlight Speech Parts (Beta) it again freezes for about a minute. 

When you resize the windows again with the freezing. 

And when you enable the sidebar again a minute will pass.

Indeed the sytem may display "Quilter is not responding" under these conditions. You have to wait until it passes.

I'm running a 32-core Ryzen box with 128 GB RAM, a fast system running Pop!\_OS 20.10.

Please consider profiling the code to locate and tune where Quilter is slow.

**Comment by lainsce** [comment]
> Markdown file with 60,000 words

You might wanna consider using Quilter's built-in file embedding with a file that large;
Get the parts into files of their own, and then just use:

`/Folder/Document1.md :file`
`/Folder/Document2.md :file`
`/Folder/Document3.md :file`
`/Folder/Document4.md :file`

and so on.. to load the parts on the same folder in this main file.

**Comment by johnblommers** [comment]
Good point. I did not know that Quilter had file embedding. Thanks for the tip!
