### ISSUE TITLE
Feature request: render markdown in the Gsv part too

### ISSUE THREAD

**Issue by sp1ritCS** [lainsce/quilter#380]
If this goes against your vision of your App, feel free to close it.

Hi, I just found your App on Flathub, and it looks like a very promising Markdown writing application.
I already use [NoteKit](https://github.com/Blackhole89/notekit) for Note-taking. But unlike this, it only uses Gsv with a [modified markdown definition](https://github.com/blackhole89/notekit/blob/master/sourceview/markdown.lang) to ["render" Markdown](https://github.com/blackhole89/notekit/blob/cdca7e05f23506b3bfffa69e73b0d6a5bd97b839/notebook.cpp#L490) and [cLaTeXMath](https://github.com/NanoMichael/cLaTeXMath) to render LaTeX. It's quite convenient to write in it.

Would it be possible to have something similar in Quilter?

**Comment by lainsce** [comment]
Sorry, but what do you mean with "GSV"?

LaTeX in Quilter is powered by Katex, and it uses what's in the Markdown Cheatsheet in-app to show Katex, but only if enabled in the Preferences.

**Comment by sp1ritCS** [comment]
> Sorry, but what do you mean with "GSV"?

Gtksourceview

**Comment by lainsce** [comment]
Quilter has a different approach to this, it has a separate preview pane to show the result of the markdown, unlike Typora which just shows the result in one place.

**Comment by sp1ritCS** [comment]
> Notekit seems to do the same thing as Typora

yeah, seems similar

---

>  it just feels confusing for the user
I disagree, but fine.
