### ISSUE TITLE
Do you mind if the last elementary version's icon is used in Writer?

### ISSUE THREAD

**Issue by hanaral** [lainsce/quilter#384]
Hi - I'm well aware of what's happening to the project, but I think it would be a waste since [Writer](https://github.com/ryonakano/writer) doesn't have one...

**Comment by lainsce** [comment]
I don't think it would fit it 100%, because Writer's a word processor and Quilter was a markdown editor and the icon metaphor of these two ideas is quite different. You could edit it to suit Writer, though.

**Comment by hanaral** [comment]
I was planning on using it as a baseline to make something that looks like Pages or TextEdit - I'll go ahead then if you haven't any objections!
