### ISSUE TITLE
can't save files

### ISSUE THREAD

**Issue by mjourdan** [lainsce/quilter#385]
Quilter 3.3.0 installed from Flatpak.

Click the save icon, select either "save" or "save as", nothing happens. Ctrl+S doens't seem to work either. Document is still marked as "not saved yet".

I tried again with autosave disabled, same.

**Comment by lainsce** [comment]
Quilter has stopped development, to merge with Apostrophe, I advise to use Apostrophe. 🙂

**Comment by mjourdan** [comment]
Oh! Quilter UI was really appealing to me and felt like it could be a good replacement for Notes Up. Maybe I'll give an other try to Apostrophe then, or wait for GNOME Notes. Still it's nice to see separate projects joining their forces. Thank you @lainsce
