### ISSUE TITLE
Change default save location

### ISSUE THREAD

**Issue by SilverMarcs** [lainsce/quilter#388]
I know development has shifted but I really like the aesthetics of the latest flatpakversion.

How do i choose where to save files? I am okay with overriding home directory permission of flatpak so that isnt an issue.

**Comment by lainsce** [comment]
If you click on the document name on the headerbar, a popover will open with a save as button. :)

**Comment by SilverMarcs** [comment]
> If you click on the document name on the headerbar, a popover will open with a save as button. :)

unfortunately for me, nothing pops upon pressing save as button. running from terminal doesnt seem to give any meaningful output either, beside something related to statusbar

**Comment by lainsce** [comment]
Weird... it should have open up a Save As dialog from the system via a portal.

Maybe there's things missing in your OS install?

**Comment by SilverMarcs** [comment]
> Maybe there's things missing in your OS install?

Not sure what could be missing. Its a plain installation of fedora. and in any case, shouldn't flatpak be gathering all required components anyway?

**Comment by lainsce** [comment]
> Not sure what could be missing. Its a plain installation of fedora. and in any case, shouldn't flatpak be gathering all required components anyway?

Yeah, I meant like flatpak things breaking like a flatpak portal missing or something... but anyways, sorry to not being able to help you further. :(
