### ISSUE TITLE
Quilter themes are installed to a system directory

### ISSUE THREAD

**Issue by aleksandar-stefanovic** [lainsce/quilter#39]
This could be problematic because they're permanently there, and the user need to have root privileges to remove them.

The alternative is to append the path of your app's data directory to the search paths of the StyleManager and then copy the style files to that directory. (I can submit a commit if you confirm this issue).

**Comment by lainsce** [comment]
They're not permanently there since once you uninstall Quilter, the files are not there.
It's all clean uninstall, otherwise my app wouldn't even be on AppCenter.
