### ISSUE TITLE
Quilter not available in Elementary AppCenter by default

### ISSUE THREAD

**Issue by JohnDumpling** [lainsce/quilter#392]
After the release of eOS 6, the Quilter app is not included in the AppCenter. After adding the Flathub repository by sideloading a random Flatpak app, Quilter shows up as a non-curated app with a Gnome icon and UI look (does not fit the Elementary stylesheet).

**Comment by lainsce** [comment]
That's what it is, Quilter isn't an elementary app anymore, it follows GNOME guidelines.
