### ISSUE TITLE
Trouble Saving and locating documents in the filesystem

### ISSUE THREAD

**Issue by benji88i** [lainsce/quilter#399]
Hi there forgive me for being so inexperienced but is there a way to change the directory of where the files get saved. Or can I manually select the file path somehow. I dont seem to get a save dialogue box popup when saving. It seems to save in the home directory.

Also is there a way to see the different file versions.

A readme file would be great or help documentation. I simply love the app thanks so much for building such a great program.!

* State what version you're using
Version 3.30
OS: Fedora 36 Gnome

Thanks!

**Comment by lainsce** [comment]
Quilter is deprecated and inactive in development; I suggest moving to Apostrophe.
