### ISSUE TITLE
[Suggestion] Consider implement already existant proofreading tools

### ISSUE THREAD

**Issue by lf-araujo** [lainsce/quilter#41]
I read in the elementary blog where this app was featured that you plan to support marking adverbs and adjectives. I suppose you are aiming at something similar to Hemingway editor. This is good. 

>  Also, I’m studying how to make a custom highlighting work so you can highlight verbs, adverbs and adjectives so that you can structure your stories better.

I wanted to bring to your attention that although not as colorful, the readability cues that the Hemingway supports are all implemented in an opensource (Java, yes unfortunately) tool called [LanguageTool](languagetool.org).   Please consider using it even if temporarily, because I firmly believe such a tool would benefit of a rewrite in C/Vala. 

I have tons of suggestions to make for a writer focused in markdown, which I never had time to implement due to lack of time now. I use pandoc  professionally every day for the production of large, complex reports.

**Comment by lainsce** [comment]
Wow, that is precisely what I needed for this!
Thanks for the suggestion! I'm going to find a way to use this. 😃

**Comment by lf-araujo** [comment]
I really appreciate the invitation, but I am in the last months of a PhD thesis and I can't participate right now unfortunately.  That said, I am involved in a project for high level typographic rendering of documents, which I cant disclose right now. But there is a tool created by me that you may be interested, it is a pandoc building system: [Mighty Make](https://lf-araujo.github.io/2017/04/08/mightymake.html) (just reached v1.0 and now supports beamer). Perhaps, you should consider Mighty Make's "API" as a backend to your app rendering abilities. 

Further, there are specifications for my daily workflow with pandoc [here](https://lf-araujo.github.io/2016/11/07/mdworkflow.html). 

Best.

**Comment by lainsce** [comment]
The invitation is timeless, as your PhD thesis comes first 😉

I'll look around in Mighty Make too.

If anything, my telegram is *@lainsce* so, contact away when you're free.
