### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by caio-hungria** [lainsce/quilter#42]
I'm getting random crashes while using Quilter. I guess it isn't related, but it first happened when I copied a chunk of text from whatsapp through Rambox messaging app.
And now it's happening all the time. Less than 5 minutes of use and it will happen, for sure. I can't tell if it has something to do with the latest update.
So I ran it through terminal, and this is the message I get when it crashes:

[ERROR 18:24:35.656839] FileUtils.vala:110: Error: Erro ao remover arquivo: Dispositivo ou recurso está ocupado
Trace/breakpoint trap (imagem do núcleo gravada)

One more thing, I opened a new file (there was random text in the app) and selected "Close without saving", that first time it happened.

**Comment by lainsce** [comment]
Please wait until Quilter 1.2.0 is released in AppCenter, it fixes this bug. 😄
