### ISSUE TITLE
Beta Testing the Preview Mode

### ISSUE THREAD

**Issue by OriginalFannibal** [lainsce/quilter#48]
This is the writing app I've been waiting for my entire life and I am so happy to hear that a preview mode is in the works. Is there any way I can help beta test it or is there anywhere one can track progress on that front?  

Thank you so, so much for something this amazing!

**Comment by lainsce** [comment]
You can track it by going on the Projects tab right here on the lainsce/quilter repository.
It's currently at 0% done (:joy:) however, since I'm studying how to make it, and another guy was solicit and helpful and is working on it for me, so expect some progress on it.

**Comment by OriginalFannibal** [comment]
Thanks :)

Looking forward to it!
