### ISSUE TITLE
Save function does not work

### ISSUE THREAD

**Issue by fauliath** [lainsce/quilter#49]
When overwriting an existing save, or creating a new save, the result is not actual written to the file, nor is a new file created.

**Comment by lainsce** [comment]
Which version are you on? I'm asking because I'm not sure how this is affecting people in the current release.
Please provide what shows up if you type `com.github.lainsce.quilter` in Terminal while using the app for saving and etc.

**Comment by lainsce** [comment]
Does master/1.2.3 fix this for you?

**Comment by sempasha** [comment]
Please reopen the issue, save files does not work.
Quilter version 1.7.5.

- Save as - works well.
- Save (when autosave disabled) - do nothing.
- Autosave (when enabled) - do nothing.

I'd lost contents of my files several times already.

**Comment by lainsce** [comment]
I've not encountered any of that in the latest version of Quilter so I dunno what to do.

**Comment by sempasha** [comment]
Ok, how to install latest version. Is it available at ElementaryOS application store@

**Comment by lainsce** [comment]
When it passes review.

**Comment by sempasha** [comment]
Just updated to latest version 1.8.

- Save as button - works well.
- Save button (when autosave disabled) - works well.
- Autosave (when enabled) - not works.

Maybe I misunderstood the concept of autosave.
What I expect autosave will do:

  1. Saves changes time to time, lets say every 10 seconds I'm writing.
  1. Saves changes immidiatelly when stop writing, for example in case window lost focus or closed.

Could you, please, explain - how autosave should work?

**Comment by lainsce** [comment]
Autosave will save every 10 seconds you're writing, _if Quilter detects changes as well._ If there's no change, there's no save going to be made.
