### ISSUE TITLE
select all ( Ctrl + A ) does not work ( makes the app exit)

### ISSUE THREAD

**Issue by rezk2ll** [lainsce/quilter#51]
Hello, I like the app very much,
currently, i have trouble selecting all the text( i have to click my mouse and select all )
it would be better if there is a keyboard shortcut ( CTRL+ A ) to select all. hitting ctrl+a makes the app exit.

**Comment by lainsce** [comment]
I’ll work on this and add it to the 1.2.3 release that’s cooking. 👍
