### ISSUE TITLE
When does an update make it to the AppCenter?

### ISSUE THREAD

**Issue by OriginalFannibal** [lainsce/quilter#52]
This is not an issue really but this seemed like a better place to ask this question than over mail. I noticed that 1.2.3 is out now but the version available on the AppCenter is 1.2.2.  

How long does it usually take for an update to be available on the AppCenter after it has been released here?

**Comment by lainsce** [comment]
It depends if all the human testing is done by the AppCenter curators. It’s usually around 2 to 3 days. I know 1.2.3 is the biggest release yet for Quilter so that might be what’s causing the delay.

**Comment by OriginalFannibal** [comment]
That's a pretty long time by today's standards. 

I thought I'd grab the `.deb` file and install it directly but here is what I get when I try to do that. I am using Eddy to install the `.deb` file.  

    com.github.lainsce.quilter_1.2.3_amd64.deb: E: Sub-process Popen returned an error code (2)
    E: Encountered a section with no Package: header
    E: Problem with MergeList /home/loki/Downloads/com.github.lainsce.quilter_1.2.3_amd64.deb
    E: The package lists or status file could not be parsed or opened.

**Comment by lainsce** [comment]
Yeah, I know it’s not speedy enough, but you have to understand that elementary has a small team of developers juggling between OS stuff and AppCenter stuff.

**Comment by OriginalFannibal** [comment]
And they are doing an absolutely phenomenal work :)  
Looking forward to trying it out once it makes it there.
