### ISSUE TITLE
Reducing the line length/Centered Layout

### ISSUE THREAD

**Issue by OriginalFannibal** [lainsce/quilter#53]
Currently, the line length nearly extends the entire width of the screen. The [line length](http://practicaltypography.com/line-length.html) is an important determiner of readability and it also makes a significant difference while writing.  

Packages such as [Zen](https://atom.io/packages/Zen) for Atom let you control the width to make writing easier and I was wondering if this could be implemented natively in Quilter. Here is what this looks like in another writing app called [Focus Writer](https://gottcode.org/focuswriter/screenshots/focuswriter_retro.png).  

Atom has to fulfill a lot of roles and is primarily an editor for code but Quilter focuses exclusively on being a minimalist *writing* app. This could be offered as the new default and I really think this would be a significant improvement. A length of 80 characters is what is offered usually and that would be a good default.

Also, if you decide to implement this then I would really appreciate making it the default experience and not relegating it to the Focus mode.

**Comment by lainsce** [comment]
I’m going to study how to implement this and it’s going to be on 1.2.4

**Comment by OriginalFannibal** [comment]
> I think it's better to have these suggestions for the Preview Mode instead, since there's where you'd be reading your story.  

While it is a regular feature of ebook readers, I also find it very useful while writing as it keeps my eyes focused on a smaller region of the screen instead of having to scan the entire width of it. 

Could you try out how it feels? You could use the Zen package in Atom. The Typewriter package for Atom provides a similar experience. It really is helpful.

**Comment by lainsce** [comment]
The problem with this when I tested it out is that I can't really clip the text area to be 80 characters per line, it really gets cramped and unusable when I do it, but I can center the text part of the window, but then all text becomes like when you enable centered text in Word, where text doesn't look right-aligned but centered, it starts typing from the center and grows from there.

**Comment by OriginalFannibal** [comment]
Could the code for those two packages be of any help? Here is [Typewriter](https://github.com/braver/typewriter) and here is [Zen](https://github.com/defunkt/Zen). I don't know how useful they might be since they are targeting a different platform and all but they do implement it really well.

**Comment by lainsce** [comment]
Well, those are indeed great and all buuut they’re written for Atom, which is JavaScript/TypeScript, not Vala with Gtk which is what I use for Quilter. Besides I found a way to do it, at least doing centering right and I’ll finalize and push tomorrow, when I also will implement the spelling thing.

**Comment by OriginalFannibal** [comment]
You are amazing! Looking forward to it so much!  

There is something else I wanted to discuss with you too and it is kinda related to this issue so I don't know if I should be opening a separate one for it. I wonder if you noticed that Zen vertically centers the line that you are currently typing. This only comes into play when you reach the center of the document (which means that you'll still be starting at the top) but any further lines you type makes the document scroll up so that the line currently being typed is always at the center.

I know I might not have explained it well so here is a gif I made.

![zen](https://user-images.githubusercontent.com/20235646/29000708-9f8ea55a-7a91-11e7-9180-d0b8639f7358.gif)

It also centers whichever line you go back to work on later by clicking on it but doesn't reflow the screen if you're just scrolling or using the arrow keys. What do you think?

**Comment by lainsce** [comment]
That's a feature of browsers and can't be done if I'm outside of a browser entry like Atom uses for its text places.
The only thing I can do is center the lines visually by putting in some margins, for centering the layout and also reducing line length, but that's it.

**Comment by OriginalFannibal** [comment]
That's okay then. A centered layout would be awesome in itself :)  
The centered layout would be available while reading as well, right?

**Comment by lainsce** [comment]
Yep, it'll be in both Edit View and Preview View! :smile:
