### ISSUE TITLE
Search with Highlighting and Replacing

### ISSUE THREAD

**Issue by OriginalFannibal** [lainsce/quilter#54]
Would be really handy to be able to search for words which would be highlighted in the document and you could then switch between highlighted words with enter, the way we can in browsers. 

Replacing a chosen words could be implemented alongside it and could save a lot of time, especially in lengthier projects.

**Comment by lainsce** [comment]
I'll look into this and how I can add it.

**Comment by lainsce** [comment]
UPDATE: This function didn't play well with the app, so it might require more work or maybe it's best to let it be without it.

**Comment by OriginalFannibal** [comment]
Would it at least be possible to implement search highlighting or is that as complex as implementing it along with replacing?

**Comment by lainsce** [comment]
I'm studying how to enable searches in-app to have search highlighting as that's a bit easier to do.

**Comment by lainsce** [comment]
Would you mind if I let this be for another version in the future, when the Preview Mode is in place?
I think it'll be easier to add in when that happens.

**Comment by OriginalFannibal** [comment]
Not a problem at all.
Thanks for being so supportive of requests :)
