### ISSUE TITLE
Feature Request: Autocomplete words 

### ISSUE THREAD

**Issue by OriginalFannibal** [lainsce/quilter#55]
Autocomplete would trigger once a minimum of 3 characters had been typed and would offer options from the words used in the current document, to avoid overwhelming the user and it would have the added benefit of being contextual. I guess this list would be constantly updated as the user works on the document and would need to be (re)generated each time a new document is opened.

I think this would be great and would fit in well with the goals of this app but I don't know about how feasible this is from a technical standpoint. Just wanted to bring this up for discussion.

P.S: This is the last request from the list I made of what would make Quilter the perfect writing app (admittedly, for me).

**Comment by lainsce** [comment]
I don't think this can be done, alas, wouldn't it be kinda strange to have an auto completer for every language in the planet? I dunno.

**Comment by OriginalFannibal** [comment]
> I don't think this can be done, alas, wouldn't it be kinda strange to have an auto completer for every language in the planet? I dunno.  

Which is why I suggested using offering only words from the current document. Like when you've typed in a lengthy name once and then each time you enter the first 3 characters of the name later, the name would be offered for autocompletion. That should be more doable, right? But if it isn't then you can close the issue. Just wanted to bring it up for discussion is all.

**Comment by lainsce** [comment]
You see, for me to come up with all the words in the document for easy auto-completion, I would need to live update a cache of words used in the open document, which would also be removed once I change documents on the fly, and replaced by a new cache of words.

**Comment by OriginalFannibal** [comment]
You said it better than I could have. That's... um, a problem then?

**Comment by lainsce** [comment]
Yes, a problem, since it adds unnecessary complexity. :disappointed:

**Comment by OriginalFannibal** [comment]
I understand. Would you rather leave the issue open to return to at some later date or should I close it?

**Comment by lainsce** [comment]
Let me do the closing stuff for you. It's still on the closed issues list for future returning, no harm done.
