### ISSUE TITLE
Unsaved changes

### ISSUE THREAD

**Issue by Djaler** [lainsce/quilter#56]
Steps to reproduce:
1) Open or create new file
2) Make some changes
3) Save file
4) Try to open or create new file

You will see dialog about unsaved changes

**Comment by lainsce** [comment]
That's a saving prevention for some use cases where you want to really make sure to save the file before opening a new one. You can see it on the closed issues list where somebody told me that opening a new file made them lose the file they were working on.

**Comment by Djaler** [comment]
But this is bug. I don't want to save my file twice. What other text editor does this?

**Comment by Senpos** [comment]
I am really sure I saved the file when I press the save button and no changes were added to file after. So there are no reasons to ask user to save file again, since its already saved by him, unless you have problems in your main saving mechanism.

**Comment by Senpos** [comment]
If you want to make sure that data will still persist after editor is closed even if there were no changes (which is weird) - just save it in background to the temporary file and retrieve data from there once user is trying to open the file he worked before. This is how popular editors works (or at least close idea).

**Comment by lainsce** [comment]
I just found out which dialog you were referring to, and surely, this is not needed anymore! 😂 
I’m going to remove it on the next release.
