### ISSUE TITLE
Open a file only once

### ISSUE THREAD

**Issue by lmberg** [lainsce/quilter#58]
If the user has opened a markdown file in a Quilter window and opens that file again, one of the two things should happen:

- Don't open a second but instead bring the first one to the front
- Open a second window and warn that the file has already been opened in another window in both windows.

IMO, the first option is the better one as this is the default behaviour in most apps. There is some quite nice API in GtkApplication in order to implement this.

**Comment by lainsce** [comment]
This first option is what actually happens already in Quilter 1.2.5, despite not looking like it. :+1:

**Comment by lmberg** [comment]
Seems like that is not entirely true, at least not for me. I checked and my version of Quilter is 1.2.5.

When opening the same file two times from the command line, the first instance stays running while the second one quits immediately. However, there is still a second editor window popping up. Seems like that is being spawned by the first instance - when I kill the first instance, both editor windows disappear.

**Comment by lainsce** [comment]
I see. Thanks for explaining, I'll see what I can do :+1:

**Comment by lainsce** [comment]
Fixed in 1.2.6
