### ISSUE TITLE
Save as switch

### ISSUE THREAD

**Issue by Djaler** [lainsce/quilter#60]
When I make "Save as", editor should switch current file to saved file

**Comment by lainsce** [comment]
Hi! Can you give me more details, like console output or a video showing this bug happening? It would make this a bit easier to know what to fix.

**Comment by Djaler** [comment]
https://youtu.be/hb4AzgJ1Tkc - quilter behaviour
https://youtu.be/s4LM6kpCXno - sublime text behaviour

**Comment by lainsce** [comment]
This is fixed in 1.2.8, have fun!
