### ISSUE TITLE
Old file recreating

### ISSUE THREAD

**Issue by Djaler** [lainsce/quilter#62]
When I open Quilter, if last file was deleted, Quilter recreate it. I think it should just launch "New file" mode

https://youtu.be/kVKDzAjzJAM

**Comment by lainsce** [comment]
Will work on it.

**Comment by Djaler** [comment]
https://github.com/lainsce/quilter/blob/632913be88069532629a1e8d43a7b08abce7bc88/src/Services/FileUtils.vala#L34 there you create file from AppSettings.last_file if it doesn't exist. Insted of this you should call FileUtils new_document, I think

**Comment by lainsce** [comment]
I see, will fix!
