### ISSUE TITLE
As a user when I save a file I want the file extension to be automatically appended on the end of the file name.

### ISSUE THREAD

**Issue by TimBritton** [lainsce/quilter#63]

**Comment by lainsce** [comment]
Will fix it, expect it on 1.2.9

**Comment by TimBritton** [comment]
I would fix it myself but unfortunately with my contract at work it makes everything complicated...

**Comment by lainsce** [comment]
I was searching about this, and the default and only way GTK deals with files is not touching their extensions. So, sadly, I think you'll need to wait for me to come up with a "hack" to enable this.
