### ISSUE TITLE
unable to maximize on a second monitor

### ISSUE THREAD

**Issue by jendamarek** [lainsce/quilter#64]
I'm unable to maximize the window when moving it to the second (not primary) screen.
It may be related with the fact that it's not a standard window.

**Comment by lainsce** [comment]
I'm afraid that's not Quilter's fault, sadly. Gala (the window manager) needs some love in the multi monitor side still.

**Comment by jendamarek** [comment]
I know, but maximizing other windows works. 
For example https://github.com/donadigo/appeditor which uses similar window look works.

**Comment by lainsce** [comment]
I'll search about this and fix it for 1.2.9 :smile:

**Comment by lainsce** [comment]
Due to inactivity, and my rewritten code on 1.3.0, I consider this fixed.
