### ISSUE TITLE
Turn off markdown highlighting

### ISSUE THREAD

**Issue by sgpthomas** [lainsce/quilter#65]
I often use this as a sort of notepad to help me think through problems. For this kind of work, I have no need for syntax highlighting. It would be nice to be able to turn it off.

![image](https://user-images.githubusercontent.com/3752122/30613492-4e9590f4-9d56-11e7-9bf7-4acc5978d887.png)

**Comment by lainsce** [comment]
Quilter is made to be a way for you to easily write and structure stories, and it does this by leveraging Markdown's features. I admit that I've been slacking off on the Preview Mode that is where all this Markdown is supposed to go. I'm expecting to have a "first preview" of Preview Mode in Quilter 1.3.0.
Turning off the Markdown would make Quilter not Quilter, if you catch my reasoning.
