### ISSUE TITLE
Improve the temporary file management

### ISSUE THREAD

**Issue by tintou** [lainsce/quilter#66]
In MainWindow.vala, you are doing this:
```
var home = GLib.Environment.get_home_dir ();
settings.last_file = @"$home/.cache/com.github.lainsce.quilter/temp";
```
You might want to use https://valadoc.org/glib-2.0/GLib.Environment.get_user_cache_dir.html
Or even https://valadoc.org/glib-2.0/GLib.FileUtils.mkstemp.html if you don't want the file to persist between sessions

**Comment by lainsce** [comment]
I'll fix this for 1.3.0, thanks for pointing that out. :+1:
