### ISSUE TITLE
Quilter can accidentally wipe out the contents of a file

### ISSUE THREAD

**Issue by donadigo** [lainsce/quilter#67]
1. Create a new file in Files with some contents.
2. Open it with Quilter.
3. Press Ctrl+Z a couple of times and close the window.
4. The contents disappear from the file.

A few ways to prevent this:
* Show a dialog that there are unsaved changes.
* Do not clear the document when pressing Ctrl+Z in an freshly opened document.

**Comment by lainsce** [comment]
> Do not clear the document when pressing Ctrl+Z in an freshly opened document.

This solution interested me. How would I go about using this solution?

**Comment by donadigo** [comment]
@lainsce actually, those two ways should be implemented. 

What I mean is, Ctrl+Z should revert *only* operations that are done by the user and not what's internal to the editor. The opened document has some contents in it, and it should not revert to a blank document which is not the state of the original.

**Comment by lainsce** [comment]
How would I do this then as basic as possible? 😉

**Comment by lainsce** [comment]
I believe this was fixed in 1.3.0 so I'm going to close this issue.

**Comment by Djaler** [comment]
This is not fixed in 1.3.1

**Comment by Djaler** [comment]
Can you test before closing issue, please

**Comment by lainsce** [comment]
I accidentally autoclosed the issue by saying "fixed in 1.3.0", Github understands it as "issue fixed, so close it."

**Comment by lainsce** [comment]
Does the issue persist in 1.3.2?

**Comment by Djaler** [comment]
Yes

**Comment by lainsce** [comment]
I see, but I believe this part here:
* Do not clear the document when pressing Ctrl+Z in an freshly opened document.

Is  almost done, I just need to know what's wrong, while,
* Show a dialog that there are unsaved changes.

Is not needed

**Comment by Djaler** [comment]
> this part is almost done
It doesn't. I still can clean my file by pressing Ctrl+Z after file opening

**Comment by lainsce** [comment]
By almost done, I mean: Try pressing Ctrl-Z two times. The text disappears the first time, then reappears.

**Comment by Djaler** [comment]
This is not a solution

**Comment by lainsce** [comment]
Exactly. That's why I said _almost done_. It's not solved, but it's partially solved.

**Comment by lainsce** [comment]
Does the master branch now fix this issue?

**Comment by lainsce** [comment]
I believe I've fixed this in 1.3.2, if you find any discrepancies or further bugs, please open a new issue.
