### ISSUE TITLE
Temp file in header

### ISSUE THREAD

**Issue by Djaler** [lainsce/quilter#68]
Steps to reproduce:

1. Open Quilter
2. "New file"
3. Close
4. Open Quilter

Now in header you'll see path of temp file in .cache

**Comment by lainsce** [comment]
That's correct. The temp file is the "New Document".

**Comment by Djaler** [comment]
https://youtu.be/WKEmFRmuFd0

**Comment by lainsce** [comment]
Yep, that's correct behavior: When you do have New Document in the subtitle and re-open it, it's actually the temp file that's opened so that you don't lose what you didn't save. It's the same mechanism of Notejot when dealing with the note, but there, you don't have the subtitle.

**Comment by Djaler** [comment]
Users shouldn't now about a way the temp file saved.

**Comment by lainsce** [comment]
So you're saying that I should mask the subtitle in that instance?I'll see what I can do

**Comment by Djaler** [comment]
I think you should look how all this interactions with users implemented in Sublime Text, for example

**Comment by lainsce** [comment]
This is fixed in master, closing this issue.
