### ISSUE TITLE
"New file" reacts after second click

### ISSUE THREAD

**Issue by Djaler** [lainsce/quilter#70]
Steps to reproduce:
1. Open Quilter
2. Click to "New file" -> No reaction
3. Click again -> Dialog opened

**Comment by Djaler** [comment]
https://youtu.be/t_7oS83nwiA

**Comment by lainsce** [comment]
I'll try to fix this on a future release. 👍

**Comment by Djaler** [comment]
I think problem somewhere here https://github.com/lainsce/quilter/blob/master/src/MainWindow.vala#L307.

**Comment by lainsce** [comment]
Can you check if master fixes this problem?

**Comment by lainsce** [comment]
After extensive testing in master, I think I can say that this is fixed.
