### ISSUE TITLE
Can't pay for Quilter?

### ISSUE THREAD

**Issue by peteruithoven** [lainsce/quilter#76]
I've tried several times over the last few months to pay for Quilter, but I've never been able to. Even though I've payed for lot's of other apps. 
@lainsce are you receiving payments from other users? 
Are others experiencing this specifically when paying for Quilter? 

I'm getting the following very vague error:
> There was a problem processing your payment
> An error occurred while processing the card. Please try again later. We apologize for any inconvenience caused.

![screenshot from 2017-10-08 14 57 25](https://user-images.githubusercontent.com/523210/31316996-07849ac4-ac39-11e7-8474-8ca7ee4fb4c2.png)

The only relevant issues I've found
- https://github.com/elementary/appcenter/issues/391
- https://github.com/elementary/houston/issues/483

**Comment by lainsce** [comment]
During a small window back in July-August, I was able to be paid in AppCenter.
But now, Stripe which is the backend for AppCenter payments, seemingly blocked brazillian accounts from accepting USD (US Dollars) or any currency other than BRL (Brazilian Reais).

I suggest that you pay me via [Patreon](https://www.patreon.com/lainsce) instead until Stripe unblocks Brazilian accounts.
(I always give back to elementary in Patreon so don't worry, the fee for them is paid for.)

**Comment by peteruithoven** [comment]
Damn, that sounds very annoying. I'm assuming you've contacted support? There is no way to setup a forwarding kind of account in another country? 

I'll use Patreon. 

Disabling AppCenter payments for now seems like a good idea. Maybe you could point to Patreon in your app description?

**Comment by lainsce** [comment]
Yeah, I've contacted support, but they redirected me to open an account in the US site with an US account. :joy: 

Yeah, I'm disabling payments for now in 1.3.6 onwards.
