### ISSUE TITLE
Suggestion: Nicer way to display markdown cheatsheet

### ISSUE THREAD

**Issue by yeboahnanaosei** [lainsce/quilter#77]
Hello Lainsce,
Thanks for all the work you've done on Quilter. It keeps maturing by every update. I would like to suggest that perhaps you should display the markdown cheatsheet like the way Notes-Up does it. With Notes-Up, you have the cheatsheet inside the editor so your workflow isn't interrupted. You can keep writing and still have the cheatsheet right there.
![screenshot from 2017-10-08 20-43-39](https://user-images.githubusercontent.com/22800157/31320777-c267f824-ac69-11e7-940c-15d79b81518c.png) 

 Whereas with Quilter, you get a separate pop up showing you the cheatsheet. You "market" Quilter as an app that allows you to focus on your writing. With that in mind I feel having the cheatsheet appear inside the editor will let Quilter stay true to itself; i.e. an app that makes you focus on your writing. Having a separate pop up sometimes disrupts the writing process for me.
![screenshot from 2017-10-08 20 52 13](https://user-images.githubusercontent.com/22800157/31320824-a1c0945e-ac6a-11e7-82f7-54cda11ac9d4.png)

**Comment by lainsce** [comment]
I'll see how I can integrate better the cheatsheet with Quilter. :+1:

**Comment by lainsce** [comment]
In 1.3.7, I made using the Cheatsheet more effortless and less distracting.
It's still a popup dialog, but it doesn't get in the way now.

**Comment by yeboahnanaosei** [comment]
Ok. will be waiting for the update

**Comment by lainsce** [comment]
New feature that you'll like: Ctrl-H both opens *and* closes the cheat sheet. So no more lifting of the hand from keyboard to mouse is required to close it.

**Comment by yeboahnanaosei** [comment]
Cool.. Waiting to see how it will look like
