### ISSUE TITLE
Add hotkey to switch between 'Edit' and 'Preview'

### ISSUE THREAD

**Issue by JonnyCodewalker** [lainsce/quilter#78]
Having a hotkey/keycomb to switch between these modes would be nice to make a quick check of the final look more accesible.

Personal reccomondation would be F1, since it is easily accesible.

**Comment by lainsce** [comment]
Will look into it!
Expect this in 1.3.7

**Comment by JonnyCodewalker** [comment]
For longer files it probably makes sense to jump to the position in the preview where the cursor is in the edit.

**Comment by lainsce** [comment]
That's not possible with GTK + Vala, I think.
That's a commonly written feature of Javascript called a scrollspy.

**Comment by lainsce** [comment]
Anyhoo, it's going to be in 1.3.7. Pressing F1 will change between modes now.
