### ISSUE TITLE
When using 'Tab' in the Cheatsheet instantly switch page

### ISSUE THREAD

**Issue by JonnyCodewalker** [lainsce/quilter#80]
Currently you have to press Tab and then enter to look at another page of the cheatsheet. Enableing a "fast-switch" might make the workflow more fluent.

**Comment by JonnyCodewalker** [comment]
Alternatively this could be solved by showing all informations on one page.

**Comment by lainsce** [comment]
I'll see what I can do for this in 1.3.7 :+1:
