### ISSUE TITLE
Automatically append .md file extension to files when saving

### ISSUE THREAD

**Issue by angjinhang** [lainsce/quilter#81]
Currently saving files with type "Markdown files" will not give a .md file extension to them. While the file is still perfectly readable and editable, it will confuse users (especially new users) that their files does not have a file extension and might assume that they are broken. 

Automatically saving files in .md might also help when directly opening them from the file manager as they are recognized. 

Thanks

**Comment by lainsce** [comment]
This is not possible with the app's backend which is GTK3. It doesn't support automatically appending an extension on the filename on the dialogs unless you've already had a file with that extension to rename and save to a diffferent location.

**Comment by angjinhang** [comment]
Well, I mean, although it is not shown in the save dialog, it should automatically be appended when the file is written (which I'm very sure that GTK doesn't do any file writing).

For example, 
Writes file name without extension in dialog -> Chooses "Markdown files" in the drop down list next to file name -> Automatically write `<filename>.md` instead of `<filename>` when writing the file.

It should be a good thing :thinking: although Scratch also doesn't does it like that (Text files -> no extension if not provided). Maybe I should file a report there too.

**Comment by lainsce** [comment]
Yeah, I did understand what you wanted, don't worry. And yeah, even Scratch suffers from this because it simply isn't possible with GTK3 and Vala, to the best of my knowledge with both technologies. :thinking:

**Comment by angjinhang** [comment]
Somehow Scratch didn't implement file extensions is because that UNIX systems don't need file extensions especially for text files. Refer https://github.com/elementary/scratch/issues/233

Makes sense, but then if we have the .md extension it will allow us to directly open saved files from the Files app (since the .md extension will automatically associate it with Quilter). Not an ideal solution, but maybe a dirty hack could do it eh :thinking:

**Comment by lainsce** [comment]
Yeah, dirty hacks won't fly in AppCenter apps, it needs to be an accepted syntax in Vala to access the extension at saving, sadly, so, it'll need to be like this until someone makes it easier and in-syntax to do it.

**Comment by TimBritton** [comment]
It's it not allowed to save the file with the user file name and then check
to see if the saved file has .md at the end and if it doesn't rename the
file appending .md at the end? I'm not too familiar with vala but I've
written python apps where I had to do something similar because of the
similar restrictions.

**Comment by lainsce** [comment]
Yeah, if I do that, the saved file will always get an .md at the end, leaving you with funny files like `test.md.md.md.md(...).md` currently.
