### ISSUE TITLE
Autosave overwrites wrong file

### ISSUE THREAD

**Issue by bebeki** [lainsce/quilter#83]
If I open Files and click on several Markdown files, all of them open in Quilter, but some of them get overwritten by others. I've lost several files to Quilter which overwrites the contents of one file with the text from another. 

**Example:**

- I open two files, 1. Outline and 2. Draft
- I then close both of them. 
- When I open Outline later, I find the content for Draft inside both documents. Somehow, all of the content for Outline was erased and replaced with Draft.
- End result, I have two copies of Draft (with one still called Outline) and have lost whatever was saved in Outline.

What seems to happen is that Quilter plans to autosave a file, but by the time it does so, I've opened another one, so it saves over that one instead. I'm only guessing. I wish I knew for certain what was going on so that I could provide you with more helpful information. I love Quilter, but I can't use it if I keep losing work.

**Comment by lainsce** [comment]
Quilter is made so you don't open multiple files per session, only one at a time.
Sorry for making you lose those files. :disappointed:

**Comment by bebeki** [comment]
In that case, is there anyway to prevent Quilter from opening multiple files at once? If I click on a file in Files, can you have it close the first window when it opens the second? I set Quilter to be the default app for Markdown files, and there's nothing to indicate that it can't handle multiple files at once since it opens each file in a new window. Alternatively, you can make it so that users can't open a new file in Quilter via Files.

**Comment by lainsce** [comment]
It shouldn't open a new window for each file when you open multiple files, so that's another issue you could open. I will however, try to find a solution for showing that Quilter can't open multiple files in the UI.

**Comment by bebeki** [comment]
'k, I've opened a separate issue for that. Thanks for the speedy responses and creating such an awesome app!
