### ISSUE TITLE
App icon slightly too tall

### ISSUE THREAD

**Issue by bebeki** [lainsce/quilter#84]
Quilter has a great sense of style, but the app icon is a few pixels taller than almost every other app's. It seems especially jarring next to Notejot, but it doesn't matter what app I put Quilter next to, it's taller than almost all of them. Ideally the app would be the same height as Scratch.

![quiltericon](https://user-images.githubusercontent.com/32748700/31515375-f920f478-af62-11e7-99d8-6b3279767c78.png)

**Comment by lainsce** [comment]
Fixed in master, is going to be released in Quilter 1.3.9
