### ISSUE TITLE
Quilter opens a new window for each file when launched from file manager

### ISSUE THREAD

**Issue by bebeki** [lainsce/quilter#85]
Quilter is designed to handle only one file at a time, but if you open a file via the file manager, it will open numerous windows with no indication that this isn't intended behavior. This results in data loss.

**Comment by lainsce** [comment]
Can you show me further information on this? Ideally:
* Screenshot of the multiple windows
* Terminal output when you run `com.github.lainsce.quilter --debug` and then open the files
* Current version of Quilter installed in your machine. e.g. 1.3.7

**Comment by bebeki** [comment]
Oops, I opened this bug from memory, but I remembered the behavior completely wrong. Quilter doesn't open multiple windows.

I was unable to get you a screenshot. Here's what happened when I tried.

- Click on a file inside Files (rather than using the Open menu inside Quilter). It opens.
- Click on a second file, its content loads, but the title in the titlebar stays on the first file. Quilter then autosaves the second file's content over the first one.
- Click back on a third file. This happens again.
- I click back and forth a few times, not sure what just happened.
- After doing this a few times, all three files now show up as 0 bytes.

![quiltereatsmorefiles](https://user-images.githubusercontent.com/32748700/31519728-4e957272-af71-11e7-9d1e-d7a2a29220f9.png)

- Further clicks no longer open files in Quilter, but in Scratch instead.
 
I'll close this issue, since my memory of what happened was wrong, but I have no idea how to properly file this bug. I'm not sure what's going on. My take away is just to only open files from directly inside Quilter, because doing so via Files is dangerous.

For what it's worth, I'm running 1.3.7.

**Comment by lainsce** [comment]
Yeah, if you're on 1.3.7, then you don't have the fix for this which is going to be up on 1.3.8 this Friday (my time). Again, sorry for making it look like opening a file outside of Quilter is dangerous, it's not my intention, just a pesky bug already fixed :D

**Comment by bebeki** [comment]
Actually, I got the behavior to replicate.

I opened three files in this order:

1. [How To] Change Default GNOME Shell Font.md
2. [How To] Disable Recently Used List.txt
3. [How To] Remove AbiWord plugins.txt

All three times, the titlebar never changed from [How To] Change Default GNOME Shell Font.md.

First, file #2's content loaded up inside file #1.
![quilter1](https://user-images.githubusercontent.com/32748700/31520247-3f2b82ca-af73-11e7-9467-0c6985744804.png)

Then file#3 appeared to load up inside file#2 (while showing file#1's name)
![quilter2](https://user-images.githubusercontent.com/32748700/31520267-500a3ece-af73-11e7-8958-92c6905f09c0.png)

File#2 is now blank.
![quilter3](https://user-images.githubusercontent.com/32748700/31520301-68e53c3c-af73-11e7-8df0-74547e2425be.png)

File #2's content is somehow in file#1
![quilter4](https://user-images.githubusercontent.com/32748700/31520326-797a68ce-af73-11e7-8826-9b1c40099d4c.png)

In the end, file#1 and #2 are both blank. File #3 is fine.
![quilter5](https://user-images.githubusercontent.com/32748700/31520360-94cf990a-af73-11e7-8ff3-0415b442041e.png)

**What I got from the terminal:**
com.github.lainsce.quilter --debug
[INFO 17:22:52.299070] Application.vala:153: Quilter version: (null)
[INFO 17:22:52.299164] Application.vala:155: Kernel version: 4.10.0-37-generic
[DEBUG 17:22:52.349210] [Gtk] Connecting to session manager
[DEBUG 17:22:52.352451] Settings.vala:163: Loading settings from schema 'com.github.lainsce.quilter'
[FATAL 17:23:13.925867] gtk_spell_checker_attach: assertion 'spell->priv->view == NULL' failed
[FATAL 17:23:13.958031] gtk_spell_checker_attach: assertion 'spell->priv->view == NULL' failed
[FATAL 17:23:13.985955] [Gtk] gtk_header_bar_pack: assertion 'gtk_widget_get_parent (widget) == NULL' failed
[FATAL 17:24:32.310556] gtk_spell_checker_attach: assertion 'spell->priv->view == NULL' failed
[FATAL 17:24:32.343357] [Gtk] gtk_header_bar_pack: assertion 'gtk_widget_get_parent (widget) == NULL' failed
[FATAL 17:24:32.348384] gtk_spell_checker_attach: assertion 'spell->priv->view == NULL' failed
[FATAL 17:24:32.375221] [Gtk] gtk_header_bar_pack: assertion 'gtk_widget_get_parent (widget) == NULL' failed
[FATAL 17:25:28.282378] gtk_spell_checker_attach: assertion 'spell->priv->view == NULL' failed
[FATAL 17:25:28.307124] [Gtk] gtk_header_bar_pack: assertion 'gtk_widget_get_parent (widget) == NULL' failed
[FATAL 17:25:28.311455] gtk_spell_checker_attach: assertion 'spell->priv->view == NULL' failed
[FATAL 17:25:28.336845] [Gtk] gtk_header_bar_pack: assertion 'gtk_widget_get_parent (widget) == NULL' failed
[FATAL 17:26:13.485600] gtk_spell_checker_attach: assertion 'spell->priv->view == NULL' failed
[FATAL 17:26:13.511964] [Gtk] gtk_header_bar_pack: assertion 'gtk_widget_get_parent (widget) == NULL' failed
[FATAL 17:26:13.515507] gtk_spell_checker_attach: assertion 'spell->priv->view == NULL' failed
[FATAL 17:26:13.543748] [Gtk] gtk_header_bar_pack: assertion 'gtk_widget_get_parent (widget) == NULL' failed
[FATAL 17:29:00.198490] gtk_spell_checker_attach: assertion 'spell->priv->view == NULL' failed
[FATAL 17:29:00.230302] [Gtk] gtk_header_bar_pack: assertion 'gtk_widget_get_parent (widget) == NULL' failed
[FATAL 17:29:00.233404] gtk_spell_checker_attach: assertion 'spell->priv->view == NULL' failed
[FATAL 17:29:00.263716] [Gtk] gtk_header_bar_pack: assertion 'gtk_widget_get_parent (widget) == NULL' failed

**Comment by lainsce** [comment]
This is fixed in 1.3.8, up to review & release this friday, just wait patiently and you'll get this functionality fixed :+1:
