### ISSUE TITLE
Change preview translation so that it only occurs when visiting preview mode.

### ISSUE THREAD

**Issue by JonnyCodewalker** [lainsce/quilter#86]
At the moment quilter regularly updates the preview mode. Wouldn't it be better if it only did that when you are opening the preview mode? elementaryOS reports Quilter as using much power, so it would be beneficial for use on a laptop if it would preserve energy by not performing not necessary options.

**Comment by lainsce** [comment]
Due to how it works in tandem with the Edit View being changed, and also that whatever app that you have in the foreground is reported as using too much power, I'd believe that this is a non-issue.  

Besides, I always cache the Preview Mode so it doesn't need to always re-run.
