### ISSUE TITLE
Question / Suggestion: Shortcut key to switch between edit and preview mode

### ISSUE THREAD

**Issue by yeboahnanaosei** [lainsce/quilter#87]
Is there any shortcut key to switch between edit and preview mode? If there isn't then I think it will be great to have a shortcut key for that.

**Comment by lainsce** [comment]
There is one! :+1: 
Just press F1 and you'll change between views seamlessly.

**Comment by yeboahnanaosei** [comment]
Hmm. Great to know there is one. But Do you think F1 is the most intuitive option? Perhaps a `Ctrl + <key>` will feel more intuitive or familiar.

**Comment by lainsce** [comment]
I think it is intuitive since it's just a keystroke away, and won't make the user look at the keyboard to find the Ctrl + <key> combo every time.

**Comment by yeboahnanaosei** [comment]
Well, on my keyboard I need to press `fn + F1`
