### ISSUE TITLE
Add visual feedback for sucessful saving a file.

### ISSUE THREAD

**Issue by JonnyCodewalker** [lainsce/quilter#88]
Currently there is no indication as to wether or not a file was saved sucessfully. It might be benefitial to add a small indicator. Considering how paranoid users are about saving it will give them peace of mind.
And yes, I am one of these users.

One none intrusive option would be to gey out the "Save" Button if there are no changes to save, similar as to how most word processors do it.

**Comment by lainsce** [comment]
Maybe the subtitle should reflect that the file wasn't saved and then, when it saves, remove the indication. Kind of like: `<file path> *` when not saved, and just the file_path when saved.
Is this a good solution?

**Comment by lainsce** [comment]
Fixed in master/1.4.0, due to release 10/27/17
