### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by JonnyCodewalker** [lainsce/quilter#94]
Currently Codeblocks via ` ``` .... ``` ` do not support the annotation of a language for syntax highlighting ` ```java .... ``` `. This would be benefitial for programming oriented Texts.

**Comment by lainsce** [comment]
While I do like syntax highlighting as it makes code real easy to look at, Quilter was made to be tailored to be 100% focus driven, and as such, it doesn’t have any highlighted text. Besides, you could put the resulting markdown, after typing it out, in a place that does have highlighted text support as it’s universal.

**Comment by SkyzohKey** [comment]
It would be a pretty useful feature for people like me that often writes whitepapers and stuff related to code :x

**Comment by lainsce** [comment]
Well, it's not me, it's the default Markdown preformatter into the Preview Mode that doesn't do the highlights :disappointed:

**Comment by SkyzohKey** [comment]
Isn't it extendable ?

**Comment by lainsce** [comment]
AFAIK no, but I will look into it
