### ISSUE TITLE
Default values for spacing and margin are invalid

### ISSUE THREAD

**Issue by danrabbit** [lainsce/quilter#95]
https://github.com/lainsce/quilter/blob/0e8da22453514589526a57fa11ccb6a513b978b6/data/com.github.lainsce.quilter.gschema.xml#L71

The default value is a string but the code expects a number. It would be better for these settings to use an int, but at the very least the defaults should be what the code expects

**Comment by lainsce** [comment]
Fixed in 1.4.1/master
